### ISSUE TITLE
AttributeError: no such field 'release_group_id'

### ISSUE THREAD

**Issue by thde** [beetbox/beets#1080]
I get the following error if the fetchart plugin is enabled and i want to get the information from a discogs release. 

For example: http://www.discogs.com/Animal-Trainer-Pirates-EP/release/4593548

```
Traceback (most recent call last):
  File "/Users/thde/Music/tools/virtualenv_beet/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.9', 'console_scripts', 'beet')()
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/ui/__init__.py", line 935, in main
    _raw_main(args)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/ui/__init__.py", line 925, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/ui/commands.py", line 872, in import_func
    import_files(lib, paths, query)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/ui/commands.py", line 844, in import_files
    session.run()
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/importer.py", line 295, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/util/pipeline.py", line 299, in run
    out = self.coro.send(msg)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/util/pipeline.py", line 181, in coro
    func(*(args + (task,)))
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/importer.py", line 1261, in plugin_stage
    func(session, task)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beetsplug/fetchart.py", line 373, in fetch_art
    path = art_for_album(task.album, task.paths, self.maxwidth, local)
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beetsplug/fetchart.py", line 275, in art_for_album
    config['fetchart']['sources'].as_str_seq()):
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beetsplug/fetchart.py", line 248, in _source_urls
    for url in urls:
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beetsplug/fetchart.py", line 88, in caa_art
    if album.release_group_id:
  File "/Users/thde/Music/tools/virtualenv_beet/lib/python2.7/site-packages/beets/dbcore/db.py", line 309, in __getattr__
    raise AttributeError('no such field {0!r}'.format(key))
AttributeError: no such field 'release_group_id'
```

**Comment by asayler** [comment]
Hmm, I installed 1.3.10 from a dump of the master branch this evening, and I'm still getting an error similar to this trying to use the "media" field of albums that previously worked fine (e.g. prior to 1.3.9). Only instead of raising exceptions, my error just winds up in the file names. For example, trying to use the 'media' field as one of the disambiguation options leads to output like:

```2011 - Making Mirrors_no such field media_```

Which should actually be two separate folders:

```
2011 - Making Mirrors [CD]
2011 - Making Mirrors [Digital]
```

Here's path spec (with the non-relevant sections truncated for readability):

```
paths:
    default: $original_year - $album%aunique{albumartist album, albumdisambig media catalognum}/$track - $title
```

So it looks like there may be two issues here:
- The 'media' field does not work as a disambiguation field, leading to "no such field" errors.
- Errors raised during disambiguation get embedded in the file name instead of causing a runtime exception (which is why I didn't catch this sooner).
