### ISSUE TITLE
'MP4' object has no attribute 'codec'

### ISSUE THREAD

**Issue by dajo** [beetbox/beets#1117]
So I'm running from source on Windows and I'm having difficulty with, it appears, ALAC files. But it's also possibly M4A files; both of which are in my library. I can trigger the following with a 'beet update'

``` python
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\__init__.py", line 935, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\__init__.py", line 925, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\commands.py", line 1080, in update_func
    update_items(lib, decargs(args), opts.album, opts.move, opts.pretend)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\commands.py", line 1019, in update_items
    item.read()
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\library.py", line 443, in read
    mediafile = MediaFile(syspath(read_path))
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\mediafile.py", line 1344, in __init__
    if self.mgfile.codec and self.mgfile.codec.startswith('alac'):
AttributeError: 'MP4' object has no attribute 'codec'
```

and a slightly different version with 'beet import'

``` python
user configuration: C:\Users\Jason\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Jason\AppData\Roaming\beets
Sending event: pluginload
library database: D:\database\musiclibrary.blb
library directory: D:\Albums
Sending event: library_opened
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\__init__.py", line 935, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\__init__.py", line 925, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\commands.py", line 872, in import_func
    import_files(lib, paths, query)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\ui\commands.py", line 844, in import_files
    session.run()
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\importer.py", line 299, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\util\pipeline.py", line 249, in run
    msg = self.coro.next()
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\importer.py", line 1098,
in read_tasks
    task = task_factory.album(paths)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\importer.py", line 997, in album
    items = map(self.read_item, paths)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\importer.py", line 1015,
in read_item
    return library.Item.from_path(path)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\library.py", line 391, in from_path
    i.read(path)
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\library.py", line 443, in read
    mediafile = MediaFile(syspath(read_path))
  File "C:\Python27\lib\site-packages\beets-1.3.10-py2.7.egg\beets\mediafile.py", line 1344, in __init__
    if self.mgfile.codec and self.mgfile.codec.startswith('alac'):
AttributeError: 'MP4' object has no attribute 'codec'
```

So this occurs if the import directory or the library contains M4A/ALAC files. A directory with only MP3 files would work splendidly.

I have a pretty basic config right now, and I can replicate the above error with a blank config. Let me know how I can help isolate this.

Thanks!

**Comment by baykelper** [comment]
I had the same issue, installed from the tarball (per the faq), and verified that the error no longer occurs. (thanks!).   sorry I have very limited Python experience, so question:   How do we go back to the official release version? (once it is released).

**Comment by sampsyo** [comment]
You can use an ordinary `pip install -U`.
