### ISSUE TITLE
convert: Character encoding/path issue on Windows

### ISSUE THREAD

**Issue by mluds** [beetbox/beets#1166]
The convert plugin seems to have issues with certain characters. Here is the cmd.exe output when importing:

```
C:\Users\Michael\Desktop\blink-182\blink-182>beet import .

C:\Users\Michael\Desktop\blinkΓÇÉ182\blinkΓÇÉ182 (14 items)
Tagging:
    blinkΓÇÉ182 - blinkΓÇÉ182
URL:
    http://musicbrainz.org/release/f0359d59-315e-45e6-bf7b-170754bac198
(Similarity: 100.0%) (CD, 2003, US, Geffen Records)
```

Everything works fine here but notice how the `-` becomes `ΓÇÉ`. Then when I try to convert one of the tracks:

```
C:\Users\Michael>beet -v convert -d . stockholm
user configuration: C:\Users\Michael\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Michael\AppData\Roaming\beets
Sending event: pluginload
library database: C:\Users\Michael\Music\Library.blb
library directory: C:\Users\Michael\Music\Files
Sending event: library_opened
blinkΓÇÉ182 - blinkΓÇÉ182 - Stockholm Syndrome
Convert? (Y/n) y
Encoding C:\Users\Michael\Music\Files\blinkΓÇÉ182\blinkΓÇÉ182\05 Stockholm Syndrome.flac
Encoding C:\Users\Michael\Music\Files\blinkΓÇÉ182\blinkΓÇÉ182\05 Stockholm Syndrome.flac failed. Cleaning up...
Command ffmpeg -i C:\Users\Michael\Music\Files\blinkΓÇÉ182\blinkΓÇÉ182\05 Stockholm Syndrome.flac -y -vn -aq 2 C:\Users\Michael\blinkΓÇÉ182\blinkΓÇÉ182\05 Stock
holm Syndrome.mp3 exited with status 1
ffmpeg version 2.2.3 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jun 19 2014 20:36:23 with gcc 4.8.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --ena
ble-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libi
lbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enabl
e-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --
enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --en
able-zlib
  libavutil      52. 66.100 / 52. 66.100
  libavcodec     55. 52.102 / 55. 52.102
  libavformat    55. 33.100 / 55. 33.100
  libavdevice    55. 10.100 / 55. 10.100
  libavfilter     4.  2.100 /  4.  2.100
  libswscale      2.  5.102 /  2.  5.102
  libswresample   0. 18.100 /  0. 18.100
  libpostproc    52.  3.100 / 52.  3.100
C:\Users\Michael\Music\Files\blink├óΓé¼┬É182\blink├óΓé¼┬É182\05 Stockholm Syndrome.flac: No such file or directory
Conversion failed!

Sending event: cli_exit
```

Notice how the `-` is `ΓÇÉ` in the ffmpeg command but `├óΓé¼┬É` in the output. This makes me think it has something to do with character encoding and `subprocess.popen`.

P.S. I only modified the source to display the ffmpeg output. Here's the `git diff`:

```
diff --git a/beets/util/__init__.py b/beets/util/__init__.py
index 38cecd7..0f8285c 100644
--- a/beets/util/__init__.py
+++ b/beets/util/__init__.py
@@ -665,6 +665,7 @@ def command_output(cmd, shell=False):
         raise subprocess.CalledProcessError(
             returncode=proc.returncode,
             cmd=' '.join(cmd),
+            output=stderr
         )
     return stdout

diff --git a/beetsplug/convert.py b/beetsplug/convert.py
index 0b87fb7..73a4664 100644
--- a/beetsplug/convert.py
+++ b/beetsplug/convert.py
@@ -116,6 +116,7 @@ def encode(command, source, dest, pretend=False):
             exc.cmd.decode('utf8', 'ignore'),
             exc.returncode,
         ))
+        log.debug(u'{0}'.format(exc.output.decode('utf-8')))
         util.remove(dest)
         util.prune_dirs(os.path.dirname(dest))
         raise
```

**Comment by vaab** [comment]
Here's a workaround for python 2.7 on Windows to use ``CreateProcessW``. Comments welcome.

http://vaab.blog.kal.fr/2017/03/16/fixing-windows-python-2-7-unicode-issue-with-subprocesss-popen/

**Comment by Vesnyx** [comment]
@vaab I'm unfamiliar with how I would go about adding this fix to beets. 

Also @sampsyo I'm getting a slightly similar error with Python 3. This is the error output:
```
Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.5', 'console_scripts', 'beet')()
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 87, in func
    opts.func(lib, opts)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 52, in update
    alt.update(create=options.create)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 195, in update
    for item, dest in converter.as_completed():
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 324, in as_completed
    yield f.result()
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 247, in _convert
    self._encode(self.convert_cmd, item.path, dest)
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\convert.py", line 213, in encode
    encode_cmd.append(args[i].encode(util.arg_encoding()))
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\u2606' in position 30: character maps to <undefined>
```
