### ISSUE TITLE
beet move issues

### ISSUE THREAD

**Issue by sv2241** [beetbox/beets#1231]
When running 'beet -v move -a' command, I'm getting the following error after some minutes on a freshly indexed library:

```
user@host:~$ beet -v move -a
...
[the] "Aretha Franklin" -> "Aretha Franklin"
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: database_change
moving: /media/music/Album/Aretha Franklin/1998 Spanish Harlem
Sending event: database_change
[the] "Aretha Franklin" -> "Aretha Franklin"
Sending event: before_item_moved
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/beets/util/__init__.py", line 445, in move
    shutil.copyfile(path, dest)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/media/music/Album/Aretha Franklin/1998 Spanish Harlem/0101 Aretha Franklin - Spanish Harlem.mp3'

Error: No such file or directory while moving /media/music/Album/Aretha Franklin/1998 Spanish Harlem/0101 Aretha Franklin - Spanish Harlem.mp3 to /media/music/Album/Aretha Franklin/1998 Spanish Harlem/0101 Aretha Franklin - Spanish Harlem.mp3
user@host:~$
```

Before the command has been executed:

```
user@host:~$ sudo find /media/music/ -type d -empty
/media/music/Non-Album/Other
user@host:~$
```

After the command has been executed:

```
user@host:~$ sudo find /media/music/ -type d -empty
/media/music/Non-Album/Other
/media/music/Album/Aretha Franklin/1998 Spanish Harlem
user@host:~$
```

My config is here: http://pastebin.com/4iVfF3XY

**Comment by sampsyo** [comment]
It looks like beets is saying it's catalogued a file that no longer exists. Do you know why beets would be tracking that path? Where is the music actually located?

Can you go back to show how to reproduce this? That is, start with an empty library, import some music, and then run your command `beet -v move -a`. Otherwise it's hard to see exactly how your database got into this state.

**Comment by sampsyo** [comment]
This issue is timing out. Please reopen it if you have more details about the problem.
