### ISSUE TITLE
beet submit is broken

### ISSUE THREAD

**Issue by randybias** [beetbox/beets#1293]
With trunk...

> % beet submit
> % beet submit ''

all result in a stacktrace:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/Library/Python/2.7/site-packages/beets-1.3.11-py2.7.egg/beets/ui/__init__.py", line 953, in main
    _raw_main(args)
  File "/Library/Python/2.7/site-packages/beets-1.3.11-py2.7.egg/beets/ui/__init__.py", line 943, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Library/Python/2.7/site-packages/beets-1.3.11-py2.7.egg/beetsplug/chroma.py", line 185, in submit_cmd_func
    submit_items(self._log, apikey, lib.items(ui.decargs(args)))
  File "/Library/Python/2.7/site-packages/beets-1.3.11-py2.7.egg/beetsplug/chroma.py", line 243, in submit_items
    fp = fingerprint_item(item)
TypeError: fingerprint_item() takes at least 2 arguments (1 given)
```

**Comment by sampsyo** [comment]
Thanks for reporting! Should be fixed now.
