### ISSUE TITLE
UnicodeDecodeError when using beet update

### ISSUE THREAD

**Issue by willgrnr** [beetbox/beets#1298]
I get the following error when trying to use the beet update command.

```
C:\Users\100557855>beet update
M83 - Hurry Up, WeΓÇÖre Dreaming - Midnight City
  month: 10 -> 00
  day: 17 -> 00
  original_day: 17 -> 00
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "c:\users\100557855\src\beets\beets\ui\__init__.py", line 953, in main
    _raw_main(args)
  File "c:\users\100557855\src\beets\beets\ui\__init__.py", line 943, in _raw_ma
in
    subcommand.func(lib, suboptions, subargs)
  File "c:\users\100557855\src\beets\beets\ui\commands.py", line 1078, in update
_func
    update_items(lib, decargs(args), opts.album, opts.move, opts.pretend)
  File "c:\users\100557855\src\beets\beets\ui\commands.py", line 1041, in update
_items
    item.move()
  File "c:\users\100557855\src\beets\beets\library.py", line 672, in move
    album.move_art(copy)
  File "c:\users\100557855\src\beets\beets\library.py", line 887, in move_art
    new_art = util.unique_path(new_art)
  File "c:\users\100557855\src\beets\beets\util\__init__.py", line 491, in uniqu
e_path
    new_path = '%s.%i%s' % (base, num, ext)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal
 not in range(128)
```

Unfortunately I have no idea what music file (if any?) is causing the issue.

**Comment by sampsyo** [comment]
Thanks for the report; this was a recent `unicode_literals` regression. Should be fixed now.
