### ISSUE TITLE
beet mbsync → TypeError: item_before_write() got an unexpected keyword argument 'tags'

### ISSUE THREAD

**Issue by Freso** [beetbox/beets#1331]
```
freso@kotake> beet mbsync
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 953, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 943, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beetsplug/mbsync.py", line 69, in func
    self.singletons(lib, query, move, pretend, write, fmt)
  File "/usr/lib/python2.7/site-packages/beetsplug/mbsync.py", line 94, in singletons
    apply_item_changes(lib, item, move, pretend, write)
  File "/usr/lib/python2.7/site-packages/beetsplug/mbsync.py", line 36, in apply_item_changes
    item.try_write()
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 556, in try_write
    self.write(path, tags)
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 530, in write
    plugins.send('write', item=self, path=path, tags=item_tags)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 446, in send
    result = handler(**arguments)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 122, in wrapper
    return func(*args, **kwargs)
TypeError: item_before_write() got an unexpected keyword argument 'tags'
[1] freso@kotake> beet --version
beets version 1.3.11
plugins: lyrics, permissions, info, freedesktop, inline, lastgenre, check, mbsync, bpm, copyartifacts, fetchart, artistcountry, follow, types, web, alternatives, chroma, smartplaylist
freso@kotake> yaourt -Qi beets-git|grep Version
Version        : 1.3.10.r398.g457afdc-1
```

**Comment by brunal** [comment]
This is because a plugin listens to the `write` event but does not expect the arguments sent: `item`, `path`, `tags` (here it's the latter). This used not to break because `plugins.send()` was check the `argspec` of every listener. Because of the logging system update, all listeners are wrapped by a logging-level-setter function expecting the usual `*args, **kwargs`. → the `argspec` check did not work anymore and I removed it.
Solutions include:
- updating the plugin. Since I cannot find that function (`item_before_write`) under `beetsplug/` I think it's a plugin that's not included by default.
- restoring the `argspec` hack in the wrapper function. I'd rather avoid that

**Comment by Freso** [comment]
Closing in favour of geigerzaehler/beets-check#15.

**Comment by sampsyo** [comment]
Seems reasonable. I hope this doesn't come up too many more times—we've sort of shot ourselves in the foot by being so flexible with the arguments until now.
