### ISSUE TITLE
Mp3gain stops at any music that has character '

### ISSUE THREAD

**Issue by medyagh** [beetbox/beets#1783]
I was trying replaygain with command backend, mp3gain and it stops at any song that has the character '
for example:
Thriller 25 - Wanna Be Startin’ Somethin’

I was thinking may be the backened needs to escape that character ?

**Comment by jackwilsdon** [comment]
Do you get any errors? What's the output with `-vv`?

**Comment by sampsyo** [comment]
It would also be helpful to know your setup: OS, mp3gain version, beets version, etc.

FWIW, it's not the shell that's interfering, because we don't execute a shell—but mp3gain itself might have a bug with apostrophes and such in its arguments.

**Comment by medyagh** [comment]
I use ubuntu 15.10, and I use the
beet version
```
beets version 1.3.15
plugins: chroma, convert, discogs, duplicates, echonest, ftintitle, fuzzy, importfeeds, info, inline, lastgenre, lyrics, permissions, replaygain, web
```

**Comment by sampsyo** [comment]
How about @jackwilsdon's question above: what's the error? Is there anything in the verbose log?

**Comment by medyagh** [comment]
how can I get the verbose log?

**Comment by medyagh** [comment]
here is the log for one of them
```replaygain: analyzing Howard Shore - The Lord of the Rings: The Return of the King - The White Tree
replaygain: ReplayGain error: /usr/local/bin/mp3gain exited with status 1
replaygain: analyzing Howard Shore - The Lord of the Rings: The Return of the King - The Steward of Gondor
replaygain: ReplayGain error: /usr/local/bin/mp3gain exited with status 1
replaygain: analyzing Howard Shore - The Lord of the Rings: The Return of the King - Minas Morgul
replaygain: ReplayGain error: /usr/local/bin/mp3gain exited with status 1
replaygain: Skipping track Howard Shore - The Lord of the Rings: The Return of the King - The Ride of the Rohirrim
replaygain: analyzing Howard Shore - The Lord of the Rings: The Return of the King - Twilight and Shadow
replaygain: ReplayGain error: /usr/local/bin/mp3gain exited with status 1
replaygain: analyzing Howard Shore - The Lord of the Rings: The Return of the King - Cirith Ungol
replaygain: ReplayGain error: /usr/local/bin/mp3gain exited with status 1
replaygain: analyzing Howard Shore - The Lord of the Rings: The Return of the King - Andúril
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.15', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/replaygain.py", line 936, in func
    self.handle_track(item, write)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/replaygain.py", line 898, in handle_track
    track_gains = self.backend_instance.compute_track_gain([item])
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/replaygain.py", line 285, in compute_track_gain
    output = self.compute_gain(supported_items, False)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/replaygain.py", line 343, in compute_gain
    output = call(cmd)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/replaygain.py", line 51, in call
    return command_output(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/__init__.py", line 703, in command_output
    cmd=b' '.join(cmd),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 95: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
Thanks for getting the log!

Strangely, I can't seem to reproduce this here. I have two ideas:
* I notice from the traceback that you're running beets 1.3.15. Can you upgrade to the latest release and try again?
* If you still have the problem, can you please provide a sample file that triggers the crash so we can try to reproduce it?

**Comment by sampsyo** [comment]
As with the other bug, this one is timing out. Please reopen if you can reproduce this on the latest version.
