### ISSUE TITLE
stats -e fails when file is missing

### ISSUE THREAD

**Issue by lucaspanjer** [beetbox/beets#1806]
Stats exact fails when it can't find the file on disk. In this case the file had been removed but was still in the beets library. Beets should probably proceed and note the number of missing files in the statistics summary.

```
$ beet stats -e
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.16', 'console_scripts', 'beet')()
  File "/Library/Python/2.7/site-packages/beets/ui/__init__.py", line 1207, in main
    _raw_main(args)
  File "/Library/Python/2.7/site-packages/beets/ui/__init__.py", line 1197, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Library/Python/2.7/site-packages/beets/ui/commands.py", line 1267, in stats_func
    show_stats(lib, decargs(args), opts.exact)
  File "/Library/Python/2.7/site-packages/beets/ui/commands.py", line 1235, in show_stats
    total_size += os.path.getsize(item.path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: ...
```

**Comment by sampsyo** [comment]
Thanks for the report! I've now handled the error.
