### ISSUE TITLE
lyrics plugin: Crash on timeout

### ISSUE THREAD

**Issue by Profpatsch** [beetbox/beets#1854]
This also throws away the whole import process, so one has to restart all over. Not sure about data integrity.

It seems to come from the lyrics plugin doing insufficient error handling for its connections; when `genius-api.com` is down (which it is atm) it crashes.
Should plugins be able to crash the whole program?

```
Traceback (most recent call last):
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/bin/.beet-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/ui/__init__.py", line 1163, in main
    _raw_main(args)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/ui/__init__.py", line 1153, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/ui/commands.py", line 875, in import_func
    import_files(lib, paths, query)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/ui/commands.py", line 852, in import_files
    session.run()
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/importer.py", line 1353, in plugin_stage
    func(session, task)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beetsplug/lyrics.py", line 578, in imported
    False, self.config['force'])
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beetsplug/lyrics.py", line 590, in fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beetsplug/lyrics.py", line 617, in get_lyrics
    lyrics = backend.fetch(artist, title)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beetsplug/lyrics.py", line 285, in fetch
    lyric_data = self.get_lyrics(record_url)
  File "/nix/store/sbnd428fcf9d9h677s81ml2vb3glp5na-beets-1.3.15/lib/python2.7/site-packages/beetsplug/lyrics.py", line 254, in get_lyrics
    allow_redirects=True
  File "/nix/store/40b79y62x53mjbfza45ziph5n29dp7jh-python2.7-requests-2.8.1/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/nix/store/40b79y62x53mjbfza45ziph5n29dp7jh-python2.7-requests-2.8.1/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/nix/store/40b79y62x53mjbfza45ziph5n29dp7jh-python2.7-requests-2.8.1/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/nix/store/40b79y62x53mjbfza45ziph5n29dp7jh-python2.7-requests-2.8.1/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/nix/store/40b79y62x53mjbfza45ziph5n29dp7jh-python2.7-requests-2.8.1/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='genius-api.com', port=80): Max retries exceeded with url: /api/lyricsInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7979205450>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by sampsyo** [comment]
It looks like you're on 1.3.15. We fixed something similar in #1770; can you try the latest version?

Regarding the larger question or isolating plugin exceptions: yes, this is in the plans for the long-overdue plugin system refactoring (the ticket for which is around here somewhere).

**Comment by Profpatsch** [comment]
@sampsyo You are right, I am on 1.3.15. Will try the new version.

**Comment by sampsyo** [comment]
Also: thanks for pointing out that the Genius API thing has flaked out again. I've disabled the backend by default in source—I don't think we can rely on that service as a default feature anymore.

**Comment by Profpatsch** [comment]
Seems like it. The crash didn’t appear anymore after updating to 1.3.16.

**Comment by sampsyo** [comment]
Great!
