### ISSUE TITLE
Error loading plugin discogs

### ISSUE THREAD

**Issue by todd-is-not** [beetbox/beets#1867]
I installed the latest snapshot and plugins and get the following information when I open a terminal or call beets:

```
** error loading plugin discogs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 255, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/lib/python2.7/site-packages/beetsplug/discogs.py", line 28, in <module>
    from discogs_client import Release, Client
  File "/usr/lib/python2.7/site-packages/discogs_client/__init__.py", line 6, in <module>
    from discogs_client.client import Client
  File "/usr/lib/python2.7/site-packages/discogs_client/client.py", line 12, in <module>
    from discogs_client import models
  File "/usr/lib/python2.7/site-packages/discogs_client/models.py", line 4, in <module>
    from six import with_metaclass
ImportError: No module named six
```

**Comment by sampsyo** [comment]
Looks like your installation of the `discogs_client` library is incomplete. Perhaps try reinstalling it; or, if you still get this crash, please report the bug to that project.

**Comment by abeger** [comment]
`pip install -U discogs_client` cleared this up for me.
