### ISSUE TITLE
lastimport: AttributeError: 'CustomUser' object has no attribute 'ws_prefix'

### ISSUE THREAD

**Issue by eriwst** [beetbox/beets#1875]
Hi,

beet lastimport (beets 1.3.17 on OSX 10.11.03) crashes with:

```
user@us:~% beet lastimport
lastimport: Fetching last.fm library for @mylastfmusername
lastimport: Querying page #1...
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.17', 'console_scripts', 'beet')()
  File "/Library/Python/2.7/site-packages/beets/ui/__init__.py", line 1236, in main
    _raw_main(args)
  File "/Library/Python/2.7/site-packages/beets/ui/__init__.py", line 1226, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Library/Python/2.7/site-packages/beetsplug/lastimport.py", line 50, in func
    import_lastfm(lib, self._log)
  File "/Library/Python/2.7/site-packages/beetsplug/lastimport.py", line 134, in import_lastfm
    tracks, page_total = fetch_tracks(user, page_current + 1, per_page)
  File "/Library/Python/2.7/site-packages/beetsplug/lastimport.py", line 177, in fetch_tracks
    user_obj.get_top_tracks_by_page(limit=limit, page=page)
  File "/Library/Python/2.7/site-packages/beetsplug/lastimport.py", line 110, in get_top_tracks_by_page
    "getTopTracks", "track", pylast.Track, params, cacheable)
  File "/Library/Python/2.7/site-packages/beetsplug/lastimport.py", line 72, in _get_things
    self.ws_prefix + "." + method, cacheable, params)
AttributeError: 'CustomUser' object has no attribute 'ws_prefix'
```

Any ideas?

**Comment by sampsyo** [comment]
Hmm, strange -- this seems to work fine on my machine.

Can you please check the version of the pylast library you have? Here's what I have:

```
$ python2 -c 'import pylast ; print pylast.__version__'
1.5.1
```

And if it's out of date, can you try updating it and see if that fixes the problem?

**Comment by eriwst** [comment]
Sorry,

i was using pylast version 0.5.  Since I updated to version 1.5.1 everything works well.
