### ISSUE TITLE
beet crashes with UnicodeEncodeError

### ISSUE THREAD

**Issue by sneak** [beetbox/beets#1896]
New one, similar to #1895 but not the same

```
Candidate: Black Dice & Wolf Eyes - Chimes in Black Water, Volume 2
Success. Distance: 0.79
Traceback (most recent call last):
  File "/Users/jp/Library/Python/2.7/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/ui/__init__.py", line 1236, in main
    _raw_main(args)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/ui/__init__.py", line 1226, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/ui/commands.py", line 966, in import_func
    import_files(lib, paths, query)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/importer.py", line 321, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/util/pipeline.py", line 252, in run
    msg = self.coro.next()
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/importer.py", line 1203, in read_tasks
    for t in task_factory.tasks():
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/importer.py", line 1048, in tasks
    tasks = self._create(self.album(paths, dirs))
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/importer.py", line 1127, in album
    items = map(self.read_item, paths)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/importer.py", line 1177, in read_item
    return library.Item.from_path(path)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/library.py", line 505, in from_path
    i.read(path)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/library.py", line 562, in read
    value = getattr(mediafile, key)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/mediafile.py", line 1087, in __get__
    out = style.get(mediafile.mgfile)
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/mediafile.py", line 560, in get
    return _sc_decode(data)[self.index]
  File "/Users/jp/Library/Python/2.7/lib/python/site-packages/beets/mediafile.py", line 220, in _sc_decode
    soundcheck = soundcheck.decode('utf8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 67-69: ordinal not in range(128)
```

**Comment by sampsyo** [comment]
Thanks! I messed up the fix for the other problem (I typed `decode` instead of `encode`) and caused this. Should be fixed now.
