### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by moorepants** [beetbox/beets#1943]
### Problem

During an import I got a division by zero error.

Running this command in verbose (`-vv`) mode:

``` sh
$ beet import ~/Music/
```

Led to this problem:

```
/home/moorepants/Music/Jeff Buckley/Mystery White Boy (12 items)
Tagging:
    Jeff Buckley - Mystery White Boy
URL:
    http://musicbrainz.org/release/b68b23eb-6623-4a6c-a5dc-06e76e0947bd
(Similarity: 100.0%) (CD, 2000, US, Columbia)

/home/moorepants/Music/Jeff Buckley/Mystery White Boy (Live) (12 items)
Correcting tags from:
    Jeff Buckley - Mystery White Boy (Live)
To:
    Jeff Buckley - Mystery White Boy
URL:
    http://musicbrainz.org/release/fc5e4a55-c835-3c64-bc7c-63d35ec80ee4
(Similarity: 98.1%) (label, album) (CD, 2000, AU, Columbia)
 * I Woke Up In A Strange Place ->
   I Woke Up in a Strange Place
 * Hallelujah / I Know It's Over (Medley) ->
   Hallelujah / I Know It's Over (medley)
This album is already in the library!
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.8', 'console_scripts', 'beet')()
  File "/usr/share/beets/beets/ui/__init__.py", line 964, in main
    _raw_main(args)
  File "/usr/share/beets/beets/ui/__init__.py", line 954, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/share/beets/beets/ui/commands.py", line 883, in import_func
    import_files(lib, paths, query)
  File "/usr/share/beets/beets/ui/commands.py", line 855, in import_files
    session.run()
  File "/usr/share/beets/beets/importer.py", line 297, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/share/beets/beets/util/pipeline.py", line 299, in run
    out = self.coro.send(msg)
  File "/usr/share/beets/beets/util/pipeline.py", line 158, in coro
    task = func(*(args + (task,)))
  File "/usr/share/beets/beets/importer.py", line 1148, in user_query
    resolve_duplicates(session, task)
  File "/usr/share/beets/beets/importer.py", line 1160, in resolve_duplicates
    session.resolve_duplicate(task, found_duplicates)
  File "/usr/share/beets/beets/ui/commands.py", line 791, in resolve_duplicate
    not task.is_album,
  File "/usr/share/beets/beets/ui/commands.py", line 449, in summarize_items
    average_bitrate = sum([item.bitrate for item in items]) / len(items)
ZeroDivisionError: integer division or modulo by zero
```

Here's a link to the music files that trigger the bug (if relevant): 
### Setup
- OS: Ubuntu 15.10
- Python version: 2.7.10
- beets version: 1.3.8
- Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

``` yaml
directory: ~/Music
library: ~/Music/beets-library.db
import:
    write: yes
    move: yes
plugins: chroma fetchart lastgenre fromfilename duplicates
```

**Comment by sampsyo** [comment]
It looks like you're using beets 1.3.8, which is quite old. Could you please try the latest version?

**Comment by moorepants** [comment]
This is the version that comes with Ubuntu 15.10. I'm not that interested in installing the latest version, as it takes more work than simply "apt-get install beets". Do you all have a ppa?

**Comment by sampsyo** [comment]
No, there's no PPA I'm aware of.

**Comment by moorepants** [comment]
Here are errors I get when installing beets using pip.

```
(beets)moorepants@parvati:~$ pip install beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync]
Collecting beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync]
  Using cached beets-1.3.17.tar.gz
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in ./miniconda/envs/beets/lib/python2.7/site-packages (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Collecting mutagen>=1.27 (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Using cached mutagen-1.31.tar.gz
Collecting munkres (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Using cached munkres-1.0.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): unidecode in ./miniconda/envs/beets/lib/python2.7/site-packages (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Collecting musicbrainzngs>=0.4 (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading musicbrainzngs-0.6.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 1.8MB/s 
Requirement already satisfied (use --upgrade to upgrade): pyyaml in ./miniconda/envs/beets/lib/python2.7/site-packages (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Collecting jellyfish (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading jellyfish-0.5.3.tar.gz (131kB)
    100% |████████████████████████████████| 133kB 1.6MB/s 
Collecting pyacoustid (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading pyacoustid-1.1.0.tar.gz
Collecting discogs-client>=2.1.0 (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading discogs-client-2.2.1.tar.gz
Collecting pyechonest (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading pyechonest-9.0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in ./miniconda/envs/beets/lib/python2.7/site-packages (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Collecting rarfile (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading rarfile-2.7.tar.gz
Collecting pylast (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading pylast-1.5.1.tar.gz
Collecting dbus-python (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading dbus-python-1.2.4.tar.gz (612kB)
    100% |████████████████████████████████| 614kB 951kB/s 
Collecting python-mpd2 (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading python-mpd2-0.5.5.tar.bz2
Collecting pathlib (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 2.2MB/s 
Collecting pyxdg (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading pyxdg-0.25.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 2.5MB/s 
Requirement already satisfied (use --upgrade to upgrade): flask in ./miniconda/envs/beets/lib/python2.7/site-packages (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Requirement already satisfied (use --upgrade to upgrade): flask-cors in ./miniconda/envs/beets/lib/python2.7/site-packages (from beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Collecting audioread (from pyacoustid->beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading audioread-2.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in ./miniconda/envs/beets/lib/python2.7/site-packages (from discogs-client>=2.1.0->beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
Collecting oauthlib (from discogs-client>=2.1.0->beets[fetchart,chroma,discogs,echonest,lastgenre,mpdstats,web,import,thumbnails,metasync])
  Downloading oauthlib-1.0.3.tar.gz (109kB)
    100% |████████████████████████████████| 112kB 1.9MB/s 
Building wheels for collected packages: beets, mutagen, munkres, musicbrainzngs, jellyfish, pyacoustid, discogs-client, pyechonest, rarfile, pylast, dbus-python, python-mpd2, pathlib, pyxdg, audioread, oauthlib
  Running setup.py bdist_wheel for beets ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/b1/7b/5a/a82be71fdaaf8d79f3f369ba9c4f0bd2b9e978e7c3d523fdb7
  Running setup.py bdist_wheel for mutagen ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/52/de/01/86c9fc612017a4010465876a3f44bb192902a72686efc427fd
  Running setup.py bdist_wheel for munkres ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/fa/d4/87/8ea03d9af1f268b19d5e5e7c54049309836ba78d24f2050abe
  Running setup.py bdist_wheel for musicbrainzngs ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/d4/70/91/62b4a6eb5495adef0785f650b11600677c1a9287d86ff45ca9
  Running setup.py bdist_wheel for jellyfish ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/37/1e/ec/392e6c138d24b80f9bdada3a2f7dcbac582d38ed1cfd6203a0
  Running setup.py bdist_wheel for pyacoustid ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/53/46/02/0ac19995e1e72050a52b191c43b1c1fea067600ad7d1c819fe
  Running setup.py bdist_wheel for discogs-client ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/0f/b8/e0/d8ca73768a230ab5b4711a1e6622a31d05dc9c998a53a4d139
  Running setup.py bdist_wheel for pyechonest ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/b1/26/34/359c6b2c4c0c462e67ac43653fe94265cf4d821c59faef27c4
  Running setup.py bdist_wheel for rarfile ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/36/cb/dc/61c1e516db0d59307d205c9fe3666240b48136c7d3b775b7c4
  Running setup.py bdist_wheel for pylast ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/07/b7/c1/036697c3d43ffa1c350fc1bb6100f2c242ad74234bf978b559
  Running setup.py bdist_wheel for dbus-python ... error
  Complete output from command /home/moorepants/miniconda/envs/beets/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rrx02s/dbus-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpYyf4kepip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  creating /tmp/pip-build-rrx02s/dbus-python/build
  creating /tmp/pip-build-rrx02s/dbus-python/build/temp.linux-x86_64-2.7
  checking whether make supports nested variables... yes
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether UID '1000' is supported by ustar format... yes
  checking whether GID '1000' is supported by ustar format... yes
  checking how to create a ustar tar archive... gnutar
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for native Windows host... no
  checking how to print strings... printf
  checking for style of include used by make... GNU
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking dependency style of gcc... gcc3
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /bin/dd
  checking how to truncate binary pipes... /bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... no
  checking for inline... inline
  checking whether /home/moorepants/miniconda/envs/beets/bin/python version is >= 2.6... yes
  checking for /home/moorepants/miniconda/envs/beets/bin/python version... 2.7
  checking for /home/moorepants/miniconda/envs/beets/bin/python platform... linux2
  checking for /home/moorepants/miniconda/envs/beets/bin/python script directory... ${prefix}/lib/python2.7/site-packages
  checking for /home/moorepants/miniconda/envs/beets/bin/python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
  configure: Using $PYTHON-config: /home/moorepants/miniconda/envs/beets/bin/python-config
  checking for Python headers using /home/moorepants/miniconda/envs/beets/bin/python-config --includes... -I/home/moorepants/miniconda/envs/beets/include/python2.7 -I/home/moorepants/miniconda/envs/beets/include/python2.7
  checking whether those headers are sufficient... yes
  checking for Python library linker flags using /home/moorepants/miniconda/envs/beets/bin/python-config... -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
  checking for git... /usr/bin/git
  checking whether you want to build HTML docs... if possible
  checking whether you want to build API docs... if possible
  checking python module: docutils... no
  checking for dbus-run-session... /usr/bin/dbus-run-session
  checking whether  understands --generator... no
  checking whether  understands --date... no
  checking whether  understands --time... no
  checking whether  understands --exit-status=2... no
  checking whether  understands --no-raw... no
  checking whether  understands --no-file-insertion... no
  checking whether  understands --cloak-email-addresses... no
  checking whether  understands --input-encoding=UTF-8... no
  checking for pkg-config... /usr/bin/pkg-config
  checking pkg-config is at least version 0.9.0... yes
  checking for DBUS... no
  configure: error: Package requirements (dbus-1 >= 1.6) were not met:
  
  No package 'dbus-1' found
  
  Consider adjusting the PKG_CONFIG_PATH environment variable if you
  installed software in a non-standard prefix.
  
  Alternatively, you may set the environment variables DBUS_CFLAGS
  and DBUS_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-rrx02s/dbus-python/setup.py", line 106, in <module>
      'build_ext': BuildExt,
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-rrx02s/dbus-python/setup.py", line 62, in run
      cwd=builddir)
    File "/home/moorepants/miniconda/envs/beets/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-rrx02s/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/moorepants/miniconda/envs/beets/bin/python', '--prefix=/tmp/pip-build-rrx02s/dbus-python/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
  Running setup.py bdist_wheel for python-mpd2 ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/97/2a/11/40b3c20ebe6d3540cdec166a373f59a6b49cbdae15f026afce
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/84/4b/e9/2c35393d25f4a858caf5bafc2f822abb7171c52369a6010709
  Running setup.py bdist_wheel for pyxdg ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/fe/39/af/59b0559e392651cca4cf1cdf3d08375b95024d783610b934b2
  Running setup.py bdist_wheel for audioread ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/b7/4c/20/77f7c36f09493671dd11d4fd14dfed0cb869c6a8a92e418993
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/24/97/b6/b1f31b9c4b7710fe4e5a28e591349f68e43d6027aef320d056
Successfully built beets mutagen munkres musicbrainzngs jellyfish pyacoustid discogs-client pyechonest rarfile pylast python-mpd2 pathlib pyxdg audioread oauthlib
Failed to build dbus-python
Installing collected packages: mutagen, munkres, musicbrainzngs, jellyfish, audioread, pyacoustid, oauthlib, discogs-client, pyechonest, rarfile, pylast, dbus-python, python-mpd2, pathlib, pyxdg, beets
  Running setup.py install for dbus-python ... error
    Complete output from command /home/moorepants/miniconda/envs/beets/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rrx02s/dbus-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-srWfyu-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /tmp/pip-build-rrx02s/dbus-python/build
    creating /tmp/pip-build-rrx02s/dbus-python/build/temp.linux-x86_64-2.7
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether UID '1000' is supported by ustar format... yes
    checking whether GID '1000' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking whether /home/moorepants/miniconda/envs/beets/bin/python version is >= 2.6... yes
    checking for /home/moorepants/miniconda/envs/beets/bin/python version... 2.7
    checking for /home/moorepants/miniconda/envs/beets/bin/python platform... linux2
    checking for /home/moorepants/miniconda/envs/beets/bin/python script directory... ${prefix}/lib/python2.7/site-packages
    checking for /home/moorepants/miniconda/envs/beets/bin/python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
    configure: Using $PYTHON-config: /home/moorepants/miniconda/envs/beets/bin/python-config
    checking for Python headers using /home/moorepants/miniconda/envs/beets/bin/python-config --includes... -I/home/moorepants/miniconda/envs/beets/include/python2.7 -I/home/moorepants/miniconda/envs/beets/include/python2.7
    checking whether those headers are sufficient... yes
    checking for Python library linker flags using /home/moorepants/miniconda/envs/beets/bin/python-config... -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
    checking for git... /usr/bin/git
    checking whether you want to build HTML docs... if possible
    checking whether you want to build API docs... if possible
    checking python module: docutils... no
    checking for dbus-run-session... /usr/bin/dbus-run-session
    checking whether  understands --generator... no
    checking whether  understands --date... no
    checking whether  understands --time... no
    checking whether  understands --exit-status=2... no
    checking whether  understands --no-raw... no
    checking whether  understands --no-file-insertion... no
    checking whether  understands --cloak-email-addresses... no
    checking whether  understands --input-encoding=UTF-8... no
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for DBUS... no
    configure: error: Package requirements (dbus-1 >= 1.6) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rrx02s/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-rrx02s/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/home/moorepants/miniconda/envs/beets/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-rrx02s/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/moorepants/miniconda/envs/beets/bin/python', '--prefix=/tmp/pip-build-rrx02s/dbus-python/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/moorepants/miniconda/envs/beets/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rrx02s/dbus-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-srWfyu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-rrx02s/dbus-python/
```

**Comment by sampsyo** [comment]
Can you please try instilling without all the extras? It looks like one of them is pulling in dbus-python, and that's failing for some reason.

**Comment by moorepants** [comment]
Yes, the metasync extra is trying to install dbus-python and that fails. I removed the metasync extra and it installed.

**Comment by jackwilsdon** [comment]
Has the new version fixed it, @moorepants? Are you still getting the `ZeroDivisionError`?

**Comment by arcresu** [comment]
It looks to me that the underlying logic error has been fixed at some point because the division by `len(items)` is inside a guard `if items:`. If you're still having this issue with the latest version of beets feel free to reopen this issue.
