### ISSUE TITLE
Unreadable file when trying to import AIFF

### ISSUE THREAD

**Issue by marcwie** [beetbox/beets#1965]
I am having some trouble importing AIFF files created by audacity. Calling 
`beet imp filename.aiff` raises: `unreadable file: filename.aiff`. However, I checked and the file plays fine in VLC. I am on arch with beets installed via pacman. Its in version 1.3.17. Any help is highly appreciated :)

**Comment by jackwilsdon** [comment]
Could you possibly provide a link to the file?

**Comment by marcwie** [comment]
Hey, 
I put the file here:  https://www.dropbox.com/s/ru7swpwuboi5fks/Audio%20Track.aiff?dl=0
I just realized that if I only export a snippet of the content (thus create a smaller file), I can import it just fine. Might there be some issues with the filesize?

**Comment by marcwie** [comment]
Here is the output of `beet config`. My Version is 1.3.17.

directory: /media/media/music/library

import:
    move: yes
asciify_paths: yes
library: /media/media/music/library/musiclibrary.blb

plugins: discogs fetchart embedart bpd web smartplaylist fromfilename edit
bpd:
    volume: 100
    host: ''
    password: REDACTED
    port: 6600
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
fetchart:
    minwidth: 0
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    cautious: no
    google_engine: 001442825323518660753:hrh5ch1gjzm
    maxwidth: 0
    google_key: REDACTED
    auto: yes
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no
smartplaylist:
    auto: yes
    playlist_dir: .
    playlists: []
    relative_to:

**Comment by sampsyo** [comment]
Can you also please include the verbose output from a command that fails on this file?

**Comment by marcwie** [comment]
Sure. Here is the verbose output of `beet imp`:

user configuration: /home/marc/.config/beets/config.yaml
data directory: /home/marc/.config/beets
plugin paths: 
Sending event: pluginload
library database: /media/media/music/library/musiclibrary.blb
library directory: /media/media/music/library
Sending event: library_opened
Sending event: import_begin
header parsing failed: Not enough data to read
unreadable file: /home/marc/hotel_lauer/Audio Track.aiff
No files imported from /home/marc/hotel_lauer/Audio Track.aiff
Sending event: import
Sending event: cli_exit

Thanks!

**Comment by jackwilsdon** [comment]
I can reproduce the problem with the provided file.

Here is the output from importing verbosely:

```
user configuration: /Users/jack/.config/beets/config.yaml
data directory: /Users/jack/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 9, 3))
library database: /Users/jack/.config/beets/library.db
library directory: /Users/jack/Music/Music
Sending event: library_opened
Sending event: import_begin
header parsing failed: Not enough data to read
unreadable file: /Users/jack/Downloads/Audio Track.aiff
No files imported from /Users/jack/Downloads/Audio Track.aiff
Sending event: import
Sending event: cli_exit
```

The error is caused by Mutagen not getting enough data, it is thrown [here](https://github.com/dhamaniasad/mutagen/blob/1ecd913248704e071c7e581adaa25d7a1a3be8f3/mutagen/id3/__init__.py#L72). Not entirely sure why it isn't getting enough data though.

**Comment by sampsyo** [comment]
Cool; thanks! It sounds, therefore, like either (a) this file has a malformed header, and VLC is just willing to read it anyway, or (b) it may be a bug in Mutagen. By truncating the audio, you're probably rewriting the header, which makes it readable again.

Perhaps this should be reported to the Mutagen project instead—or you might prefer to just "give up" and rewrite a valid header for this one file.

**Comment by jackwilsdon** [comment]
Something interesting is that other tagging software seems to cope fine with the file (I tried [Kid3] and it worked fine). Could it be a bug with Mutagen?

[Kid3]: http://kid3.sourceforge.net

**Comment by sampsyo** [comment]
It could definitely be a way in which Mutagen is overly conservative, which might be considered a bug—the right thing to do is probably to get a traceback from doing a `mutagen.File('test.aiff')` to gather more information on exactly what's going wrong. That might indicate who to blame: the file or Mutagen.

**Comment by jackwilsdon** [comment]
Sadly the stack trace doesn't give us much to go off:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/_file.py", line 251, in File
    return Kind(filename)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/_file.py", line 42, in __init__
    self.load(filename, *args, **kwargs)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/aiff.py", line 351, in load
    raise error(e)
mutagen.aiff.error: Not enough data to read
```

**Comment by sampsyo** [comment]
Hmm; that is no good. Yet another case when I wish for Python 3's chained exceptions…

**Comment by jackwilsdon** [comment]
I managed to get a slightly better stack trace by removing the silly exception chaining done by Mutagen, but we're still not there:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/_file.py", line 251, in File
    return Kind(filename)
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/_file.py", line 42, in __init__
    self.load(filename, *args, **kwargs)
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/aiff.py", line 347, in load
    self.tags = _IFFID3(filename, **kwargs)
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/id3/__init__.py", line 188, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/_util.py", line 206, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/_tags.py", line 84, in __init__
    self.load(*args, **kwargs)
  File "/Users/jack/Downloads/venv/lib/python2.7/site-packages/mutagen/id3/__init__.py", line 277, in load
    raise error(e)
mutagen.id3._util.error: Not enough data to read
```

**Comment by jackwilsdon** [comment]
Well here is the most complete stack trace we're going to get, it certainly seems to be an issue with Mutagen retrieving the ID3 tags from the file:

```
  File "<stdin>", line 1, in <module>
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/_file.py", line 251, in File
    return Kind(filename)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/_file.py", line 42, in __init__
    self.load(filename, *args, **kwargs)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/aiff.py", line 347, in load
    self.tags = _IFFID3(filename, **kwargs)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/id3/__init__.py", line 188, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/_util.py", line 206, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/_tags.py", line 84, in __init__
    self.load(*args, **kwargs)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/id3/__init__.py", line 274, in load
    data = _fullread(fileobj, self.size - 10)
  File "/Users/jack/Documents/Development/Personal/beets/venv/lib/python2.7/site-packages/mutagen/id3/__init__.py", line 73, in _fullread
    raise EOFError("Not enough data to read")
EOFError: Not enough data to read
```

**Comment by sampsyo** [comment]
Huh, the AIFF has ID3 tags? I suppose that could be the problem—I'm guessing other tools mostly don't bother reading ID3 from AIFF, so that didn't matter to them.

**Comment by marcwie** [comment]
I figured that everything works as supposed, if I leave all tags empty when creating the file. So it might really be a problem with the ID3 tags. At least for me, this solves the issue. I don't know too much about mutagen. Do you think it makes sense to open a new issue there? Thanks for your help!

**Comment by jackwilsdon** [comment]
Yeah, opening an issue on mutagen sounds like a good idea; a second opinion never hurt anyone :smile:.

**Comment by sampsyo** [comment]
Yes, good idea! And referencing these trackbacks would probably help.
