### ISSUE TITLE
echonest: TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by MacLeodMike** [beetbox/beets#1997]
### Problem

I'm attempting to import an album, and beets is crashing. I've tried on both Ubuntu Trusty and Xenial. The trusty host is the host I've used for years with beets, and I have imported albums before and after this one successfully. The Xenial host is brand new, created in an attempt to see if it would make a difference.

The autotagger identifies the album correctly (100%) but fails to import with the echonest plugin enabled. If I disable the echonest plugin it will import properly.

```sh
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1236, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1226, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 966, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 321, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 302, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 184, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1374, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 452, in imported
    self.apply_metadata(item, song)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 426, in apply_metadata
    item[field] = int(v)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

My configuration (output of `beet config`) is:

```yaml
importfeeds:
    dir: /mnt/music
    relative_to:
    formats: echo
    absolute_path: yes
    m3u_name: imported.m3u

paths:
    default: '%asciify{Albums/%upper{%left{$albumartist,1}}/$albumartist/[%if{$year,$year,0000}] $album%aunique{}/$disc-$track - $title}'
    singleton: '%asciify{Singles/$artist - $title}'
    comp: '%asciify{Compilations/[%if{$year,$year,0000}] $album/$track - $title}'
    albumtype:soundtrack: '%asciify{Soundtracks/[%if{$year,$year,0000}] $album/$track - $title}'
acoustid:
    apikey: REDACTED
threaded: yes
scrub:
    auto: no
per_disc_numbering: yes
library: ~/.config/beets/library.blb
ignore: .AppleDouble ._* *~ .DS_Store
replaygain:
    backend: gstreamer
    overwrite: yes
    targetlevel: 89
    auto: yes
lastgenre:
    canonical: ~/.config/beets/genres-tree.yaml
    whitelist: ~/.config/beets/genres.txt
    source: album
    fallback: Unknown
    count: 1
    force: yes
    min_weight: 10
    auto: yes
    separator: ', '

plugins: fetchart embedart replaygain scrub the mbsync missing lastgenre ftintitle info discogs chroma importfeeds echonest
directory: /mnt/music/

import:
    copy: yes
    move: no
    write: yes
    delete: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    none_rec_fallback: skip
    timid: no
    languages: en
    log: ~/beets-import.log
echonest:
    apikey: REDACTED
    auto: yes
    convert: yes
    upload: yes
    truncate: yes
    energy: energy
    liveness: liveness
    tempo: bpm
    speechiness: speechiness
    acousticness: acousticness
    danceability: danceability
    valence: valence

match:
    preferred:
        countries: [US, GB|UK]
        media: [CD, Digital Media|File]
        original_year: yes
fetchart:
    minwidth: 0
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    cautious: no
    google_engine: 001442825323518660753:hrh5ch1gjzm
    maxwidth: 0
    google_key: REDACTED
    auto: yes
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    remove_art_file: no
    maxwidth: 0
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
missing:
    count: no
    total: no
chroma:
    auto: yes
the:
    a: yes
    patterns: []
    the: yes
    strip: no
    format: '{0}, {1}'
```

**Comment by sampsyo** [comment]
This does look like a bug, but alas, the Echo Nest API is about to shut down. See also #1920 and [the announcement](http://developer.echonest.com/). So, unfortunately, we are likely to remove this plugin altogether before we fix this. :cry:

**Comment by sampsyo** [comment]
Sadly, we've had to remove the Echo Nest plugin entirely after the API shutdown, so I'll need to close this bug. :cry:
