### ISSUE TITLE
Using beets in a bash script results in error

### ISSUE THREAD

**Issue by nomadturk** [beetbox/beets#2041]
### Problem

I was trying to get rid of around 1700 directories/subdirectories with only 1 or 2 mp3 files in it due to importing a lot of various artist albums in a bad way. I didn't go delete all && beet update way and wanted to use it in a bash script.

Turns out 1.3.18 has a bug for that matter. 

Since beets doesn't have a --quiet or --force parameter for beet remove command, I had to manually pass the stdin to beet when it was asked. 

Running the example command below

`echo 'y'|beet remove -d "/Depo/Beets/Anberlin/New Surrender"
`
results with error message:

```
/Depo/Beets/Anberlin/New Surrender/00 - Feel Good Drag.mp3 - Feel Good Drag
Really DELETE 1 file (y/n)? Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1250, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1240, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1230, in remove_func
    remove_items(lib, decargs(args), opts.album, opts.delete)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1220, in remove_items
    if not ui.input_yn(prompt, True):
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 375, in input_yn
    ('y', 'n'), require, prompt, u'Enter Y or N:'
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 339, in input_options
    resp = input_(prompt)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 207, in input_
    return resp.decode(_in_encoding(), 'ignore')
TypeError: decode() argument 1 must be string, not None
```

Same goes for other methods. When I wanted to pass Y to beets, none of them were accepted. Only after @DjSlash said he had success with the command that we were able to identify the problem. Turns out 1.3.17 doesn't have such problems and after a downgrade I managed to do what I wanted as well.

### Setup

* OS: Debian 8
* Python version: 2.7.9
* beets version:  1.3.18
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml

```

**Comment by nomadturk** [comment]
Headsup: https://github.com/beetbox/beets/issues/1997 Also mentions the same error. But I've tried running beets without any plugins and the result was the same.

**Comment by sampsyo** [comment]
Thanks for documenting the problem! This was indeed a regression in the previous version. I've committed a fix with tests.

**Comment by sampsyo** [comment]
For posterity, the bug was introduced in #1964.

Also, #1997 looks like a different error to me---maybe they just look similar enough because they both mention None?

**Comment by nomadturk** [comment]
My bad... #1997 indeed is different. I don't remember which one I was trying to link ^^

Thanks for the fix.

**Comment by petwri** [comment]
When will the fix for this be available?

**Comment by jrobeson** [comment]
it should be available now in 1.3.19

**Comment by petwri** [comment]
And is 1.3.19 available via pip?

**Comment by jrobeson** [comment]
should be
