### ISSUE TITLE
beatport: AttributeError: 'BeatportPlugin' object has no attribute 'client'

### ISSUE THREAD

**Issue by brianroach** [beetbox/beets#2075]
### Problem

After successfully authorizing with Beatport via OAuth & pasting returned string in terminal, I got the following error:

```
Traceback (most recent call last):
  File "/Users/anodigital/.pyenv/versions/2.7.10/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/__init__.py", line 1250, in main
    _raw_main(args)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/__init__.py", line 1240, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 1264, in lookup_candidates
    task.lookup_candidates()
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/importer.py", line 591, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/autotag/match.py", line 439, in tag_album
    search_album, va_likely)
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/autotag/hooks.py", line 582, in album_candidates
    out.extend(plugins.candidates(items, artist, album, va_likely))
  File "/Users/anodigital/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beets/plugins.py", line 355, in candidates
    out.extend(plugin.candidates(items, artist, album, va_likely))
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 344, in candidates
    return self._get_releases(query)
  File "/Users/anodigital/github/beets/beetsplug/beatport.py", line 396, in _get_releases
    for x in self.client.search(query).results]
AttributeError: 'BeatportPlugin' object has no attribute 'client'
```

### Setup

* OS: Mac OS X 10.11.5 (15F34)
* Python version: 2.7.10
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```
threaded: yes
art_filename: cover
library: /Users/anodigital/Desktop/music.blb
ignore: .AppleDouble ._* *~ .DS_Store

ui:
    color: yes
pluginpath: ~/github/beets/beetsplug

plugins: beatport
directory: /Users/anodigital/Desktop/Music

import:
    copy: no
    write: yes
    resume: yes
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
echonest:
    auto: yes
    upload: no
    convert: no
    truncate: yes
beatport:
    tokenfile: beatport_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
```

**Comment by jackwilsdon** [comment]
Looks like #2076 might actually fix this?
