### ISSUE TITLE
Problem when piping input to beets in a bash-script

### ISSUE THREAD

**Issue by petwri** [beetbox/beets#2081]
This thing used to work until I did an update from 1.3.17 to 1.3.18. Within a bash script, I use

`echo y | /usr/local/bin/beet -c /home/main/.beets/config.yaml rm path:"$DEL_PATH" `

in order to automatically delete music based on a few conditions. However, now i get this back from beet:

`Really remove 9 items from the library (y/n)? Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1250, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1240, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1230, in remove_func
    remove_items(lib, decargs(args), opts.album, opts.delete)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1220, in remove_items
    if not ui.input_yn(prompt, True):
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 375, in input_yn
    ('y', 'n'), require, prompt, u'Enter Y or N:'
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 339, in input_options
    resp = input_(prompt)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 207, in input_
    return resp.decode(_in_encoding(), 'ignore')
TypeError: decode() argument 1 must be string, not None`

Works fine without the `echo` part.

Ideas?

**Comment by sampsyo** [comment]
Hi! This is a regression we fixed recently in #2041. A release with this fix is coming very soon.
