### ISSUE TITLE
Discogs error: TypeError: data must be a byte string

### ISSUE THREAD

**Issue by Pelllicer** [beetbox/beets#2098]
### Problem

Error caused by Discogs plugin

Running this command in verbose (`-vv`) mode:

``` sh
$  beet -vv import "/home/jpd/discoduro/torrents/public/Desi"
```

Led to this problem:

```
user configuration: /home/jpd/.config/beets/config.yaml
data directory: /home/jpd/.config/beets
plugin paths: /home/jpd/discoduro/torrents/beets/whatlastgenre/plugin/beets/beetsplug
Sending event: pluginload
inline: adding album field wcdbitrate
library database: /home/jpd/discoduro/torrents/beets/beetslibrary.db
library directory: /home/jpd/discoduro/Musica/Albums
Sending event: library_opened
Sending event: import_begin
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.19', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 317, in run
    plugins.send('import_begin', session=self)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 457, in send
    result = handler(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/discogs.py", line 78, in setup
    token, secret = self.authenticate(c_key, c_secret)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/discogs.py", line 101, in authenticate
    _, _, url = auth_client.get_authorize_url()
  File "/usr/local/lib/python2.7/dist-packages/discogs_client/client.py", line 61, in get_authorize_url
    content, status_code = self._fetcher.fetch(self, 'POST', self._request_token_url, data=postdata, headers=params)
  File "/usr/local/lib/python2.7/dist-packages/discogs_client/fetchers.py", line 95, in fetch
    resp = request(method, uri, headers=headers, data=body)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 854, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 947, in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string
```
### Setup
- OS: Debian jessie
- Python version: Python 2.7.9
- beets version:  1.3.18
- Turning off plugins made problem go away (yes/no):  Yes, only including the Discogs plugin causes this.

My configuration (output of `beet config`) is:

``` yaml
directory: ~/discoduro/Musica/Albums
library: ~/discoduro/torrents/beets/beetslibrary.db
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: darkred
    text_highlight_minor: lightgray
    action_default: magenta
    action: teal
plugins: discogs edit embedart fetchart lastimport mpdstats mpdupdate inline duplicates
import:
  log: beetslog.txt
art_filename: folder
ignore: .AppleDouble ._* *~ .DS_Store
ignore_hidden: yes
embedart:
  ifempty: yes
lastfm:
  user: Pelllicer
pluginpath:
  ~/discoduro/torrents/beets/whatlastgenre/plugin/beets/beetsplug
wlg:
  auto: yes
  force: no
  count: 3
paths:
  default: "[$catalognum] $albumartist - $album ($year) [$wcdbitrate]/$track $title"
  singleton: Singles/$artist - $title
  comp: $album/$track $title
  albumtype:soundtrack: Soundtracks/$album/$track $title
album_fields:
  wcdbitrate: |
     total = 0
     for item in items:
       total += item.bitrate
     abr = total / len(items) / 1000
     if abr > 320:
       return 'FLAC'
     elif abr == 320:
       return '320'
     elif abr < 320 and abr >= 220:
       return 'V0'
     elif abr < 215 and abr >= 170 and abr != 192:
       return 'V2'
     elif abr == 192:
       return '192'
     elif abr < 170:
       return abr
```

_Notes_
- Updating discogs-client to the latest version didn't fix the issue.
- Updating pyopenssl to the latest version didn't fix the issue.
- The date and hour of the machine are right.
- The token file have never been created on `~/.config/beets/`.

Any thoughts about how to fix this one? Thank you in advance.

**Comment by sampsyo** [comment]
Hi! We've seen something like this come up before: http://comments.gmane.org/gmane.comp.audio.beets.user/708

Could you please also try upgrading requests (`pip install -U requests`)?

**Comment by Pelllicer** [comment]
I think that this could be due to a dependency issue. I ran:
```
pip install -U requests pyopenssl
```
And got some errors:
```
Downloading/unpacking requests from https://pypi.python.org/packages/99/b4/63d99ba8e189c47d906b43bae18af4396e336f2b1bfec86af31efe2d2cb8/requests-2.10.0-py2.py3-none-any.whl#md5=abf5a77de3e8a5973c738cca884502a0
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB): 506kB downloaded
Downloading/unpacking pyopenssl from https://pypi.python.org/packages/b1/4e/54c8995d2de887919272c2b711cd430277ec33e0f7bb88cb564244c102b6/pyOpenSSL-16.0.0-py2.py3-none-any.whl#md5=40b81d9372700b6bf97bff050a64bc31
  Downloading pyOpenSSL-16.0.0-py2.py3-none-any.whl (45kB): 45kB downloaded
Downloading/unpacking six>=1.5.2 from https://pypi.python.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8 (from pyopenssl)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking cryptography>=1.3 (from pyopenssl)
  Downloading cryptography-1.4.tar.gz (399kB): 399kB downloaded
  Running setup.py (path:/tmp/pip-build-atpvZ2/cryptography/setup.py) egg_info for package cryptography

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna>=2.0 (from cryptography>=1.3->pyopenssl)
  Downloading idna-2.1-py2.py3-none-any.whl (54kB): 54kB downloaded
Downloading/unpacking pyasn1>=0.1.8 (from cryptography>=1.3->pyopenssl)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Downloading/unpacking setuptools>=11.3 (from cryptography>=1.3->pyopenssl)
  Downloading setuptools-23.1.0-py2.py3-none-any.whl (435kB): 435kB downloaded
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3->pyopenssl)
Downloading/unpacking ipaddress (from cryptography>=1.3->pyopenssl)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.3->pyopenssl)
  Downloading cffi-1.7.0.tar.gz (400kB): 400kB downloaded
  Running setup.py (path:/tmp/pip-build-atpvZ2/cffi/setup.py) egg_info for package cffi

Downloading/unpacking pycparser from https://pypi.python.org/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935 (from cffi>=1.4.1->cryptography>=1.3->pyopenssl)
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/pip-build-atpvZ2/pycparser/setup.py) egg_info for package pycparser

    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: requests, pyopenssl, six, cryptography, idna, pyasn1, setuptools, ipaddress, cffi, pycparser
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: pyOpenSSL 0.14
    Not uninstalling pyOpenSSL at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: cryptography 0.6.1
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cryptography
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-atpvZ2/cryptography/setup.py", line 333, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
    ImportError: No module named setuptools_ext
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-atpvZ2/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bp0HyJ-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-atpvZ2/cryptography/setup.py", line 333, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load

    ['__name__'])

ImportError: No module named setuptools_ext

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-atpvZ2/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bp0HyJ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-atpvZ2/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

Despite of having cryptography installed:
```
pip show cryptography
---
Name: cryptography
Version: 0.6.1
Location: /usr/lib/python2.7/dist-packages
Requires: cffi, six
```
Some results in google point that cffi needs to be +1.0. But Debian states that is a system file that can't overwrite?

```
pip install -U cffi

Downloading/unpacking cffi from https://pypi.python.org/packages/83/3c/00b553fd05ae32f27b3637f705c413c4ce71290aa9b4c4764df694e906d9/cffi-1.7.0.tar.gz#md5=34122a545060cee58bab88feab57006d
  Downloading cffi-1.7.0.tar.gz (400kB): 400kB downloaded
  Running setup.py (path:/tmp/pip-build-Cp2Xmi/cffi/setup.py) egg_info for package cffi

Downloading/unpacking pycparser from https://pypi.python.org/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935 (from cffi)
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/pip-build-Cp2Xmi/pycparser/setup.py) egg_info for package pycparser

    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: cffi, pycparser
  Found existing installation: cffi 0.8.6
    Not uninstalling cffi at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cffi
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-2.7/_cffi_backend.so

  Found existing installation: pycparser 2.10
    Not uninstalling pycparser at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for pycparser
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    Build the lexing/parsing tables
Successfully installed cffi pycparser
Cleaning up...
```
But still show the previous version:
```
pip show cffi
---
Name: cffi
Version: 0.8.6
Location: /usr/lib/python2.7/dist-packages
Requires: pycparser
```

Still I'm not sure if this is the issue. I'm not experienced with these kinds of errors to be honest. By the way thank you for pointing me to the google groups, I didn't know about it. I will follow it too :) Thank you.

**Comment by sampsyo** [comment]
Oh dear, that looks like bad news -- Debian won't let you upgrade cffi? Perhaps you need to uninstall some Debian-provided package and reinstall via pip?

I'm perplexed. Sorry for the packaging/dependency hell!

**Comment by Pelllicer** [comment]
I finally fixed it. It was something as silly as upgrading these two via `easy_install`:
```easy_install --upgrade pip```
```easy_install --upgrade cryptography```
Now is working as intended. Thank you.

**Comment by sampsyo** [comment]
Woohoo! It's weird that `easy_install` did the trick, but I'll take it. :tada:

**Comment by jrobeson** [comment]
this means our dependency specs aren't high (or specific) enough.  

Upgrading packages using pip could break other packages installed on the distribution.  For example, say `required_debian_tool` only works with `cryptography-1.0` and the user upgrades to `cryptography-1.5` then `required_debian_tool` could easily break and bork their entire system.

Beets should have failed to install before we got to this point.

**Comment by jrobeson** [comment]
@Pelllicer:  so what `python-` prefixed packages (and their versions) did you have installed via apt?

**Comment by Pelllicer** [comment]
@jrobeson 

```
$ apt --installed list | grep python-
...
python/stable,now 2.7.9-1 amd64 [installed]
python-apt/stable,now 0.9.3.12 amd64 [installed]
python-apt-common/stable,now 0.9.3.12 all [installed,automatic]
python-cairo/stable,now 1.8.8-1+b2 amd64 [installed,automatic]
python-cffi/stable,now 0.8.6-1 amd64 [installed]
python-chardet/stable,now 2.3.0-1 all [installed,automatic]
python-colorama/stable,now 0.3.2-1 all [installed,automatic]
python-crypto/stable,now 2.6.1-5+b2 amd64 [installed,automatic]
python-cryptography/stable,now 0.6.1-1 amd64 [installed]
python-dbus/stable,now 1.2.0-2+b3 amd64 [installed,automatic]
python-dbus-dev/stable,now 1.2.0-2 all [installed,automatic]
python-debian/stable,now 0.1.27 all [installed,automatic]
python-debianbts/stable,now 1.12 all [installed,automatic]
python-defusedxml/stable,now 0.4.1-2 all [installed,automatic]
python-dev/stable,now 2.7.9-1 amd64 [installed]
python-distlib/stable,now 0.1.9-1 all [installed,automatic]
python-dnspython/stable,now 1.12.0-1 all [installed,automatic]
python-docutils/stable,now 0.12+dfsg-1 all [installed,automatic]
python-gobject-2/stable,now 2.28.6-12+b1 amd64 [installed]
python-gtk2/stable,now 2.24.0-4 amd64 [installed,automatic]
python-html5lib/stable,now 0.999-3 all [installed,automatic]
python-imaging/stable,stable,now 2.6.1-2+deb8u2 all [installed,automatic]
python-ldb/stable,now 2:1.1.17-2+deb8u1 amd64 [installed,upgradable to: 2:1.1.20-0+deb8u1]
python-lxml/stable,now 3.4.0-1 amd64 [installed,automatic]
python-minimal/stable,now 2.7.9-1 amd64 [installed]
python-mutagen/stable,now 1.25.1-1 all [installed]
python-ndg-httpsclient/stable,now 0.3.2-1 all [installed,automatic]
python-ntdb/stable,now 1.0-5 amd64 [installed,automatic]
python-numpy/stable,now 1:1.8.2-2 amd64 [installed,automatic]
python-openssl/stable,now 0.14-1 all [installed,automatic]
python-pexpect/stable,now 3.2-1 all [installed,automatic]
python-pil/stable,stable,now 2.6.1-2+deb8u2 amd64 [installed,automatic]
python-pip/stable,now 1.5.6-5 all [installed]
python-pkg-resources/stable,now 5.5.1-1 all [installed,automatic]
python-ply/stable,now 3.4-5 all [installed,automatic]
python-pyasn1/stable,now 0.1.7-1 all [installed,automatic]
python-pycparser/stable,now 2.10+dfsg-3 all [installed,automatic]
python-pygments/stable,stable,now 2.0.1+dfsg-1.1+deb8u1 all [installed,automatic]
python-pyinotify/stable,now 0.9.4-1 all [installed,automatic]
python-renderpm/stable,now 3.1.8-3+deb8u1 amd64 [installed,automatic]
python-reportbug/stable,now 6.6.3 all [installed]
python-reportlab/stable,now 3.1.8-3+deb8u1 all [installed,automatic]
python-reportlab-accel/stable,now 3.1.8-3+deb8u1 amd64 [installed,automatic]
python-requests/stable,now 2.4.3-6 all [installed]
python-roman/stable,now 2.0.0-1 all [installed,automatic]
python-samba/stable,now 2:4.1.17+dfsg-2+deb8u2 amd64 [installed,upgradable to: 2:4.2.10+dfsg-0+deb8u3]
python-setuptools/stable,now 5.5.1-1 all [installed,automatic]
python-six/stable,now 1.8.0-1 all [installed,automatic]
python-soappy/stable,now 0.12.22-1 all [installed,automatic]
python-support/stable,now 1.0.15 all [installed]
python-talloc/stable,now 2.1.1-2 amd64 [installed,upgradable to: 2.1.2-0+deb8u1]
python-tdb/stable,now 1.3.1-1 amd64 [installed,upgradable to: 1.3.6-0+deb8u1]
python-urllib3/stable,now 1.9.1-3 all [installed,automatic]
python-wheel/stable,now 0.24.0-1 all [installed,automatic]
python-wstools/stable,now 0.4.3-2 all [installed,automatic]
python2.7/stable,now 2.7.9-2 amd64 [installed]
python2.7-dev/stable,now 2.7.9-2 amd64 [installed,automatic]
python2.7-minimal/stable,now 2.7.9-2 amd64 [installed,automatic]
python3/stable,now 3.4.2-2 amd64 [installed,automatic]
python3-cffi/stable,now 0.8.6-1 amd64 [installed]
python3-minimal/stable,now 3.4.2-2 amd64 [installed,automatic]
python3-ply/stable,now 3.4-5 all [installed,automatic]
python3-pycparser/stable,now 2.10+dfsg-3 all [installed,automatic]
python3-uno/now 1:4.3.3-2+deb8u3 amd64 [installed,upgradable to: 1:4.3.3-2+deb8u5]
python3.4/stable,now 3.4.2-1 amd64 [installed,automatic]
python3.4-minimal/stable,now 3.4.2-1 amd64 [installed,automatic]
...
```
And the ones installed manually according to `apt-mark showmanual | grep python-`
```
python-apt
python-cffi
python-cryptography
python-dev
python-gobject-2
python-minimal
python-mutagen
python-pip
python-reportbug
python-requests
python-support
```
Probably Most of the manually installed ones could have been installed trying to fix the stated issue.

**Comment by arcresu** [comment]
Given that it's been a few years, the distros have more modern versions of the relevant python packages and we probably aren't likely to be affected by this specific dependency under-specification any longer (even if the underlying problem still exists). As such I think we can close this now.
