### ISSUE TITLE
AlbumInfo isn't always Orderable in py3

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2125]
I'm not really sure what we're sorting here, so I have no recommendations. Here have a traceback! :)

```sh
beet import /home/johnny/some/path/to/music/files
Traceback (most recent call last):
  File "/home/johnny/src/beets/beet", line 23, in <module>
    beets.ui.main()
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1288, in main
    _raw_main(args)
  File "/home/johnny/src/beets/beets/ui/__init__.py", line 1275, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/johnny/src/beets/beets/ui/commands.py", line 968, in import_func
    import_files(lib, paths, query)
  File "/home/johnny/src/beets/beets/ui/commands.py", line 945, in import_files
    session.run()
  File "/home/johnny/src/beets/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/johnny/.local/share/pyenv/versions/3.4.5/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/home/johnny/src/beets/beets/importer.py", line 1264, in lookup_candidates
    task.lookup_candidates()
  File "/home/johnny/src/beets/beets/importer.py", line 591, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/home/johnny/src/beets/beets/autotag/match.py", line 446, in tag_album
    candidates = sorted(candidates.values())
TypeError: unorderable types: AlbumInfo() < AlbumInfo()

```

**Comment by jrobeson** [comment]
I'd done a successful import (the very first one! yay!) on py3 right before this, so it's not a general problem.

**Comment by jrobeson** [comment]
I removed TrackInfo from the title because I"m not sure if it is affected, but it probably would be in a similiar situation.

**Comment by sampsyo** [comment]
Huh! The idea here is that we're sorted `AlbumMatch` and `TrackMatch` objects, which are `namedtuple`s defined in `beets.autotag.hooks`. The idea behind the `sorted(...)` call is to sort the tuples by their distance, which is their first field.

I think the problem here is that, when two matches have exactly the same distance, Python tries to sort them by their second field—which is the `AlbumInfo` or `TrackInfo` object. It doesn't really matter how these get ordered; on Python 2, it happens in some arbitrary order. On Python 3, it looks like it crashes. :disappointed:

I suppose the right solution is just to explicitly sort by distance?

**Comment by jrobeson** [comment]
like this? `sorted(candidates.values(), key=lambda match: (match.distance))` ?

**Comment by jrobeson** [comment]
so where are all the places other than that that we should do this ?

**Comment by sampsyo** [comment]
Yes, that looks good. The only other cases I can think of are elsewhere in the same file—there are a handful of occurrences of `sorted(candidates.values())`. Maybe it's worth introducing a helper function that just does one thing.
