### ISSUE TITLE
plugin dependencies not installed

### ISSUE THREAD

**Issue by davidak** [beetbox/beets#2136]
### Problem

i first installed beets with python3 pip, but uninstalled it again as i read it doesn't work yet. then installed it with python 2.7.
followed the getting started guide, imported some music and activated some plugins. but it seams the dependencies for the plugins are not installed using pip. and i don't see a documentation that i have to do that.

what is wrong here?
do i really have to install them manually?

```sh
unibook:~ davidak$ beet -vv web
user configuration: /Users/davidak/.config/beets/config.yaml
data directory: /Users/davidak/.config/beets
plugin paths:
** error loading plugin fetchart:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/fetchart.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lyrics:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lyrics.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lastgenre:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 26, in <module>
    import pylast
ImportError: No module named pylast

** error loading plugin web:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/web/__init__.py", line 23, in <module>
    import flask
ImportError: No module named flask

Sending event: pluginload
library database: /Users/davidak/Music/musiclibrary.blb
library directory: /Users/davidak/Music
Sending event: library_opened
error: unknown command 'web'
```

### Setup

* OS: OS X 10.9.5
* Python version: 2.7.9
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
nibook:~ davidak$ beet version
** error loading plugin fetchart:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/fetchart.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lyrics:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lyrics.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lastgenre:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 26, in <module>
    import pylast
ImportError: No module named pylast

** error loading plugin web:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/web/__init__.py", line 23, in <module>
    import flask
ImportError: No module named flask

beets version 1.3.18
no plugins loaded
unibook:~ davidak$ beet config
** error loading plugin fetchart:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/fetchart.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lyrics:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lyrics.py", line 25, in <module>
    import requests
ImportError: No module named requests

** error loading plugin lastgenre:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 26, in <module>
    import pylast
ImportError: No module named pylast

** error loading plugin web:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 253, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/web/__init__.py", line 23, in <module>
    import flask
ImportError: No module named flask

directory: ~/Music

import:
    move: yes
library: ~/Music/musiclibrary.blb

plugins: fetchart lyrics lastgenre web
```

**Comment by sampsyo** [comment]
The documentation for each plugin should describe its dependencies. And yes, you do need to install them manually with `pip`; otherwise, we'd install a bunch of extra dependencies for everyone that they don't need.

One slightly more convenient option is to use pip's "extras" feature. For example, `pip install beets[fetchart]` will also get the `fetchart`-specific dependencies.

**Comment by davidak** [comment]
@sampsyo great.

`pip install beets[fetchart]` works, but can i install dependencies for multiple plugins at once?

i tried:

```
unibook:~ davidak$ pip install beets[fetchart, lyrics, lastgenre, web, ipfs]
Invalid requirement: 'beets[fetchart,'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'[fetchar'"
```

**Comment by sampsyo** [comment]
Perhaps the documentation for pip and such could help? http://stackoverflow.com/questions/19096155/setuptools-and-pip-choice-of-minimal-and-complete-install for example suggests that you have it right, but you need to omit the spaces.

**Comment by davidak** [comment]
`pip install beets[fetchart,lyrics,lastgenre,web,ipfs]` works.

that should be documented on the [plugins page](http://beets.readthedocs.io/en/stable/plugins/index.html).

**Comment by sampsyo** [comment]
Yes, that would make sense! Could you please contribute the new documentation? It's really easy—you can just find the relevant `*.rst` document in the GitHub file browser and hit the "Edit" button.
