### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 15: invalid continuation byte

### ISSUE THREAD

**Issue by t3k4y** [beetbox/beets#2225]
Hello!
After installing beets i wanted to import (aka. let beets know) my existing music files.
Than, the following error occurs:

Running this command in verbose (`-vv`) mode:

```sh

--- ~ »  beet -vv import ~/Musik                                                                                 1 ↵
user configuration: /home/i/.config/beets/config.yaml
data directory: /home/i/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/i/.config/beets/library.db
library directory: /home/i/Musik
Sending event: library_opened
Sending event: import_begin
state file could not be read: [Errno 2] No such file or directory: u'/home/i/.config/beets/state.pickle'
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.19', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 251, in run
    msg = next(self.coro)
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1202, in read_tasks
    for t in task_factory.tasks():
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1038, in tasks
    for dirs, paths in self.paths():
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1090, in paths
    for dirs, paths in albums_in_dir(self.toppath):
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1480, in albums_in_dir
    logger=log):
  File "/usr/local/lib/python2.7/dist-packages/beets/util/__init__.py", line 190, in sorted_walk
    if (ignore_hidden and not hidden.is_hidden(cur)) or not ignore_hidden:
  File "/usr/local/lib/python2.7/dist-packages/beets/util/hidden.py", line 78, in is_hidden
    path = path.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 15: invalid continuation byte


```

### Setup

* OS: linuxmint
* Python version: 2.7
* beets version: 1.3.19
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml

directory: ~/Musik

import:
    copy: no

```

**Comment by sampsyo** [comment]
Hi! I believe we fixed this in #2168. The fix should be released quite soon.
