### ISSUE TITLE
sqlite error: "too many SQL variables"

### ISSUE THREAD

**Issue by RX14** [beetbox/beets#2230]
### Problem

Running a relatively simple query:

``` sh
$ beet -vv ls 'porter robinson' ^worlds
```

This happened:

```
user configuration: /home/rx14/.config/beets/config.yaml
data directory: /home/rx14/.config/beets
plugin paths:
Sending event: pluginload
library database: /media/media/Music/beets.db
library directory: /media/media/Music
Sending event: library_opened
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.19', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 1069, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 1064, in list_items
    for item in lib.items(query):
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 1295, in items
    return self._fetch(Item, query, sort or self.get_default_item_sort())
  File "/usr/lib/python2.7/site-packages/beets/library.py", line 1270, in _fetch
    model_cls, query, sort
  File "/usr/lib/python2.7/site-packages/beets/dbcore/db.py", line 838, in _fetch
    rows = tx.query(sql, subvals)
  File "/usr/lib/python2.7/site-packages/beets/dbcore/db.py", line 670, in query
    cursor = self.db._connection().execute(statement, subvals)
sqlite3.OperationalError: too many SQL variables
```

I'm not 100% sure but it seems to only happen when using a NOT query.
### Setup
- OS: Arch linux x86_64
- Python version: 2.7.12
- beets version: 1.3.19 (can hardly tell because you borked the version)
- Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

``` yaml
paths:
    default: $albumartist/%if{$original_year,$original_year }$album%aunique{}/%if{$track,$track }$artist - $album - $title
    singleton: $artist/%if{$original_year,$original_year }$artist - $title
    comp: Compilations/$album%aunique{}/%if{$track,$track }$artist - $title
smartplaylist:
    playlist_dir: /media/media/Music/Playlists/
    playlists: [{name: all.m3u, query: ''}]
    auto: yes
    relative_to:
library: /media/media/Music/beets.db
replaygain:
    backend: bs1770gain
    targetlevel: 89
    auto: yes
    overwrite: no
    chunk_at: 5000
    method: replaygain

plugins: lastgenre chroma fromfilename web duplicates replaygain smartplaylist scrub
directory: /media/media/Music
timid: yes
acoustid:
    apikey: REDACTED
scrub:
    auto: yes
lastgenre:
    count: 1
    source: album
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
chroma:
    auto: yes
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
```

**Comment by sampsyo** [comment]
That's odd! I can't reproduce this here. Maybe your system somehow has a strangely-compiled SQLite installed, with a different setting for this parameter? https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber

That seems unlikely for Arch. And to check, disabling all of your plugins didn't help?

**Comment by RX14** [comment]
@sampsyo I did put it in the issue but I commented out my plugins line in the yml and the query still failed.

**Comment by sampsyo** [comment]
Strange. Any other guesses? Since I can't reproduce here, I'm not sure how to proceed.

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem can be reproduced by other users.

**Comment by RX14** [comment]
This doesn't repro for me any more too, so this is fixed.
