### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 114: invalid continuation byte

### ISSUE THREAD

**Issue by KyleSanderson** [beetbox/beets#2282]
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.19', 'console_scripts', 'beet')()
  File "/usr/lib64/python2.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib64/python2.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib64/python2.7/site-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/usr/lib64/python2.7/site-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib64/python2.7/site-packages/beets/util/pipeline.py", line 251, in run
    msg = next(self.coro)
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 1202, in read_tasks
    for t in task_factory.tasks():
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 1038, in tasks
    for dirs, paths in self.paths():
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 1090, in paths
    for dirs, paths in albums_in_dir(self.toppath):
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 1480, in albums_in_dir
    logger=log):
  File "/usr/lib64/python2.7/site-packages/beets/util/__init__.py", line 205, in sorted_walk
    for res in sorted_walk(cur, ignore, ignore_hidden, logger):
  File "/usr/lib64/python2.7/site-packages/beets/util/__init__.py", line 205, in sorted_walk
    for res in sorted_walk(cur, ignore, ignore_hidden, logger):
  File "/usr/lib64/python2.7/site-packages/beets/util/__init__.py", line 205, in sorted_walk
    for res in sorted_walk(cur, ignore, ignore_hidden, logger):
  File "/usr/lib64/python2.7/site-packages/beets/util/__init__.py", line 205, in sorted_walk
    for res in sorted_walk(cur, ignore, ignore_hidden, logger):
  File "/usr/lib64/python2.7/site-packages/beets/util/__init__.py", line 205, in sorted_walk
    for res in sorted_walk(cur, ignore, ignore_hidden, logger):
  File "/usr/lib64/python2.7/site-packages/beets/util/__init__.py", line 190, in sorted_walk
    if (ignore_hidden and not hidden.is_hidden(cur)) or not ignore_hidden:
  File "/usr/lib64/python2.7/site-packages/beets/util/hidden.py", line 78, in is_hidden
    path = path.decode('utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 114: invalid continuation byte

**Comment by jrobeson** [comment]
this bug is already fixed, so now we're just waiting on the release.

**Comment by KyleSanderson** [comment]
@sampsyo Any update on tagging a new release?

**Comment by sampsyo** [comment]
Please see #2168.

I hope to take care of the new release tomorrow!
