### ISSUE TITLE
replaygain plugin errors

### ISSUE THREAD

**Issue by mfiano** [beetbox/beets#2285]
1.3.19. beet help replaygain shows:
```
Traceback (most recent call last):
  File "/usr/sbin/beet", line 9, in <module>
    load_entry_point('beets==1.3.14', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1126, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1005, in _setup
    plugins = _load_plugins(config)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 991, in _load_plugins
    plugins.send("pluginload")
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 457, in send
    for handler in event_handlers()[event]:
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 440, in event_handlers
    for plugin in find_plugins():
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 288, in find_plugins
    _instances[cls] = cls()
  File "/usr/lib/python2.7/site-packages/beetsplug/replaygain.py", line 791, in __init__
    self.config, self._log
  File "/usr/lib/python2.7/site-packages/beetsplug/replaygain.py", line 394, in __init__
    self._rg.set_property("forced", True)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

**Comment by sampsyo** [comment]
Hmm; that's odd. This arises from a missing GStreamer plugin, but we should be catching it before the crash. Could you give this a try on the latest source and see whether it still happens?

**Comment by arcresu** [comment]
It's been some time now and we haven't heard from you. Without more detailed information it's really hard for the community to help you with this issue. If you'd still like help with this, feel free to reopen this issue or open a new one, but make sure you [include as much relevant information](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html) as possible and describe how the problem can be reproduced by other users.
