### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'prepare_request'

### ISSUE THREAD

**Issue by EnduringGuerila** [beetbox/beets#2289]
### Problem

(Describe your problem, feature request, or discussion topic here. If you're reporting a bug, please fill out this and the "Setup" section below. Otherwise, you can delete them.)

When I try to use Fetchart, I get this error. 

Running this command in verbose (`-vv`) mode:

```
beet -vv import /raid5/Torrent/TestFlac/
user configuration: /home/enduring/.config/beets/config.yaml
data directory: /home/enduring/.config/beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: /home/enduring/.config/beets/library.db
library directory: /raid5/Torrent/NewFlacOrg
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /raid5/Torrent/TestFlac/2012 - Away From The World
Tagging Dave Matthews Band - Away From The World
No album ID found.
Search terms: Dave Matthews Band - Away From The World
Album might be VA: False
Sending event: albuminfo_received
Candidate: Dave Matthews Band - Away From the World
Success. Distance: 0.00
Sending event: albuminfo_received
Candidate: Dave Matthews Band - Away From the World
Success. Distance: 0.03
Sending event: albuminfo_received
Candidate: Dave Matthews Band - Away From the World
Success. Distance: 0.00
Sending event: albuminfo_received
Candidate: Dave Matthews Band - Away From the World
Success. Distance: 0.08
Sending event: albuminfo_received
Candidate: Dave Matthews Band - Away from the World
Success. Distance: 0.10
Evaluating 5 candidates.

/raid5/Torrent/TestFlac/2012 - Away From The World (11 items)
Sending event: before_choose_candidate
Correcting tags from:
    Dave Matthews Band - Away From The World
To:
    Dave Matthews Band - Away From the World
URL:
    http://musicbrainz.org/release/0e9a9e01-be55-45f5-b579-9735187c04f7
(Similarity: 100.0%) (CD, 2012, XW, RCA)
Sending event: import_task_choice
found duplicates: [1]
default action for duplicates: a
This album is already in the library!
Old: 11 items, FLAC, 911kbps, 53:56, 353.5 MiB
New: 11 items, FLAC, 911kbps, 53:56, 353.5 MiB
[S]kip new, Keep both, Remove old? R
Sending event: import_task_apply
Replacing item 16: /raid5/Torrent/TestFlac/2012 - Away From The World/10 - Snow Outside.flac
Sending event: database_change
Sending event: item_removed
Replacing item 19: /raid5/Torrent/TestFlac/2012 - Away From The World/07 - Belly Full.flac
Sending event: database_change
Sending event: item_removed
Replacing item 17: /raid5/Torrent/TestFlac/2012 - Away From The World/06 - The Riff.flac
Sending event: database_change
Sending event: item_removed
Replacing item 18: /raid5/Torrent/TestFlac/2012 - Away From The World/11 - Drunken Soldier.flac
Sending event: database_change
Sending event: item_removed
Replacing item 20: /raid5/Torrent/TestFlac/2012 - Away From The World/09 - Rooftop.flac
Sending event: database_change
Sending event: item_removed
Replacing item 21: /raid5/Torrent/TestFlac/2012 - Away From The World/02 - Belly Belly Nice.flac
Sending event: database_change
Sending event: item_removed
Replacing item 22: /raid5/Torrent/TestFlac/2012 - Away From The World/03 - Mercy.flac
Sending event: database_change
Sending event: item_removed
Replacing item 12: /raid5/Torrent/TestFlac/2012 - Away From The World/05 - Sweet.flac
Sending event: database_change
Sending event: item_removed
Replacing item 13: /raid5/Torrent/TestFlac/2012 - Away From The World/08 - If Only.flac
Sending event: database_change
Sending event: item_removed
Replacing item 15: /raid5/Torrent/TestFlac/2012 - Away From The World/01 - Broken Things.flac
Sending event: database_change
Sending event: item_removed
Replacing item 14: /raid5/Torrent/TestFlac/2012 - Away From The World/04 - Gaucho.flac
Sending event: database_change
Sending event: database_change
Sending event: item_removed
11 of 11 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1480233412.71, flexible attributes [] from album 2 for /raid5/Torrent/TestFlac/2012 - Away From The World
Reimported item added 1480233412.71 from item 16 for /raid5/Torrent/TestFlac/2012 - Away From The World/10 - Snow Outside.flac
Reimported item flexible attributes [u'data_source'] from item 16 for /raid5/Torrent/TestFlac/2012 - Away From The World/10 - Snow Outside.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 19 for /raid5/Torrent/TestFlac/2012 - Away From The World/07 - Belly Full.flac
Reimported item flexible attributes [u'data_source'] from item 19 for /raid5/Torrent/TestFlac/2012 - Away From The World/07 - Belly Full.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 17 for /raid5/Torrent/TestFlac/2012 - Away From The World/06 - The Riff.flac
Reimported item flexible attributes [u'data_source'] from item 17 for /raid5/Torrent/TestFlac/2012 - Away From The World/06 - The Riff.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 18 for /raid5/Torrent/TestFlac/2012 - Away From The World/11 - Drunken Soldier.flac
Reimported item flexible attributes [u'data_source'] from item 18 for /raid5/Torrent/TestFlac/2012 - Away From The World/11 - Drunken Soldier.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 20 for /raid5/Torrent/TestFlac/2012 - Away From The World/09 - Rooftop.flac
Reimported item flexible attributes [u'data_source'] from item 20 for /raid5/Torrent/TestFlac/2012 - Away From The World/09 - Rooftop.flac
Sending event: database_change
Reimported item added 1480233412.72 from item 21 for /raid5/Torrent/TestFlac/2012 - Away From The World/02 - Belly Belly Nice.flac
Reimported item flexible attributes [u'data_source'] from item 21 for /raid5/Torrent/TestFlac/2012 - Away From The World/02 - Belly Belly Nice.flac
Sending event: database_change
Reimported item added 1480233412.72 from item 22 for /raid5/Torrent/TestFlac/2012 - Away From The World/03 - Mercy.flac
Reimported item flexible attributes [u'data_source'] from item 22 for /raid5/Torrent/TestFlac/2012 - Away From The World/03 - Mercy.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 12 for /raid5/Torrent/TestFlac/2012 - Away From The World/05 - Sweet.flac
Reimported item flexible attributes [u'data_source'] from item 12 for /raid5/Torrent/TestFlac/2012 - Away From The World/05 - Sweet.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 13 for /raid5/Torrent/TestFlac/2012 - Away From The World/08 - If Only.flac
Reimported item flexible attributes [u'data_source'] from item 13 for /raid5/Torrent/TestFlac/2012 - Away From The World/08 - If Only.flac
Sending event: database_change
Reimported item added 1480233412.71 from item 15 for /raid5/Torrent/TestFlac/2012 - Away From The World/01 - Broken Things.flac
Reimported item flexible attributes [u'data_source'] from item 15 for /raid5/Torrent/TestFlac/2012 - Away From The World/01 - Broken Things.flac
Sending event: database_change
Reimported item added 1480233412.72 from item 14 for /raid5/Torrent/TestFlac/2012 - Away From The World/04 - Gaucho.flac
Reimported item flexible attributes [u'data_source'] from item 14 for /raid5/Torrent/TestFlac/2012 - Away From The World/04 - Gaucho.flac
Sending event: database_change
lastgenre: added last.fm album genre (album): Alternative Rock
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Snow Outside
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Belly Full
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - The Riff
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Drunken Soldier
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Rooftop
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Belly Belly Nice
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Mercy
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Sweet
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - If Only
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Broken Things
Sending event: database_change
lyrics: got lyrics from backend: LyricsWiki
lyrics: fetched lyrics: Dave Matthews Band - Away From the World - Gaucho
Sending event: database_change
fetchart: trying source filesystem for album Dave Matthews Band - Away From the World
fetchart: trying source coverart for album Dave Matthews Band - Away From the World
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.1', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 969, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 946, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1395, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 794, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 865, in art_for_album
    source.fetch_image(candidate, extra)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 233, in fetch_image
    message=u'downloading image')) as resp:
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 191, in request
    return _logged_get(self._log, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 176, in _logged_get
    prepped = s.prepare_request(req)
AttributeError: 'Session' object has no attribute 'prepare_request'
```

Led to this problem:
```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.1', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 969, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 946, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1395, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 794, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 865, in art_for_album
    source.fetch_image(candidate, extra)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 233, in fetch_image
    message=u'downloading image')) as resp:
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 191, in request
    return _logged_get(self._log, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/fetchart.py", line 176, in _logged_get
    prepped = s.prepare_request(req)
AttributeError: 'Session' object has no attribute 'prepare_request'

```

### Setup

* OS: Mint
* Python version: latest
* beets version: 1.4.1
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
directory: /raid5/Torrent/NewFlacOrg

import:
    write: yes

    move: no
    copy: yes
    delete: no
    resume: ask

threaded: yes

ui:
    color: yes

paths:
    default: $albumartist - $album ($year) [$format]/$track - $title


replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''





plugins: [
    lyrics,
    fetchart,
    #embedart,
    lastgenre,
    #scrub,
    #mbsync,
    #mpdupdate,
    #mpdstats,
    #missing,
    #duplicates
]

lyrics:
    auto: yes

fetchart:
    auto: yes

#embedart:
#    auto: yes
#    ifempty: yes
#    maxwidth: 300

lastgenre:
    auto: yes
    count: 3
    separator: '; '
```

**Comment by sampsyo** [comment]
It looks like your Requests module is outdated. Can you try `pip install -U requests`?

**Comment by EnduringGuerila** [comment]
I just installed it yesterday so I am not sure why it was out of date. That seems to have fixed the problem. Quick question, how do I also make beets move the .log file (that contains the cd rip information) to the new folder?

**Comment by jrobeson** [comment]
@sampsyo : so what's our minimum version of requests? We should add that to setup.py, and likely add a version check to fetchart.

**Comment by sampsyo** [comment]
OK, great!

@jrobeson Disturbingly, I actually don't know exactly which version we're assuming—but you're right, we should sort that out. Let's start with 2.0.0 and see how that goes. And adding a version check to fetchart would be a great idea!

**Comment by jrobeson** [comment]
@EnduringGuerila : which version of requests is in your distribution?

**Comment by avijasu01** [comment]
[hadoop@ip-10-21-0-158 ~]$ pip show requests
Name: requests
Version: 1.2.3
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Copyright 2013 Kenneth Reitz
Location: /usr/lib/python2.7/dist-packages
Requires:

**Comment by georgechalhoub** [comment]
`pip install -U requests` did the trick for me
