### ISSUE TITLE
discogs: IndexError: list index out of range

### ISSUE THREAD

**Issue by Smyds** [beetbox/beets#2302]
### Problem

I'm trying to import this album :
https://www.discogs.com/Para-One-Ciel-Ether-Con-Citoyen-Crazy/master/690105

while doing a `beet import Unsorted/New\ Stuff` :

```
/data/Music/Unsorted/New Stuff/Para One - 2003 - Paraone - Iris - Le Sept - Flynt - Lyricson (Maxi) [CD - FLAC] (6 items)
Finding tags for album "Paraone - Iris - Le sept - Flynt - Lyricson - Paraone - Iris - Le Sept - Flynt - Lyricson".
Candidates:
1. The Kenny Clarke - Francy Boland Big Band - Paris Jazz Concert: TNP - Oct. 29th, 1969, Part 2 (35.9%) (tracks, artist, album, ...) (CD, 2002, DE, LaserLight Digital)
2. A - Z Consolidated - A - Z Consolidated (33.8%) (tracks, album, artist)
3. Μίκης Θεοδωράκης - Βασίλης Τσιτσάνης - Σταμάτης Κόκοτας - Θεοδωράκης - Τσιτσάνης - Κόκοτας (29.3%) (tracks, missing tracks, album, ...) (12" Vinyl, 1985, GR, Μίνως Μάτσας & Υιός Α.Ε.)
4. Pirkko Mannola - Brita Koivunen - Vieno Kekkonen - Pirkko - Brita - Vieno (20.2%) (missing tracks, tracks, artist, ...) (CD, 1989, FI, Finnlevy)
5. _ - _ (7.7%) (missing tracks, tracks, album, ...)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? I
Enter release ID: 690105
Traceback (most recent call last):
  File "/home/cesar/.local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1250, in main
    _raw_main(args)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1240, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 967, in import_func
    import_files(lib, paths, query)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 944, in import_files
    session.run()
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 160, in coro
    task = func(*(args + (task,)))
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/importer.py", line 1285, in user_query
    task.choose_match(session)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/importer.py", line 779, in choose_match
    choice = session.choose_match(self)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 755, in choose_match
    task.items, search_ids=search_id.split()
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/autotag/match.py", line 407, in tag_album
    search_cands.extend(hooks.albums_for_id(search_id))
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/autotag/hooks.py", line 541, in albums_for_id
    plugin_albums = plugins.album_for_id(album_id)
  File "/home/cesar/.local/lib/python2.7/site-packages/beets/plugins.py", line 373, in album_for_id
    res = plugin.album_for_id(album_id)
  File "/home/cesar/.local/lib/python2.7/site-packages/beetsplug/discogs.py", line 188, in album_for_id
    return self.get_album_info(result)
  File "/home/cesar/.local/lib/python2.7/site-packages/beetsplug/discogs.py", line 225, in get_album_info
    result.data['formats'][0].get('descriptions', [])) or None
IndexError: list index out of range
```

### Setup

```
$ uname -a
Linux debian 4.7.0-1-amd64 #1 SMP Debian 4.7.6-1 (2016-10-07) x86_64 GNU/Linux
```
```
$ beet version
beets version 1.4.1
Python version 2.7.12+
plugins: discogs, lastgenre
```
```
$ beet config
directory: /data/Music/beets

import:
    link: yes
    write: no
    log: /data/Music/.beets_import.log
library: /data/Music/beetslibrary.blb

plugins: discogs lastgenre
lastgenre:
    count: 1
    source: album
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    whitelist: yes
    separator: ', '
    fallback:
    canonical: no
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
```

**Comment by Smyds** [comment]
It works fine if I use one of the actual release instead of the "master". Maybe that's what I was supposed to do. Still it probably shouldn't crash.

**Comment by jrobeson** [comment]
that's interesting because there haven't been any changes in something obviously related since 1.4.1 was release.  You are using 1.4.1 release (vs 1.4.1 in master)

**Comment by Smyds** [comment]
I mean release and master on discogs :

https://www.discogs.com/Para-One-Ciel-Ether-Con-Citoyen-Crazy/master/690105
https://www.discogs.com/Para-One-Ciel-Ether-Con-Citoyen-Crazy/release/1261580

**Comment by sampsyo** [comment]
Thanks for reporting! It looks like we need to relax an assumption about what the Discogs API returns.

**Comment by diego-plan9** [comment]
> It works fine if I use one of the actual release instead of the "master". Maybe that's what I was supposed to do. Still it probably shouldn't crash.

Actually, on your scenario, when you specify the ID manually (at `Enter release ID: 690105`) the plugin does not retrieve the *master* release of the Para One album - it retrieves the discogs *release* with that ID, which turns out to be https://www.discogs.com/release/690105. The discogs plugin at beets makes queries only to the discogs release API, which I believe it is by design (as a "master release", on discogs terminology, is basically a mechanism for grouping releases together as far as I can see - making sense not to use master releases at all).

> Thanks for reporting! It looks like we need to relax an assumption about what the Discogs API returns.

Absolutely - luckily (?) enough, the Red Hot Chili Peppers release seems to be missing the `format` information, which the plugin is not handling gracefully at all. `DiscogsPlugin.get_album_info()` seems to be making some assumptions about other fields as well that might be prone to causing similar crashes - perhaps it would be worth to try to revise those too?

**Comment by sampsyo** [comment]
Yes, good point—it would make sense to program "defensively" here, since it's clearly not obvious which fields are guaranteed to exist and which might be missing. For example, the `country` field is treated as optional:

```py
country = result.data.get('country')
```

Perhaps we should do that sort of thing elsewhere too.
