### ISSUE TITLE
Incorrect handling of file read errors in the scrub plugin

### ISSUE THREAD

**Issue by lukash** [beetbox/beets#2351]
### Problem

Updating my whole library:

```sh
$ beet import -L
```

Led to this problem:

```
error reading FILE1: 'FILE1'
error reading FILE2: 'FILE2'
scrub: could not open file to scrub: 'FILE2'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/beet", line 11, in <module>
    load_entry_point('beets==1.4.2', 'console_scripts', 'beet')()
  File "/usr/lib64/python2.7/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib64/python2.7/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib64/python2.7/site-packages/beets/ui/commands.py", line 969, in import_func
    import_files(lib, paths, query)
  File "/usr/lib64/python2.7/site-packages/beets/ui/commands.py", line 946, in import_files
    session.run()
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib64/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib64/python2.7/site-packages/beets/util/pipeline.py", line 358, in run
    self.coro.send(msg)
  File "/usr/lib64/python2.7/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 1418, in manipulate_files
    session=session,
  File "/usr/lib64/python2.7/site-packages/beets/importer.py", line 688, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "/usr/lib64/python2.7/site-packages/beets/plugins.py", line 452, in send
    result = handler(**arguments)
  File "/usr/lib64/python2.7/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/beetsplug/scrub.py", line 149, in import_task_files
    self._scrub_item(item)
  File "/usr/lib64/python2.7/site-packages/beetsplug/scrub.py", line 125, in _scrub_item
    art = mf.art
UnboundLocalError: local variable 'mf' referenced before assignment
```

I've checked the files, FILE1 has mp3 header missing and FILE2 seems to be damaged completely, according to mpv. This got me alarmed, but I suppose it's highly improbable it was caused by beets.

The traceback is clear regarding that `mf` variable. It would also be nice if it logged the cause of the error, instead of twice the filename (that seems a common problem with exceptions, they just contain the filename as a description and not the actual cause).

Since this error interrupted the import process, I don't know how to finish where it left off :( Is calling `scrub` manually enough?

### Setup

* OS: Gentoo Linux
* Python version: 2.7
* beets version: 1.4.2

**Comment by sampsyo** [comment]
Oh dear; thanks for reporting! I've just pushed two new commits that:

* Give more informative error messages for unreadable files.
* Avoids this crash (the plugin will just keep on trucking after logging the error).

Yeah, running `beet scrub` should be enough to scrub everything.

**Comment by lukash** [comment]
No worries, thanks for a quick fix :)
