### ISSUE TITLE
thumbnails: Python 3 compatibility

### ISSUE THREAD

**Issue by PierreRust** [beetbox/beets#2372]
### Problem

When using the thumbnail plugin with python 3 I get the following error.

Running this command in verbose (`-vv`) mode:

```sh
$beet -vv thumbnails genre:Classical
```

Led to this problem:

```
(.env_beets) pierre@pierre-System-Product-Name:~$ beet -vv thumbnails genre:Classical
user configuration: /home/pierre/.config/beets/config.yaml
data directory: /home/pierre/.config/beets
plugin paths: 
Sending event: pluginload
artresizer: method is (2, (6, 8, 9))
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
library database: /home/pierre/.config/beets/music-collection.db
library directory: /home/pierre/DataDrive/MusicTri
Sending event: library_opened
thumbnails: using IM to write metadata
thumbnails: using GIO to compute URIs
thumbnails: generating thumbnail for Johann Sebastian Bach - Bach 2000: The Complete Bach Edition, Volume 2: Sacred Cantatas: BWV 48-52, 54-69, 69A, 70-99 Classical - 1999 - /home/pierre/DataDrive/MusicTri/Classical/Bach, Johann Sebastian/Bach 2000_ The Complete Bach Edition, Volume 2_ Sacred Cantatas_ BWV 48-52, 54-69, 69A, 70-99 - 1999 - Johann Sebastian Bach
Traceback (most recent call last):
  File "/home/pierre/.env_beets/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.2', 'console_scripts', 'beet')()
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 78, in process_query
    self.process_album(album)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 132, in process_album
    wrote &= self.make_cover_thumbnail(album, 256, LARGE_DIR)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 144, in make_cover_thumbnail
    target = os.path.join(target_dir, self.thumbnail_file_name(album.path))
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/thumbnails.py", line 166, in thumbnail_file_name
    hash = md5(uri.encode('utf-8')).hexdigest()
AttributeError: 'bytes' object has no attribute 'encode'
```

### Setup

* OS: linux mint rebecca
* Python version: 3.5.2
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): yes, the problem only happens when activating the thumbnail plugin

**Comment by PierreRust** [comment]
I can try to fix this bug, but I'll need some history first : this plugin use the gio lib and fall back on pathlib if the gio lib is not available.

* does anybody remember why we use the gio lib ? 
* pathlib is included in python since 3.4 : which python do we want to support ? 
* is there already some policy defined for dealing the path in python3 ? I assume this kind of issue has already been dealt with when migrating beets to python 3

**Comment by jrobeson** [comment]
I am not sure why we use GIO either. I was thinking about chopping it rather than fixing it.  Python 3.4 will be our base python version for *nix, because current Debian stable still has it.  We should be able to completely rely on pathlib in this case (i think).

 Beets is currently use bytestring paths nearly everywhere, but we have a helper called `util.py3_path` for cases where methods only take `str` style paths on Python 3. 

We're still considering going with string paths everywhere with `surrogateescape`, but we haven't yet decided. I wanted to punt that decision until the full py3 switchover.

**Comment by sampsyo** [comment]
Thanks for the report, @PierreRust! And thanks for the summary too, @jrobeson—it looks like this needs a `py3_path`.

For what it's worth, I also don't understand, from reading the code, why GIO is used there. It looks like the pathlib version of URI computation works fine, and I don't see any reason to use GIO instead. Maybe we should just rip it out, unless @brunal would like to weigh in.

**Comment by jrobeson** [comment]
I wasn't planning on pushing the issue until we went all py3, because then we'd end up with two different pathlibs. The one that we currently depend on is an unmaintained fork. I just didn't wanna force potentially different behavior until we'd just use the normal pathlib.

**Comment by sampsyo** [comment]
For such a simple use case—turning a path into a file URL—it seems a little silly that we even need `pathlib` at all. Something like this would seem to work fine: http://stackoverflow.com/a/14298190/39182

**Comment by jrobeson** [comment]
the following comments aren't so sure about that.

**Comment by sampsyo** [comment]
Hmm, yeah, looks like something's wrong on Windows. Anyway, seems like a very narrow use case for pathlib—we're not using much of its functionality here.

**Comment by jrobeson** [comment]
but it's not like it'll cost us anything, since we get it for free on py 3.4.

**Comment by sampsyo** [comment]
Right, no need to drop in Python 3 land. I'm just saying that it might not be too dangerous to just use the unmaintained backport on Python 2.

**Comment by jrobeson** [comment]
I guess I'm ok with it, until we might go full string paths anyways. I just remembered that pathlib is all about string paths, so it won't be a true win for us until then.
