### ISSUE TITLE
UnicodeEncodeError: character maps to <undefined>

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2374]
### Problem

Beets crashes when trying to match to an artist with Japanese characters in their name. I think this is causing it, or a Python 3 / Python 2 mismatch (see Setup section). `Candidate: \u4e2d\u6751\u6b63\u4eba - Sonic the Hedgehog 1&2 Soundtrack`. I include a dummied-out FLAC file that has the same metadata but no music data, which reliably crashes beets in the same way. The genre tag of the file is also questionable (my programs read it as ????) but it doesn't look like beets cares about that.

Running this command in verbose

 (`-vv`) mode:

```sh
C:\Users\rollingstar>beet -vv import E:\Music\use\5
user configuration: C:\Users\rollingstar\AppData\Roaming\beets\config.yaml
data directory: C:\Users\rollingstar\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: e:\songs\beetslibrary.bib
library directory: e:\songs
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: E:\Music\use\5
Tagging Masato Nakamura - Sonic The Hedgehog 1&2 Soundtrack
No album ID found.
Search terms: Masato Nakamura - Sonic The Hedgehog 1&2 Soundtrack
Album might be VA: False
Sending event: albuminfo_received
Candidate: \u4e2d\u6751\u6b63\u4eba - Sonic the Hedgehog 1&2 Soundtrack
Success. Distance: 0.92
Sending event: albuminfo_received
Candidate: \u4e2d\u6751\u3068\u3057\u307e\u308b - Maruto
Success. Distance: 0.87
Sending event: albuminfo_received
Candidate: \u7af9\u539f\u88d5\u5b50, \u7532\u7530\u96c5\u4eba - Marvel VS. Capcom - Clash of the Super Heroes Original Soundtrack
Success. Distance: 0.95
Sending event: albuminfo_received
Candidate: Keith Rowe & \u4e2d\u6751\u3068\u3057\u307e\u308b - [untitled]
Success. Distance: 0.86
Sending event: albuminfo_received
Candidate: \u5409\u7530\u30a2\u30df & \u4e2d\u6751\u3068\u3057\u307e\u308b - Soba to Bara
Success. Distance: 0.82
Evaluating 5 candidates.

E:\Music\use\5 (1 items)
Sending event: before_choose_candidate
Finding tags for album "Masato Nakamura - Sonic The Hedgehog 1&2 Soundtrack".
Candidates:
Traceback (most recent call last):
  File "C:\Users\rollingstar\AppData\Local\Programs\Python\Python35-32\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.4.2', 'console_scripts', 'beet')()
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\__init__.py", line 1209, in main
    _raw_main(args)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\commands.py", line 969, in import_func
    import_files(lib, paths, query)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\commands.py", line 946, in import_files
    session.run()
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\importer.py", line 320, in run
    pl.run_parallel(QUEUE_SIZE)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\util\pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\util\pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\util\pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\importer.py", line 1285, in user_query
    task.choose_match(session)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\importer.py", line 779, in choose_match
    choice = session.choose_match(self)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\commands.py", line 738, in choose_match
    itemcount=len(task.items), extra_choices=extra_choices
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\commands.py", line 603, in choose_candidate
    print_(u' '.join(line))
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\beets\ui\__init__.py", line 143, in print_
    sys.stdout.write(txt)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\rollingstar\appdata\local\programs\python\python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3-6: character maps to <undefined>
```

Here's a link to the music files that trigger the bug (if relevant): 

[01 STH1 Green Hill Zone ~ Mega Drive version ~ (2).zip](https://github.com/beetbox/beets/files/691391/01.STH1.Green.Hill.Zone.Mega.Drive.version.2.zip)

### Setup

* OS: Windows 10 x64
* Python version: 3.5.2 / 2.7.10
* beets version: 
* Turning off plugins made problem go away (yes/no): no

```beet version
beets version 1.4.2
Python version 3.5.2
no plugins loaded
```

My Windows `PATH` setup is a bit of a mess, so it looks like beets is loading Python 3 instead of Python 2. However, there is talk of making beets Python 3 compliant, so even if I messed up with loading Python 3, it's still a bug in the grand scheme of things.

My configuration (output of `beet config`) is:

```yaml
library: e:\songs\beetslibrary.bib

import:
    copy: no
    move: no
    write: no
directory: e:\songs\
per_disc_numbering: yes
```

**Comment by jrobeson** [comment]
Beets mostly works with python 3, but has some trouble on Windows. Python 3.6 includes a major feature that will help in this case.  Can you try Python 3.6?

**Comment by sampsyo** [comment]
Yeah, this is a tricky one. As a little bit of background, Python (in most versions, actually) trusts the system's settings with respect to which encoding to use for input and output. That means, unfortunately, that the system's configuration can make Python unable to print certain strings! In Python 3, there's actually no (clean) way around this—programs just have to crash if they try to print a Unicode string that can't be represented in the system's preferred output encoding.

So, one way you can get around this for now is to tell your system to use a different encoding. Can you try running this command in the terminal before running beets?

```
chcp 65001
```

That sets the terminal to use UTF-8 for the current session (I think).

@jrobeson also mentioned that Python 3.6 changes the policy on this: Python just ignores your system's setting and uses UTF-8. That makes life easier for everyone.

**Comment by jrobeson** [comment]
@sampsyo: If we're serious about supporting 3.5, then we should be telling people to use https://github.com/Drekin/win-unicode-console,  as changing the code page isn't enough.

**Comment by sampsyo** [comment]
Indeed. I think just enforcing 3.6 on Windows is probably easier—shall we add that to the documentation?

**Comment by jrobeson** [comment]
I was hoping to have a few more successful test cases. Like @RollingStar here :)

**Comment by sampsyo** [comment]
Yep! No pressure, @RollingStar, but if things work for you on 3.6, that will be great news for us. :smiley:

**Comment by RollingStar** [comment]
Confirmed working on 

beets version 1.4.3
Python version 3.6.0
plugins: copyartifactspy3, fetchart, inline, the

The command line doesn't display the artist's Japanese name correctly, but I think that's a Windows issue. This happens even after changing the code page.

Leaving this open if you want to use it to discuss mandating 3.6 on Windows.

**Comment by sampsyo** [comment]
Thank you, @RollingStar! I think that's all we need for now.

**Comment by Vesnyx** [comment]
Something new that came up:

# Problem
```
Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.5', 'console_scripts', 'beet')()
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 87, in func
    opts.func(lib, opts)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 52, in update
    alt.update(create=options.create)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 195, in update
    for item, dest in converter.as_completed():
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 324, in as_completed
    yield f.result()
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36-32\beetsplug\alternatives.py", line 247, in _convert
    self._encode(self.convert_cmd, item.path, dest)
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\convert.py", line 213, in encode
    encode_cmd.append(args[i].encode(util.arg_encoding()))
  File "c:\users\REDACTED\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\u2606' in position 30: character maps to <undefined>
```

# Setup
OS: Windows 10 FCU 2017
Python 3.6.3
beets: 1.4.5
plugins: alternatives, convert, copyartifacts, customfields, embedart, info, inline

# Temporary(?) Solution
I was able to fix this by editing [line 213 in convert.py](https://github.com/beetbox/beets/blob/master/beetsplug/convert.py#L213) like so

```
        if six.PY2:
            encode_cmd.append(args[i])
        else:
            encode_cmd.append(args[i])
            #encode_cmd.append(args[i].encode(util.arg_encoding()))
```

# Additional Research
This is slightly different than the original problem posted in this thread in that python was calling codesheet 1252, which is the default Windows code page. I was running into the issue when using Command Prompt, Windows Powershell, and cmder. I tried setting chcp 65001, which set the sheet, but still generated the same error. 
I’m assuming that the util.arg_encoding function wasn’t properly picking up the codesheet I was using, resulting in this error. I could run ‘ß’.encode(‘utf-8’) in my python console and it would output a proper byte code without issue.
