### ISSUE TITLE
Python 3 compatibility : mpdupdate plugin 

### ISSUE THREAD

**Issue by PierreRust** [beetbox/beets#2381]
### Problem

When using the mpdupdate plugion wth python 3

```sh
$ beet -vv (... paste here ...)
```

I get this error 

```
Traceback (most recent call last):
  File "/home/pierre/.env_beets/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.2', 'console_scripts', 'beet')()
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/ui/__init__.py", line 1198, in _raw_main
    plugins.send('cli_exit', lib=lib)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/plugins.py", line 452, in send
    result = handler(**arguments)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/mpdupdate.py", line 92, in update
    config['mpd']['password'].as_str(),
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/mpdupdate.py", line 108, in update_mpd
    resp = s.readline()
  File "/home/pierre/.env_beets/lib/python3.5/site-packages/beetsplug/mpdupdate.py", line 53, in readline
    self.buf += data
TypeError: Can't convert 'bytes' object to str implicitly

```

**Comment by PierreRust** [comment]
This time it's not even a problem with path, should be pretty easy to fix !

**Comment by sampsyo** [comment]
Thanks for pointing this out! Looks like we didn't have any tests for this plugin. I'm working on writing a test now.

**Comment by sampsyo** [comment]
Well, the tests turned out to be too tricky to mock, but I did manual testing and fixed this. Can you give this a try to make sure the problem is gone?

Thanks again for the report! :sparkles:

**Comment by PierreRust** [comment]
You're so fast I did not had the time to setup a dev environment for beets, I was thinking to do that this evening, I'll test it with current head.

**Comment by PierreRust** [comment]
OK, made a quick test after a `pip install git+git://github.com/beetbox/beets.git` : works great, the error is gone and mpd updated successfully !

Thanks !

**Comment by sampsyo** [comment]
Woohoo! Thanks for checking.
