### ISSUE TITLE
Beets is crashing due to ascii encoding issues

### ISSUE THREAD

**Issue by fschoell** [beetbox/beets#2393]
### Problem

beets is crashing due to some ascii encoding issues when it should display the musicbrainz search result

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import System\ of\ a\ Down\ -\ Hypnotize/
```

Led to this problem:

```
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/user/.config/beets/library.db
library directory: /home/user/Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /some/folder/System of a Down - Hypnotize
Tagging System of a Down - Hypnotize
No album ID found.
Search terms: System of a Down - Hypnotize
Album might be VA: False
Sending event: albuminfo_received
Candidate: System of a Down - Hypnotize
Success. Distance: 0.01
Sending event: albuminfo_received
Candidate: System of a Down - Hypnotize
Success. Distance: 0.00
Sending event: albuminfo_received
Candidate: System of a Down - Hypnotize
Success. Distance: 0.01
Sending event: albuminfo_received
Candidate: System of a Down - Hypnotize
Success. Distance: 0.01
Sending event: albuminfo_received
Candidate: System of a Down - Hypnotize
Success. Distance: 0.01
Sending event: albuminfo_received
Candidate: System Of A Down - Hypnotize
Success. Distance: 0.04
Sending event: albuminfo_received
Candidate: System Of A Down - Hypnotize
Success. Distance: 0.04
Sending event: albuminfo_received
Candidate: System Of A Down - Hypnotize
Success. Distance: 0.04
Sending event: albuminfo_received
Candidate: System Of A Down - Hypnotize
Success. Distance: 0.04
Sending event: albuminfo_received
Candidate: System Of A Down - Hypnotize
Success. Distance: 0.04
Evaluating 10 candidates.

/some/folder/System of a Down - Hypnotize (12 items)
Sending event: before_choose_candidate
Tagging:
    System of a Down - Hypnotize
URL:
    https://musicbrainz.org/release/8a4034a9-7834-3b7e-a6f0-d0791e3731fb
(Similarity: 100.0%) (Vinyl, 2005, US)
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 930, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 907, in import_files
    session.run()
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 319, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 1282, in user_query
    task.choose_match(session)
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 777, in choose_match
    choice = session.choose_match(self)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 698, in choose_match
    itemcount=len(task.items), choices=choices
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 601, in choose_candidate
    show_change(cur_artist, cur_album, match)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 365, in show_change
    print_(u'%s%s -> %s' % (lhs, ' ' * pad, rhs))
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 143, in print_
    sys.stdout.write(txt)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 61: ordinal not in range(128)
```

### Setup

* OS: Arch Linux
* Python version: 3.6.0 
* beets version: 1.4.3
* plugins: embedart fetchart lastgenre convert

**Comment by greenisagoodcolor** [comment]
Hello! I have a similar bug issue:

/home/msm/untagged music/flac_clk/Ambient/Rod Modell, Michael Mantra - 1998-2007/Rod Modell - 2007 - Plays Michael Mantra (2 items)
Tagging:
    Rod Modell - Plays Michael Mantra
URL:
    https://musicbrainz.org/release/9463c2d6-5361-43a8-9e93-01a49009f5b0
(Similarity: 100.0%) (CD, 2007, IT, Silentes)

/home/msm/untagged music/flac_clk/Ambient/Thomas Koner 1990-1996/Thomas Koner - 1990 - Nunatak Gongamur (11 items)
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 930, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 907, in import_files
    session.run()
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 319, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 1282, in user_query
    task.choose_match(session)
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 777, in choose_match
    choice = session.choose_match(self)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 698, in choose_match
    itemcount=len(task.items), choices=choices
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 601, in choose_candidate
    show_change(cur_artist, cur_album, match)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 263, in show_change
    print_(u"Tagging:\n    {0.artist} - {0.album}".format(match.info))
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 143, in print_
    sys.stdout.write(txt)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 21: ordinal not in range(128)

**Comment by jrobeson** [comment]
what's the output of the `locale` command?

**Comment by fschoell** [comment]
Gave me an error message, fixed my locales and now the error is gone =)

**Comment by sampsyo** [comment]
It looks like both of these are instances of The Fundamental Problem With Python 3: the user's locale configuration can make it impossible to print some strings to stdout.

@jrobeson already knows all this, but as a little background, the problem is that `sys.stdout` on Python 3 is a Unicode stream, so you're supposed to print Unicode strings (i.e., `str` objects) to it. That makes perfect sense, but Python 3 is also set up to automatically encode those `str` objects to bytes to send them to the OS—and that encoding can crash depending on the locale Python has gleaned from the OS settings.

On Python 2, we used to be able to bypass this either by avoiding unencodeable characters (i.e., using the `replace` policy) or by ignoring the encoding Python guessed and just using UTF-8 (we have an encoding override setting). On Python 3, we no longer have that option because we can't send encoded bytes directly to the OS. We're stuck waiting for Python itself to change its defaults.

Anyway, @greenisagoodcolor, seeing that locale information would still be useful.

**Comment by sampsyo** [comment]
One other thought for @jrobeson: should we consider using `sys.stdout.buffer.write` on Python 3 to restore the old behavior (i.e., `_out_encoding` is respected and bad characters are replaced)?

**Comment by jrobeson** [comment]
We certainly could do that, but I was hoping to see how prevalent the non utf8 situation was on *nix first, and in what cases we'd run into them.

**Comment by sampsyo** [comment]
Good point. It looks like both of these cases are the most predictable scenario: broken locale settings that no one noticed were broken until this crash happened.

**Comment by jrobeson** [comment]
yeah, but broken how?  I'm very suprised to see non utf8 setups on arch. I"d like to know the reasoning behind them.

**Comment by greenisagoodcolor** [comment]
@jrobeson output of locale command:

[msm@msm-x220 ~]$ locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

**Comment by jrobeson** [comment]
@greenisagoodcolor : you probably shouldn't be using the C locale on a modern system.  Any python program that uses the click cli library (not us yet), will warn you to switch to something else.

Any character that isn't in the ASCII set will either be missing or be replaced with a question mark or some other similiar character.

Don't close the issue though, as we still want to have some sort of mitigation measure in place though.

**Comment by sampsyo** [comment]
@greenisagoodcolor Could you perhaps give https://github.com/beetbox/beets/pull/2398 a try? You should be able to check out the `stdout-bytes` branch from git. Let us know if that makes the problem go away.

**Comment by hrehfeld** [comment]
Just to confirm, I run into the same issue with the same locale print as @greenisagoodcolor . It's an archlinuxarm box.

**Comment by prg318** [comment]
I just wanted to add that I experienced a similar error on a UTF-8 system:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/beets/util/__init__.py", line 352, in bytestring_path
    return path.encode(_fsencoding())
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 42: surrogates not allowed
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.4', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1228, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1215, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 933, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 885, in import_files
    if not os.path.exists(syspath(normpath(path))):
  File "/usr/lib/python3.6/site-packages/beets/util/__init__.py", line 133, in normpath
    return bytestring_path(path)
  File "/usr/lib/python3.6/site-packages/beets/util/__init__.py", line 354, in bytestring_path
    return path.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 42: surrogates not allowed
```
```
$ locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

This is potentially related and wasn't sure if I should open a new issue or add something here
