### ISSUE TITLE
python3 mpdstats str.decode error

### ISSUE THREAD

**Issue by artemutin** [beetbox/beets#2405]
### Problem

When trying to run plugin mpdstats with python 3 upstream beets version, I've got the error below. Just removing .decode('utf-8') part in line 59 makes things work again. I'm not sure, is it proper way to deal with this for python 2 compatibility, so no pr yet.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv mpdstats
```

Led to this problem:

```
user configuration: /home/chichi/.config/beets/config.yaml
data directory: /home/chichi/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Data/music/musiclibrary.blb
library directory: /Data/music
Sending event: library_opened
mpdstats: connecting to localhost:6600
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.4', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdstats.py", line 366, in func
    MPDStats(lib, self._log).run()
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdstats.py", line 307, in run
    status = self.mpd.status()
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdstats.py", line 141, in status
    return self.get('status')
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdstats.py", line 107, in get
    return getattr(self.client, command)()
  File "/usr/lib/python3.6/site-packages/mpd.py", line 629, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/usr/lib/python3.6/site-packages/mpd.py", line 254, in _execute
    return retval()
  File "/usr/lib/python3.6/site-packages/mpd.py", line 623, in decorator
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mpd.py", line 404, in _fetch_object
    objs = list(self._read_objects())
  File "/usr/lib/python3.6/site-packages/mpd.py", line 332, in _read_objects
    for key, value in self._read_pairs():
  File "/usr/lib/python3.6/site-packages/mpd.py", line 311, in _read_pairs
    pair = self._read_pair(separator)
  File "/usr/lib/python3.6/site-packages/mpd.py", line 302, in _read_pair
    line = self._read_line()
  File "/usr/lib/python3.6/site-packages/beetsplug/mpdstats.py", line 59, in _read_line
    return line.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

```

### Setup

* OS: Arch Linux x64
* Python version: Python 3.6.0
* beets version: 1.4.4
* Turning off plugins made problem go away (yes/no): yes, obviously

My configuration (output of `beet config`) is:

```yaml
directory: /Data/music
library: /Data/music/musiclibrary.blb

import:
    move: no

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

match:
    strong_rec_thresh: 0.1

plugins: fetchart lastgenre types bpm chroma convert discogs fetchart mpdstats replaygain scrub rewrite fuzzy info random play smartplaylist mpdupdate web acousticbrainz absubmit types duplicates
chroma:
    auto: yes
echonest:
    auto: no
    upload: yes
fetchart:
    google_search: yes
    sources: coverart itunes amazon albumart wikipedia google fanarttv filesystem
    maxwidth: 500
    auto: yes
    minwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
lastgenre:
    canonicalize: yes
    count: 3
    whitelist: yes
    min_weight: 10
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
replaygain:
    backend: command
    overwrite: no
    auto: yes
    targetlevel: 89
    command: ''
    noclip: yes
types:
    rating: float
    play_count: int
    mood_happy: float
    mood_electronic: float
    mood_sad: float
    mood_acoustic: float
    mood_party: float
    mood_aggressive: float
    mood_relaxed: float
    bpm: int

convert:
    auto: yes
    dest: /Data/music
    format: ogg
    formats:
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 5 $dest
        aac:
            command: ffmpeg -i $source -y -vn -acodec libfaac -aq 100 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    extension: ogg

    paths:
        default: $albumartist/$album%aunique{}/$track $title
        singleton: Non-Album/$artist/$title
        comp: Compilations/$album%aunique{}/$track $title
    pretend: no
    threads: 4
    max_bitrate: 500
    tmpdir:
    quiet: no
    embed: yes
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
mpd:
    port: 6600
    rating-mix: 0.5
    host: localhost
    password: REDACTED
    music_directory: /Data/music
    rating: yes
    rating_mix: 0.75
play:
    command: vlc
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
smartplaylist:
    relative_to: /Data/music
    playlist_dir: /Data/music/playlists
    playlists: [{name: workout.m3u, query: 'mood_aggressive::0\.[7-9]'}, {name: fast.m3u, query: 'bpm:120..250 mood_happy:0.5..1'}]
    auto: yes
absubmit:
    extractor: ''
fuzzy:
    prefix: '~'
    threshold: 0.7
scrub:
    auto: yes
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
bpm:
    max_strokes: 3
    overwrite: yes
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
rewrite: {}
acousticbrainz:
    auto: yes
    force: no
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    include_paths: no

```

**Comment by sampsyo** [comment]
Thank you! I believe I've just pushed a fix for this problem, which was indeed a Python 3 porting issue. Can you try the latest source to check that everything works now?

**Comment by artemutin** [comment]
Yes, it works well now.

**Comment by sampsyo** [comment]
Yay; thanks!
