### ISSUE TITLE
how to check for existence of a metadata plugin tag in item_fields section of the inline plugin ?

### ISSUE THREAD

**Issue by euri10** [beetbox/beets#2406]
### Problem

I want to use acousticbrains tags, tonal in particular, in a custom format with the inline plugin, but I fail at checking if the tag exists.

So when the tonal field exists it's ok:
```
➜  ~ beet ls wisemen
01/15--Wisemen Approaching---Wisemen-----Introducing (No Matt--Rap-------
-------124 bpm-- --0.946985244751--
```
now issue is when it doesn't
```
➜  ~ beet ls wise
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1071, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1067, in list_items
    ui.print_(format(item, fmt))
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 341, in __format__
    return self.evaluate_template(spec)
  File "/usr/local/lib/python2.7/dist-packages/beets/dbcore/db.py", line 464, in evaluate_template
    self._template_funcs())
  File "/usr/local/lib/python2.7/dist-packages/beets/util/functemplate.py", line 574, in substitute
    res = self.interpret(values, functions)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/functemplate.py", line 566, in interpret
    return self.expr.evaluate(Environment(values, functions))
  File "/usr/local/lib/python2.7/dist-packages/beets/util/functemplate.py", line 274, in evaluate
    out.append(part.evaluate(env))
  File "/usr/local/lib/python2.7/dist-packages/beets/util/functemplate.py", line 176, in evaluate
    if self.ident in env.values:
  File "/usr/lib/python2.7/_abcoll.py", line 388, in __contains__
    self[key]
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 382, in __getitem__
    value = self._get(key)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 373, in _get
    return self._get_formatted(self.model, key)
  File "/usr/local/lib/python2.7/dist-packages/beets/dbcore/db.py", line 69, in _get_formatted
    value = model._type(key).format(model.get(key))
  File "/usr/local/lib/python2.7/dist-packages/beets/dbcore/db.py", line 305, in get
    return self[key]
  File "/usr/local/lib/python2.7/dist-packages/beets/dbcore/db.py", line 228, in __getitem__
    return getters[key](self)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/inline.py", line 114, in _expr_func
    raise InlineError(python_code, exc)
beetsplug.inline.InlineError: error in inline path field code:
u'--{}--'.format(tonal)
NameError: name 'tonal' is not defined
```
 I'm aware of the `%ifdef{$tonal,$tonal,'no'}` that works well in my config snippet below if I put it straight into the `format_item` (the commented `format_item` line below)

Now I'd wish to test for that existence in the  `item_fields:` section of the inline plugin to format it to my needs, this is where I fail, any idea if that's possible ?

### Setup

* OS: debian
* Python version: 2.7.13
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): 

My configuration (output of `beet config`) is:

```yaml
format_item: $my_format $my_acousticbrainz
#format_item: $track/$tracktotal - $album - $albumartist - $title - $artist - $genre - [$bpm - %ifdef{$tonal,$tonal,'no'} - $key_str    ength]

item_fields:
my_acousticbrainz: u'--{}--'.format(tonal)
my_format: u'{:02d}/{:02d}--{:-<20.20}--{:-<10.10}--{:-<20.20}--{:-<10.10}\n-------{:3.0f} bpm--'.format(track, tracktotal, album, albumartist, title, genre, bpm)

```

**Comment by sampsyo** [comment]
The inline plugin sets all the values as Python local variables. So you can use any technique to check whether a given variable name exists in scope, like so: http://stackoverflow.com/questions/843277/how-do-i-check-if-a-variable-exists

**Comment by euri10** [comment]
well I tried 3 things, none behave like the ifdef

- my_acousticbrainz that uses the try/except looks fine at first sight, but if a match has been previously found, the variable still exists and is displayed for subsequent ls matches which is wrong, see log below, item 01/19 display a tonal while it has none, it uses the one fron the item 15/15 just above.

- my_abz_local that checks in locals() fails every time

- my_abz_global has the same behaviour as the try / except, 

should the variable be de-registered somewhat or is it something I should take care of in my custom item_fields ?


```
➜  ~ beet ls ennio
......(removed for readability)....
12/15--Once Upon a Time in --Ennio Morr--Friends---------------Classical-
-------118 bpm-- 'no' --0.933286130428-- locals? --0.933286130428--
13/15--Once Upon a Time in --Ennio Morr--Friendship and Love---Classical-
-------152 bpm-- 'no' --0.983314812183-- locals? --0.983314812183--
14/15--Once Upon a Time in --Ennio Morr--Speakeasy-------------Classical-
-------110 bpm-- 'no' --0.803279161453-- locals? --0.803279161453--
15/15--Once Upon a Time in --Ennio Morr--Deborah's Theme / Am--Classical-
-------136 bpm-- 'no' --0.952246785164-- locals? --0.952246785164--
......(the next item has no tonal yet shows the one of the previous item found)....
01/19--Yo-Yo Ma Plays Ennio--Yo-Yo Ma /--Gabriel's Oboe------------------
-------  0 bpm-- 'no' --0.952246785164-- locals? --0.952246785164--
02/19--Yo-Yo Ma Plays Ennio--Yo-Yo Ma /--The Falls-----------------------
......(removed for readability)....
```

```yaml
format_item: $my_format %ifdef{$tonal,$tonal,'no'} $my_acousticbrainz $my_abz_local $my_abz_global
item_fields:
    my_acousticbrainz: |
        try:
            return u'--{}--'.format(tonal)
        except NameError:
            return u'exception'
    my_abz_local: |
        if 'tonal' in locals():
            return u'--{}--'.format(tonal)
        else:
            return u'locals?'
    my_abz_global: |
        if 'tonal' in globals():
            return u'--{}--'.format(tonal)
        else:
            return u'globals?'
    my_format: u'{:02d}/{:02d}--{:-<20.20}--{:-<10.10}--{:-<20.20}--{:-<10.10}\n-------{:3.0f} bpm--'.format(track, tracktotal, album, albumartist, title, genre, bpm)
```

**Comment by sampsyo** [comment]
Sorry, I don't understand from that output what's going on here. Maybe you can cook up instructions to reproduce the problem from scratch locally?
