### ISSUE TITLE
bpd dependency error

### ISSUE THREAD

**Issue by claman** [beetbox/beets#2409]
### Problem

Attempting to run `beet bpd` is crashing on a ValueError because gi hasn't been updated to Python3. It doesn't like the package itself is still under development.

```Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/bpd/__init__.py", line 1192, in func
    self.start_bpd(lib, host, int(port), password, volume, debug)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/bpd/__init__.py", line 1166, in start_bpd
    server = Server(lib, host, port, password)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/bpd/__init__.py", line 748, in __init__
    from beetsplug.bpd import gstplayer
  File "/usr/local/lib/python3.6/site-packages/beetsplug/bpd/gstplayer.py", line 31, in <module>
    import gi
  File "/usr/local/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

### Setup

* OS: macOS 10.12.2
* Python version: 1.4.3
* beets version: 3.6.0

**Comment by sampsyo** [comment]
Hmm, are you sure you have the right dependency? `gi` is python-gobject, and it needs to be installed via an OS-specific package manager (as indicated in the plugin's docs) and definitely supports Python 3. You may have run `pip install gi`, which gets a different package.

**Comment by claman** [comment]
I was trying to use the pip version of gi. I uninstalled that and now I'm getting `ModuleNotFoundError: No module named 'gi'` at the end of the error message. I have pygobject3 installed

**Comment by sampsyo** [comment]
The package has many different names depending on your OS, package manager, and Python version. It's just a guessing game, unfortunately. I don't know what the package is called in Homebrew, for example. Good luck finding the right package to install!

**Comment by claman** [comment]
I'm honestly unsure what I did, but it's now working. Had to uninstall and reinstall twice.

**Comment by sampsyo** [comment]
Weird! But glad it's working now.
