### ISSUE TITLE
MemoryError on ending path definition with a newline

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2562]
### Problem

Dunno if this is within scope, but thought you might like to know. I get 15% CPU usage and 400 MB of memory usage from Python when I run just "beet" from the command line with no parameters. It also takes a while to crash out. This is most likely caused by referencing a variable in my `paths` section that are not defined in the config.

Running this command in verbose (`-vv`) mode:

```sh
C:\Users\RollingStar>beet -vv
user configuration: C:\Users\RollingStar\AppData\Roaming\beets\config.yaml
data directory: C:\Users\RollingStar\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
Traceback (most recent call last):
  File "C:\Users\RollingStar\AppData\Local\Programs\Python\Python36-32\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1209, in main
    _raw_main(args)
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1192, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1098, in _setup
    lib = _open_library(config)
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1145, in _open_library
    get_path_formats(),
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 601, in get_path_formats
    path_formats.append((query, Template(view.as_str())))
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\util\functemplate.py", line 553, in __init__
    self.expr = _parse(template)
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\util\functemplate.py", line 538, in _parse
    parser.parse_expression()
  File "c:\users\RollingStar\appdata\local\programs\python\python36-32\lib\site-packages\beets\util\functemplate.py", line 361, in parse_expression
    text_parts.append(self.string[self.pos:next_pos])
MemoryError
```

### Setup

Win10 x64
beets version 1.4.3
Python version 3.6.0
no plugins loaded

My configuration (output of `beet config`) is:

```yaml
directory: e:\Music\
library: e:\songs\beetslibrary.bib

paths:
    default: |
        test1 $track. $title
```

**Comment by sampsyo** [comment]
Wow! That's certainly weird. But `test1 $track. $title` actually looks like a perfectly acceptable format string—does changing it around further (or removing the newline) have any effect?

**Comment by RollingStar** [comment]
My mistake. This is the config that memory leaks until crashing. A less interesting bug.

```directory: e:\Music\
library: e:\songs\beetslibrary.bib

paths:
    default: |
        test1 $track. $title
album_fields:
    test3: |
        return ''
```

**Comment by sampsyo** [comment]
Hmm; that's strange. Is the `album_fields` part necessary, or does the crash still happen when that's removed?

```yaml
library: e:\songs\beetslibrary.bib

paths:
    default: |
        test1 $track. $title
```

I'm pretty surprised that declaring `album_fields` would have any effect at all when `inline` is disabled.

**Comment by RollingStar** [comment]
The config you posted does not crash Beets. Just tested again with the ones I put in my most recent post (above), and both still memory leak until crashing.

**Comment by sampsyo** [comment]
That's odd; I was actually able to reproduce this just by including a newline in the path format:

```yaml
paths:
    default: |
        foo
```

No `album_fields` necessary. Looks like a bug in my little template parser… looking into it now.

**Comment by RollingStar** [comment]
Yeah, now that you say that, it looks to be the cause. Ending the file (and thus the path definition) with a newline crashes beets.

**Comment by sampsyo** [comment]
OK; that should do it! Can you give the latest source a try to see if it fixes things?

**Comment by RollingStar** [comment]
That fixed it!
