### ISSUE TITLE
Error when importing music

### ISSUE THREAD

**Issue by kingofinfo** [beetbox/beets#2584]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import [...]
```

Led to this problem:

```
mpdupdate: Updating MPD database...
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1198, in _raw_main
    plugins.send('cli_exit', lib=lib)
  File "/usr/local/lib/python3.6/site-packages/beets/plugins.py", line 452, in send
    result = handler(**arguments)
  File "/usr/local/lib/python3.6/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/mpdupdate.py", line 92, in update
    config['mpd']['password'].as_str(),
  File "/usr/local/lib/python3.6/site-packages/beetsplug/mpdupdate.py", line 108, in update_mpd
    resp = s.readline()
  File "/usr/local/lib/python3.6/site-packages/beetsplug/mpdupdate.py", line 53, in readline
    self.buf += data
TypeError: must be str, not bytes
```

Here's a link to the music files that trigger the bug (if relevant): 
Bug is triggered by importing any music files

### Setup

* OS: MacOS 10.12.5
* Python version: 3.6.1
* beets version: 1.4.3
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
library: /Volumes/music/beets/musiclibrary.blb

import:
    move: yes

plugins: lastgenre fetchart ftintitle mpdupdate smartplaylist random embedart
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
mpd:
    host: localhost
    port: 6600
    password: REDACTED
ftintitle:
    auto: yes
    drop: no
    format: feat. {0}
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
smartplaylist:
    relative_to:
    playlist_dir: .
    auto: yes
    playlists: []
```

**Comment by sampsyo** [comment]
Hi! I think this is an instance of #2381. Sorry this isn't released yet—I'll push out 1.4.4 soon, or you can try running the latest source (there are instructions in the FAQ).
