### ISSUE TITLE
No module named [...] - Python 3.6.1 on Win10

### ISSUE THREAD

**Issue by acastaner** [beetbox/beets#2591]
### Problem

Just installed beets from scratch on a Windows 10 Pro machine running Python 3.6.1. Whenever I run the beet command I get a bunch of error messages complaining about missing modules. I reckon those are dependencies that I should install but I can't see anywhere in the documentation their package name.

Running this command in verbose (`-vv`) mode:

```sh
C:\Users\Arnaud>beet -vv
user configuration: C:\Users\Arnaud\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Arnaud\AppData\Roaming\beets
plugin paths:
** error loading plugin acousticbrainz:
Traceback (most recent call last):
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beets\plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\acousticbrainz.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

** error loading plugin chroma:
Traceback (most recent call last):
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beets\plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\chroma.py", line 27, in <module>
    import acoustid
ModuleNotFoundError: No module named 'acoustid'

** error loading plugin fetchart:
Traceback (most recent call last):
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beets\plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\fetchart.py", line 25, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

** error loading plugin copyartifacts:
Traceback (most recent call last):
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beets\plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "c:\users\arnaud\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\copyartifacts.py", line 141
    print 'Ignored files:'
                         ^
SyntaxError: Missing parentheses in call to 'print'

Sending event: pluginload
inline: adding item field initial
inline: adding item field disc_and_track
error: replaygain initialization failed: Is bs1770gain installed? Is your method in config correct?
```

(The replaygain error is obvious, I haven't got to set bs1770gain yet).

### Setup

* OS: Microsoft Windows [version 10.0.15063]
* Python version: 3.6.1
* beets version: Whatever the version `pip install beets` gives you.
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
directory: E:\Music
plugins: inline acousticbrainz chroma embedart fetchart lastgenre replaygain ftintitle copyartifacts
threaded: yes
autotag: yes
art_filename: cover
asciify_paths: yes
clutter: [".jpg", ".jpeg", ".png", ".sfv", ".nfo", ".m3u", ".m3u8", "Thumbs.DB", ".DS_Store"] 
# Albums will use the date of the original release rather than the selected one
original_date: yes
format_item: $artist - $album - $title ($genre)
match:
    strong_rec_thresh: 0.04
    preferred:
        countries: ['US', 'GB|UK', 'FR']
        media: ['CD', 'Digital Media|File']
original_year: yes

item_fields:
    initial: albumartist[0].upper() + u'.'
    disc_and_track: u'%02i-%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)
paths:
    albumtype:soundtrack: ost/$album/$disc_and_track. $title
    savedir:radionova: nova/$album/$disc_and_track. $artist - $title
    savedir:world: world/$albumartist/$year - $album/$disc_and_track. $title
    savedir:electro: electro/$albumartist/$year - $album/$disc_and_track. $title
    savedir:classical: classical/$artist/$album/$disc_and_track. $title
    savedir:alt_rock: alt_rock/$albumartist/$year - $album/$disc_and_track. $title
    savedir:rock: rock/$albumartist/$year - $album/$disc_and_track. $title
    savedir:jazz: jazz/$albumartist/$year - $album/$disc_and_track. $title
    savedir:blues: blues/$albumartist/$year - $album/$disc_and_track. $title
    savedir:metal: metal/$albumartist/$year - $album/$disc_and_track. $title
    savedir:rap: rap/$albumartist/$year - $album/$disc_and_track. $title
    savedir:pop: pop/$albumartist/$year - $album/$disc_and_track. $title
    savedir:techno: techno/$albumartist/$year - $album/$disc_and_track. $title
    default: _trier/$albumartist/$year - $album/$disc_and_track. $title
    comp: $genre/$album/$track. $title
ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
import:
    write: yes
    copy: yes
    move: yes
    resume: ask
## PLUGINS ##
ftintitle:
    auto: yes
acousticbrainz:
    auto: yes
chroma:
    auto: no
acoustid:
    apikey: redacted
embedart:
    auto: yes
    ifempty: yes
fetchart:
    auto: yes
    cover_names: cover front art album folder
    sources: filesystem coverart itunes amazon albumart fanarttv
lastgenre:
    auto: yes
lastfm: 
    user: FurismSA
replaygain:
    backend: bs1770gain
    auto: yes
copyartifacts:
    extensions: .cue .log
    print_ignored: yes
```

**Comment by Kraymer** [comment]
Hello,
You can find the package names to provide to `pip install` in https://github.com/beetbox/beets/blob/master/setup.py#L113

**Comment by Kraymer** [comment]
Just posted it to unblock you but you're not supposed to do that, something went wrong with your install as missing dependencies are supposed to be brought in during the install process.

**Comment by acastaner** [comment]
Well I installed using the simple ``pip install beet`` command, there's not much room to go wrong there. There definitively wasn't any error message when I installed. Maybe on Windows the dependencies have to be installed explicitly? Or maybe it's a Python 3.6.1 thing?

In any case, I can happily help troubleshoot this.

**Comment by sampsyo** [comment]
Hi, @acastaner—there are instructions at the top of the documentation page for each plugin about how to install the plugin's dependencies with pip.
