### ISSUE TITLE
Can't import with fetchart enabled.

### ISSUE THREAD

**Issue by ploprof** [beetbox/beets#2689]
### Problem

Everytime I attempt to use the command beet import I get the following bug, this only happens when I have the fetchart plugin enabled. Without it the import works just fine.

```
Tagging:
    Joy Division - Unknown Pleasures
URL:
    https://musicbrainz.org/release/8666f5b9-99f1-39a9-a0e9-65a727b4cc90
(Similarity: 100.0%) (Cassette, 1985, GB, Factory)
 * Day Of The Lords -> Day of the Lords
This album is already in the library!
Old: 9 items, FLAC, 816kbps, 35:53, 206.8 MiB
New: 10 items, FLAC, 763kbps, 39:40, 214.5 MiB
[S]kip new, Keep both, Remove old? R
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 930, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 907, in import_files
    session.run()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 319, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1392, in plugin_stage
    func(session, task)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 797, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/lib/python2.7/site-packages/beetsplug/fetchart.py", line 867, in art_for_album
    for candidate in source.get(album, extra):
TypeError: get() takes exactly 4 arguments (3 given)
```

### Setup

* OS: Fedora 26 Server Version
* Python version: Python 2.7.13
* beets version: beets version 1.4.3
* Turning off plugins made problem go away (yes/no): 
yes, turning off fetchart made it go away 
My configuration (output of `beet config`) is:

```
lyrics:
    bing_lang_from: []
    auto: yes
    fallback: ''
    bing_client_secret: REDACTED
    google_API_key: REDACTED
    force: no
    google_engine_ID: REDACTED
    sources:
    - google
    - lyricwiki
    - lyrics.com
    - musixmatch
    genius_api_key: REDACTED
    bing_lang_to:
verbose: no
echonest_tempo:
    auto: yes
color: yes
max_filename_length: 0
library: /mnt/1tb/Music/musiclibrary.blb

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
terminal_encoding: utf8
replaygain:
    auto: yes
    overwrite: yes
    albumgain: yes

clutter:
- Thumbs.DB
- .DS_Store
- '*.m3u'
- .pls
- '*.jpg'

plugins:
- discogs
- lyrics
- fetchart
- bandcamp
- embedart
- lastgenre
- scrub
- mbsync
- missing
- duplicates

paths:
    default: '%asciify{$albumartist}/%asciify{$album}%aunique{}/$track %asciify{$title}'
    singleton: Non-Album/%asciify{$artist}/%asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}
per_disc_numbering: no
bandcamp:
    lyrics: yes
    art: yes
    min_candidates: 5
    source_weight: 0.5
lastgenre:
    whitelist: no
    canoncical: ~/.config/beets/genres-tree.yaml
    fallback: ''
    source: artist
    count: 1
    prefer_specific: no
    force: yes
    min_weight: 10
    auto: yes
    separator: ', '
    canonical: no
path_sep_replace: _

import:
    write: yes
    move: yes
    copy: no
    delete: no
    autotag: yes
    timid: no
    resume: ask
    incremental: yes
    none_rec_action: ask
    log:
    quiet: no
    quiet_fallback: skip
    default_action: apply
    singletons: no
    languages: []
    detail: no
    flat: no

match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30
scrub:
    auto: yes
fetchart:
    auto: yes
    maxwidth: 300
    cautious: yes
    cover_names: cover folder
    minwidth: 0
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_engine: 001442825323518660753:hrh5ch1gjzm
    enforce_ratio: no
    store_source: no
    google_key: REDACTED
    fanarttv_key: REDACTED
embedart:
    auto: yes
    maxwidth: 300
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
time_format: '%Y-%m-%d %H:%M:%S'
pluginpath: []
list_format_album: '%upper{$albumartist} - $album'
list_format_item: '%upper{$artist} - $album - $track. $title'
art_filename: cover
threaded: yes
original_date: no
ignore: [.*, '*~', System Volume Information]

ui:
    terminal_width: 80
    length_diff_thresh: 10.0
timeout: 5.0
directory: /mnt/1tb/Music
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
missing:
    count: no
    total: no
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5

```

**Comment by sampsyo** [comment]
Hi! It looks like you're using beets 1.4.3, but there are more recent versions available—can you try with the latest beets?

If the problem persists, we'll want to narrow down which fetchart backend is causing the problem. Can you try disabling them to see if eliminating one makes the crash go away?

**Comment by ploprof** [comment]
Updating beets worked thank you. Can close issue now. 


14. Sep 2017 05:30 by notifications@github.com:

**Comment by sampsyo** [comment]
Great! FWIW, you have the power to close your issues yourself.
