### ISSUE TITLE
ValueError: MP4 files only supports PNG and JPEG images

### ISSUE THREAD

**Issue by tobiaswuerth** [beetbox/beets#2713]
### Problem

Running this command:

```cmd
beet import -s -q Z:\music\
```

Led to this problem:

```
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.5', 'console_scripts', 'beet')()
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\ui\commands.py", line 934, in import_func
    import_files(lib, paths, query)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\ui\commands.py", line 911, in import_files
    session.run()
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\importer.py", line 325, in run
    pl.run_parallel(QUEUE_SIZE)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\util\pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\util\pipeline.py", line 358, in run
    self.coro.send(msg)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\util\pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\importer.py", line 1459, in manipulate_files
    session=session,
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\importer.py", line 708, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\plugins.py", line 452, in send
    result = handler(**arguments)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beetsplug\scrub.py", line 150, in import_task_files
    self._scrub_item(item)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beetsplug\scrub.py", line 140, in _scrub_item
    mf.images = images
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\mediafile.py", line 1239, in __set__
    style.set_list(mediafile.mgfile, values)
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\mediafile.py", line 593, in set_list
    self.store(mutagen_file, [self.serialize(value) for value in values])
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\mediafile.py", line 593, in <listcomp>
    self.store(mutagen_file, [self.serialize(value) for value in values])
  File "d:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\beets\mediafile.py", line 727, in serialize
    raise ValueError(u'MP4 files only supports PNG and JPEG images')
ValueError: MP4 files only supports PNG and JPEG images
```

### Setup

* OS: Microsoft Windows Server 2016 Standard
* Python version: v3.6.3:2c5fed8
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no):  not sure, cannot reproduce

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    sources: [google, lyricwiki, musixmatch]
directory: Z:\music\_\
library: D:\programs\beets\data.db

import:
    move: yes
    write: yes
    link: no
    hardlink: no
    resume: no
    copy: no

replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
    ^\s+: ''
    ^-: _

ui:
    color: no

plugins: scrub web chroma acousticbrainz embedart fetchart lyrics lastgenre
terminal_encoding: utf_8

match:
    strong_rec_thresh: 0.1
    medium_rec_thresh: 0.1
    rec_gap_thresh: 0.1
chroma:
    auto: yes

paths:
    default: $genre/$albumartist/$album%aunique{}/$track-$title
    singleton: $genre/$albumartist/$album%aunique{}/$track-$title
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    reverse_proxy: no
    include_paths: no
embedart:
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
scrub:
    auto: yes
acousticbrainz:
    auto: yes
    force: no
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
```

I think the error message itself is pretty clear, but I don't think that the whole import process should be stopped/crash because of this.

**Comment by sampsyo** [comment]
Indeed! This should be impossible. Do you have any hints about how to reproduce the problem?

**Comment by tobiaswuerth** [comment]
I'm really sorry but I don't. I tried to reproduce it but it worked the 2nd time i let it run. I figured I might as well post what I got instead of just ignoring it. Maybe the stack-trace would be enough to find the origin of the exception.

**Comment by sampsyo** [comment]
No worries! Thanks for the report in any case. It will take a little more investigation to nail down the cause, but it looks like we may need an exception handler in the `scrub` plugin.

**Comment by Ranbato** [comment]
Actually I've gotten this twice today.  Re-running the import has it continue, but it skips the file it crashed on
```

# selection (default 1), Skip, Use as-is, Enter search, enter Id, aBort?
Tagging track: Lipps, Inc. - Funkytown
URL:
    https://musicbrainz.org/recording/c17d7eac-fb0c-415a-9719-27ec3d06db67
(Similarity: 70.6%) (id)
Apply, More candidates, Skip, Use as-is, Enter search, enter Id, aBort? a
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1291, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1278, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 341, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 442, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 355, in run
    self.coro.send(msg)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 1568, in manipulate_files
    task.manipulate_files(
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 765, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 498, in send
    result = handler(**arguments)
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 153, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/beetsplug/scrub.py", line 151, in import_task_files
    self._scrub_item(item)
  File "/usr/lib/python3.8/site-packages/beetsplug/scrub.py", line 141, in _scrub_item
    mf.images = images
  File "/usr/lib/python3.8/site-packages/mediafile.py", line 1244, in __set__
    style.set_list(mediafile.mgfile, values)
  File "/usr/lib/python3.8/site-packages/mediafile.py", line 596, in set_list
    self.store(mutagen_file, [self.serialize(value) for value in values])
  File "/usr/lib/python3.8/site-packages/mediafile.py", line 596, in <listcomp>
    self.store(mutagen_file, [self.serialize(value) for value in values])
  File "/usr/lib/python3.8/site-packages/mediafile.py", line 730, in serialize
    raise ValueError(u'MP4 files only supports PNG and JPEG images')
ValueError: MP4 files only supports PNG and JPEG images
```
