### ISSUE TITLE
Beets crashes when lastgenre activated

### ISSUE THREAD

**Issue by mrzool** [beetbox/beets#2715]
### Problem

With `lastgenre` active, any `beet` command I issue fails leaving the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1239, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1130, in _setup
    plugins = _load_plugins(config)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1116, in _load_plugins
    plugins.send("pluginload")
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 451, in send
    for handler in event_handlers()[event]:
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 434, in event_handlers
    for plugin in find_plugins():
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 288, in find_plugins
    _instances[cls] = cls()
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 115, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/site-packages/beetsplug/lastgenre/__init__.py", line 131, in setup
    wl_filename = normpath(wl_filename)
  File "/usr/local/lib/python2.7/site-packages/beets/util/__init__.py", line 132, in normpath
    path = os.path.normpath(os.path.abspath(os.path.expanduser(path)))
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'list' object has no attribute 'startswith'
```
### Setup

* OS: Mac OS X El Capitan
* Python version: 2.7.14
* beets version: 1.4.5
* Turning off `lastgenre` makes the problem go away.

My `lastgenre` configuration:

```yaml
lastgenre:
    canonical: yes
    whitelist:
    - acoustic
    - electronic
    - hip-hop
    - classical
    - rock
    - jazz
```

Thanks for any pointer.

**Comment by wordofglass** [comment]
(Disclaimer: I'm not using lastgenre myself and haven't looked at the code either)

According to [the documentation](http://beets.readthedocs.io/en/v1.4.5/plugins/lastgenre.html#configuration), `whitelist` is supposed to be a path to a file that contains the whitelist, and not directly a YAML list. In principle, the plugin could be changed to distinguish either a YAML list or scalar item (that would have the same meaning as of now which would also ensure compatibility).

**Comment by mrzool** [comment]
I had overlooked that detail in the docs, that solves it!

Thank you very much @wordofglass.

**Comment by sampsyo** [comment]
Indeed; thank you! Perhaps we should at least add a check so we can void the crash. But indeed, inlining a list of genres seems like a good addition too.
