### ISSUE TITLE
convert plugin converts well, maybe too

### ISSUE THREAD

**Issue by euri10** [beetbox/beets#2769]
### Problem

I import usually FLAC in my main library (drive1), and I have the convert plugin configured to autoconvert the FLAC into MP3 to another library folder (on drive6).
My issue is that now I got the mp3 in my main library, the conversion worked well but I don't get why the mp3 are both in my main library and in the "converts" librar, maybe its a misuse and a misundertanding on my end, ideally I would like to 1) import flac in drive1 and 2) convert them into mp3 in drive6

Relevant config parts are

```yaml

(beets) ➜  beets git:(master) cat ~/.config/beets/config.yaml 
directory: /media/drive1/BEETS
library: /home/lotso/.config/beets/musiclibrary.blb
import:
    write: yes
    move: no
    timid: yes
format_album: $albumartist - $album - $genre $added
plugins: discogs fetchart convert beatport lastgenre scrub smartplaylist acousticbrainz inline mpdstats bpm
convert:
    dest: /media/drive6/MPEETS
    format: mp3
    auto: yes
````

Running this command in verbose (`-vv`) mode:

```sh
(beets) ➜  beets git:(master) beet -vv import  /media/drive6/toadd/Yotam\ Avni\ -\ If\ You\ Still\ Want\ Me\ \{WEB\}\ \[FLAC\]\ \(2017\) 
user configuration: /home/lotso/.config/beets/config.yaml
data directory: /home/lotso/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/lotso/.config/beets/musiclibrary.blb
library directory: /media/drive1/BEETS
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)
Tagging Yotam Avni - If You Still Want Me
No album ID found.
Search terms: Yotam Avni - If You Still Want Me
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'if you still want me', 'tracks': '3', 'artist': 'yotam avni'}
Requesting MusicBrainz release e0cec698-b2df-440a-820a-61dfc9b02743
primary MB release type: album
Sending event: albuminfo_received
Candidate: Yotam Avni - Tehillim (e0cec698-b2df-440a-820a-61dfc9b02743)
Computing track assignment...
...done.
Success. Distance: 0.56
Requesting MusicBrainz release 08d57287-f66d-4c4b-84b7-16f46424e973
primary MB release type: album
Sending event: albuminfo_received
Candidate: Yotam Avni - Tehillim (08d57287-f66d-4c4b-84b7-16f46424e973)
Computing track assignment...
...done.
Success. Distance: 0.56
Requesting MusicBrainz release 0b47d398-8a33-4a96-8b4b-cae77507c86a
primary MB release type: single
Sending event: albuminfo_received
Candidate: Yotam Avni - Monad XXII (0b47d398-8a33-4a96-8b4b-cae77507c86a)
Computing track assignment...
...done.
Success. Distance: 0.61
Requesting MusicBrainz release 3f58a233-c00c-339b-8cf3-05816596237c
primary MB release type: single
Sending event: albuminfo_received
Candidate: Super Furry Animals - If You Don't Want Me to Destroy You (3f58a233-c00c-339b-8cf3-05816596237c)
Computing track assignment...
...done.
Success. Distance: 0.70
Requesting MusicBrainz release c3d6bc5b-cec4-4d1a-a644-acd7acc837e8
primary MB release type: single
Sending event: albuminfo_received
Candidate: Super Furry Animals - If You Don't Want Me to Destroy You (c3d6bc5b-cec4-4d1a-a644-acd7acc837e8)
Computing track assignment...
...done.
Success. Distance: 0.71
Sending event: albuminfo_received
Candidate: Yotam Avni - If You Still Want Me (2095877)
Computing track assignment...
...done.
Success. Distance: 0.12
Sending event: albuminfo_received
Candidate: Yotam Avni - If You Still Want Me (10849344)
Computing track assignment...
...done.
Success. Distance: 0.06
Evaluating 7 candidates.

/media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017) (3 items)
Sending event: before_choose_candidate
Tagging:
    Yotam Avni - If You Still Want Me
URL:
    https://www.discogs.com/Yotam-Avni-If-You-Still-Want-Me/release/10849344
(Similarity: 93.8%) (source) (Discogs, File, 2017, UK, Hotflush Recordings)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? a
Sending event: import_task_choice
Sending event: import_task_apply
0 of 3 items replaced
Sending event: database_change
smartplaylist: added_last_week.m3u will be updated because of Yotam Avni - If You Still Want Me -  2017-12-27 17:24:07
smartplaylist: added_last_day.m3u will be updated because of Yotam Avni - If You Still Want Me -  2017-12-27 17:24:07
smartplaylist: all.m3u will be updated because of Yotam Avni - If You Still Want Me -  2017-12-27 17:24:07
smartplaylist: added_last_month.m3u will be updated because of Yotam Avni - If You Still Want Me -  2017-12-27 17:24:07
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
convert: Encoding /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)/1 If You Still Want Me.flac
convert: Finished encoding /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)/1 If You Still Want Me.flac
Sending event: write
Sending event: after_write
Sending event: database_change
convert: Encoding /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)/3 Moschico.flac
convert: Finished encoding /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)/3 Moschico.flac
Sending event: write
Sending event: after_write
Sending event: database_change
convert: Encoding /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)/2 Yamzo.flac
convert: Finished encoding /media/drive6/toadd/Yotam Avni - If You Still Want Me {WEB} [FLAC] (2017)/2 Yamzo.flac
Sending event: write
Sending event: after_write
Sending event: database_change
lastgenre: added last.fm album genre (artist): Techno
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
fetchart: trying source filesystem for album Yotam Avni - If You Still Want Me
fetchart: using well-named art file cover.jpg
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 986, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 836, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 573, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 334, in getMessage
    msg = str(self.msg)
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beets/logging.py", line 86, in __str__
    return self.msg.format(*args, **kwargs)
KeyError: 'WEB'
Call stack:
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beets/importer.py", line 1506, in plugin_stage
    func(session, task)
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beetsplug/fetchart.py", line 794, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beetsplug/fetchart.py", line 866, in art_for_album
    source, util.displayable_path(out.path)))
  File "/usr/lib/python3.5/logging/__init__.py", line 1273, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/home/lotso/venv/beets/lib/python3.5/site-packages/beets-1.4.7-py3.5.egg/beets/logging.py", line 91, in _log
    return super(StrFormatLogger, self)._log(level, m, (), exc_info, extra)
Message: <beets.logging.StrFormatLogger._LogMessage object at 0x7f2acf0806a0>
Arguments: ()
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: item_copied
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
scrub: auto-scrubbing /media/drive1/BEETS/Yotam Avni/If You Still Want Me/01 If You Still Want Me.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: auto-scrubbing /media/drive1/BEETS/Yotam Avni/If You Still Want Me/03 Moschico.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
scrub: auto-scrubbing /media/drive1/BEETS/Yotam Avni/If You Still Want Me/02 Yamzo.mp3
scrub: writing new tags after scrub
Sending event: write
Sending event: after_write
Sending event: art_set
Sending event: database_change
Sending event: album_imported
Sending event: import
Sending event: cli_exit
smartplaylist: Updating 4 smart playlists...
smartplaylist: Creating playlist added_last_week.m3u
smartplaylist: Creating playlist added_last_day.m3u
smartplaylist: Creating playlist all.m3u
smartplaylist: Creating playlist added_last_month.m3u
smartplaylist: 4 playlists updated

```

Led to this problem:

mp3s are imported in my library, which sucks I want FLACS :)

```sh
(beets) ➜  beets git:(master) beet remove -d if you still want me                                                                        

/media/drive1/BEETS/Yotam Avni/If You Still Want Me/01 If You Still Want Me.mp3 - If You Still Want Me
/media/drive1/BEETS/Yotam Avni/If You Still Want Me/02 Yamzo.mp3 - Yamzo
/media/drive1/BEETS/Yotam Avni/If You Still Want Me/03 Moschico.mp3 - Moschico
Really DELETE 3 files (y/n)? 
```

### Setup

* OS: debian sid/buster
* Python version: 3.5
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): didnt try

**Comment by euri10** [comment]
misunderstood the auto flag in the convert plugin, removing it solves my case, that is not a bug
