### ISSUE TITLE
Failing test_asciify_variable and test_asciify_character_expanding_to_slash

### ISSUE THREAD

**Issue by k0ral** [beetbox/beets#2799]
### Problem

Tests `test_asciify_variable` and `test_asciify_character_expanding_to_slash` are failing:

```
======================================================================
FAIL: test_asciify_variable (test.test_library.DestinationFunctionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-1.4.6.drv-0/source/test/test_library.py", line 594, in test_asciify_variable
    self._assert_dest(b'/base/abC_1_2d')
  File "/tmp/nix-build-beets-1.4.6.drv-0/source/test/test_library.py", line 565, in _assert_dest
    self.assertEqual(actual, dest)
AssertionError: '/base/abC_ 1_2 d' != '/base/abC_1_2d'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_asciify_character_expanding_to_slash (test.test_library.DestinationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-beets-1.4.6.drv-0/source/test/test_library.py", line 430, in test_asciify_character_expanding_to_slash
    self.assertEqual(self.i.destination(), np('lib/abC_1_2d'))
AssertionError: '/tmp/nix-build-beets-1.4.6.drv-0/source/lib/abC_ 1_2 d' != '/tmp/nix-build-beets-1.4.6.drv-0/source/lib/abC_1_2d'
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: database_change
beets: DEBUG: Sending event: database_change
--------------------- >> end captured logging << ---------------------
```

### Setup

* OS: Linux NixOS kernel 4.9.75
* Python version: 2.7
* beets version: 1.4.6
* unidecode version: 1.0.22

**Comment by sampsyo** [comment]
Thanks for filing—I noticed this on a PR Travis failure a bit ago:
https://github.com/beetbox/beets/pull/2788#issuecomment-357330624

It looks like the behavior of the Unidecode library changed. We either need to adapt to ask nicely for the developers to restore the old behavior.

**Comment by sampsyo** [comment]
I can confirm that the behavior of Unidecode changed for these characters. Before:

```
>>> unidecode.unidecode('½')
'1/2'
```

After:

```
>>> unidecode.unidecode('½')
' 1/2 '
```

This seems harmless enough, so I will update the expected results of the tests.
