### ISSUE TITLE
Bad Files / ReplayGain plugin error

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#2801]
### Problem

Neither command works.

```
C:\Users\redacted\Unorganized\Unorganized\Beets>beet replaygain
replaygain: analyzing Milky Way - サマータイム・ラヴ・ソング = Summertime Love Song  - 夏の日の恋 Theme From "A Summer Place"
replaygain: ReplayGain error: mp3gain failed
replaygain: analyzing Milky Way - サマータイム・ラヴ・ソング = Summertime Love Song  - 波 Wave
replaygain: ReplayGain error: mp3gain failed
replaygain: analyzing Milky Way - サマータイム・ラヴ・ソング = Summertime Love Song  - サーフィン・サマー( 浜辺のサンバ ) La Costa
replaygain: ReplayGain error: mp3gain failed

C:\Users\redacted\Unorganized\Unorganized\Beets>beet bad
Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36-32\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\badfiles.py", line 119, in check_bad
    status, errors, output = checker(path)
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\badfiles.py", line 68, in check_mp3val
    status, errors, output = self.run_command(["mp3val", path])
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\badfiles.py", line 64, in run_command
    output = output.decode(sys.getfilesystemencoding())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 31: invalid start byte

C:\Users\redacted\Unorganized\Unorganized\Beets>pause
```

### Setup

* OS: Windows 8
* Python version: 3.63
* beets version: 1.4.6

My configuration (output of `beet config`) is:

```
directory: M:/Media/Audio

plugins: missing lyrics fetchart duplicates replaygain zero discogs badfiles chroma

autotag: yes

art_filename: cover

clutter: .sfv .nfo .m3u Thumbs.DB .DS_Store

original_date: yes

va_name: Various

import:
    copy: no
    write: yes

chroma:
    auto: yes
duplicates:
    album: yes
    move: C:/Users/redacted/Unorganized/Media/Audio/Fix/Duplicates
fetchart:
    auto: yes
lyrics:
    auto: yes
    force: yes
    sources: lyricwiki musixmatch genius google
    google_API_key: redacted
    fallback: ''
replaygain:
    auto: yes
    backend: command
zero:
    auto: yes
    keep_fields: 
        - artist
        - title
        - album
        - year
        - genre
        - composer
        - albumartist
        - track
        - tracktotal
        - disc
        - disctotal
        - first played
        - last played
        - lyrics
        - play count
        - rating
        - romanized artist name
        - acoustid_fingerprint
        - acoustid_id
discogs:
    user_token: redacted
```

**Comment by arcresu** [comment]
Hi! Sorry you didn't get an answer to this issue. It's really difficult for the community to help you with the problem without more detailed information like verbose output and some way for other users to reproduce the issue. For example the problem might be related to the specific files that you're working with.

There are a few issues open on the tracker currently that are related to encoding issues. Did you have a loot to see if any of those sound like your issue?

**Comment by firewater2** [comment]
I run macOS now, and I'd imagine some parts of the aforementioned setup are different too. I know I disabled the ReplayGain plugin, so I'll reopen the issue if it encounter trouble when I come back to that. Regarding the bad files, I think it's fair to assume they're corrupted somehow. I'd rather just, uhm... _obtain_ them again.
