### ISSUE TITLE
move: Crash when selecting albums to move

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#2802]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv move -cta -d /home/soergeld/Personnel/Music/
```

Led to this problem:

```
user configuration: /home/soergeld/.config/beets/config.yaml
data directory: /home/soergeld/.config/beets
plugin paths: 
Sending event: pluginload
library database: /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets2/Musicdata2.db
library directory: /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets2
Sending event: library_opened
Copying 1787 albums.
Really copy? (Yes/no/select) select

Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1516, in move_func
    opts.timid, opts.export)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1494, in move_items
    lambda o: show_path_changes(
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 410, in input_select_objects
    rep(obj)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 1495, in <lambda>
    [(o.path, o.destination(basedir=dest))]))
  File "/usr/local/lib/python2.7/dist-packages/beets/dbcore/db.py", line 338, in __getattr__
    raise AttributeError(u'no such field {0!r}'.format(key))
AttributeError: no such field 'destination'

```

If I don't use -t, it works, if I select 'Yes' or 'no' it works fine. 

### Setup

* OS: Ubuntu 17.10
* Python version: Python 2.7.13
* beets version: 1.4.6 (with additional parentwork plugin and fetches work as in https://github.com/dosoe/beets/tree/beets_parentwork, but that only adds a field so shouldn't do anything)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
paths:
    default: '%asciify{$albumartist_sort/$album %aunique{album}//$disc-$track $title}'
    singleton: '%asciify{ZZZ_noalbum/$artist_sort/$title}'
parentwork:
    force: yes
    bin: parentwork
    auto: yes
bell: yes
duplicates:
    tiebreak:
        items: [bitrate]
    keys: [mb_trackid, mb_releasegroupid]
    count: no
    full: no
    format: ''
    move: ''
    tag: ''
    path: no
    copy: ''
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
missing:
    count: yes
    album: no
    total: no
library: /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets2/Musicdata2.db
badfiles:
    commands:
        ogg: ogginfo -q

plugins: inline web duplicates edit info mbsync the badfiles fromfilename missing parentwork
directory: /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets2

import:
    copy: no
    write: no
    incremental: no
    detail: yes
    languages: en
    duplicate_action: keep
    bell: yes
    per_disc_numbering: yes

match:
    max_rec:
        missing_tracks: none
the:
    a: yes
    patterns: []
    the: yes
    strip: no
    format: '{0}, {1}'
edit:
    itemfields: track title artist album
    albumfields: album albumartist
    ignore_fields: id path
pathfields: {}
album_fields: {}
item_fields: {}
web:
    host: 127.0.0.1
    include_paths: no
    port: 8337
    reverse_proxy: no
    cors: ''
```

**Comment by sampsyo** [comment]
Thanks! It looks like this branch in `move_items` only works for items. Doing this in item mode (without the `-a` flag) should probably work; the right fix will be to use a loop/comprehension as in the `pretend` case.

**Comment by dosoe** [comment]
Thanks for your reply! However, I am dealing with 42000 items, so doing it itemwise is not possible, for albums on the other hand they are only 1700 so it is doable. Btw, do you have any idea how I could make my parentwork working (or merged, since it is working perfectly fine except the tests I don't know how to make).

**Comment by sampsyo** [comment]
The best thing would be to get others' opinions and ask them to help review the changes! It's on my list, but the more interest and help, the better.
