### ISSUE TITLE
fetchart crash

### ISSUE THREAD

**Issue by p3732** [beetbox/beets#2810]
### Problem
Upon importing an album downloaded from Bandcamp (https://ecovirtual.bandcamp.com/album/wildlife-canada) the fetchart plugin crashes. Importing other albums still works fine.

I shortened the lengthy output of the -vv option, full output is here:
[beets_fetchart_bug.txt](https://github.com/beetbox/beets/files/1718047/beets_fetchart_bug.txt)
[...]
Sending event: database_change
fetchart: trying source bandcamp for album Eco Virtual - WILDLIFE CANADA
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 937, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 914, in import_files
    session.run()
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 327, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 1506, in plugin_stage
    func(session, task)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/beetsplug/fetchart.py", line 794, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/lib/python3.6/site-packages/beetsplug/fetchart.py", line 861, in art_for_album
    source.fetch_image(candidate, self)
  File "/usr/lib/python3.6/site-packages/beetsplug/fetchart.py", line 230, in fetch_image
    with closing(self.request(candidate.url, stream=True,
AttributeError: 'str' object has no attribute 'url'

### Setup
Archlinux
Python 3.6.4
beets 1.6.4

My beet config is under https://github.com/p3732/various/blob/master/beets_config.yaml

**Comment by sampsyo** [comment]
Hi! It does seem like this crash is coming from the bandcamp plugin, which isn’t part of beets. Perhaps this bug needs to be reported there? https://github.com/unrblt/beets-bandcamp

**Comment by p3732** [comment]
Ok, then I misinterpreted the output. Thanks for providing the link :)
