### ISSUE TITLE
Instalation error on Windows 10.

### ISSUE THREAD

**Issue by JPereira89** [beetbox/beets#2892]
I am not able to install beets on Windows 10, Python 3.6.5.
Is there anything I can do to fix this?

This is what I get on the command line.

Thank you.

```
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. Todos os direitos reservados.

C:\Users\João>pip install beets
Collecting beets
  Using cached https://files.pythonhosted.org/packages/d5/44/caa90254c82b31acf5c85d22974cea7d8de405346c95add966a8f21e305b/beets-1.4.6.tar.gz
Requirement already satisfied: six>=1.9 in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: mutagen>=1.33 in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: munkres in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: unidecode in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: musicbrainzngs>=0.4 in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: pyyaml in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: jellyfish in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Requirement already satisfied: colorama in c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages (from beets)
Installing collected packages: beets
  Running setup.py install for beets ... error
Exception:
Traceback (most recent call last):
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 26: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 26: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] O processo não pode aceder ao ficheiro porque este está a ser utilizado por outro processo: 'C:\\Users\\JOO~3\\AppData\\Local\\Temp\\pip-build-dl3bybna\\beets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\joão\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] O processo não pode aceder ao ficheiro porque este está a ser utilizado por outro processo: 'C:\\Users\\JOO~3\\AppData\\Local\\Temp\\pip-build-dl3bybna\\beets'
```

**Comment by sampsyo** [comment]
Thanks! This thread suggests that this bug might be fixed in pip 10, which was recently released:
https://github.com/pypa/pip/issues/4251
