### ISSUE TITLE
Error: sqlite3.InterfaceError: Error binding parameter 25 - probably unsupported type

### ISSUE THREAD

**Issue by shimizurei** [beetbox/beets#2928]
### Problem
I am testing out some changes I made to the [VGMDB-beets](https://github.com/shimizurei/VGMdb-BeetsPlug/blob/testing/vgmdb.py) script and I ended up getting the following error: `sqlite3.InterfaceError: Error binding parameter 25 - probably unsupported type`. 

```
PS C:\Users\ORE-SAMA> beet -vv import C:\Users\ORE-SAMA\Downloads\Muzik\[TESTOO]
user configuration: C:\Users\ORE-SAMA\AppData\Roaming\beets\config.yaml
data directory: C:\Users\ORE-SAMA\AppData\Roaming\beets
plugin paths: C:\Users\ORE-SAMA\AppData\Roaming\beets\beetsplug
Sending event: pluginload
inline: adding item field multidisc
ImageMagick check `convert --version` failed: Command 'convert --version' returned non-zero exit status 4
artresizer: method is (1, (0,))
Querying VGMdb
lyrics: Disabling google source: no API key configured.
library database: C:\Users\ORE-SAMA\AppData\Roaming\beets\beets_musiclibrary.db
library directory: C:\Users\ORE-SAMA\Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: C:\Users\ORE-SAMA\Downloads\Muzik\[TESTOO]\[2017] Shingeki no Kiseki by Linked Horizon_PCCA-04539
Tagging Linked Horizon - Shingeki no Kiseki
No album ID found.
Search terms: Linked Horizon - Shingeki no Kiseki
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'shingeki no kiseki', 'tracks': u'14', 'artist': u'linked horizon'}
Requesting MusicBrainz release fac32ca3-ee09-4ec7-a80e-257627daf974
primary MB release type: single
Sending event: albuminfo_received
Candidate: Linked Horizon - Jiyuu e no Shingeki (fac32ca3-ee09-4ec7-a80e-257627daf974)
Computing track assignment...
...done.
Success. Distance: 0.63
Requesting MusicBrainz release 1aa45c49-fdf4-433f-a513-bb24faff1507
primary MB release type: single
Sending event: albuminfo_received
Candidate: Linked Horizon - Jiyuu e no Shingeki (1aa45c49-fdf4-433f-a513-bb24faff1507)
Computing track assignment...
...done.
Success. Distance: 0.64
Requesting MusicBrainz release a044848d-3918-4f3b-b689-5f3860c585a4
primary MB release type: album
Sending event: albuminfo_received
Candidate: Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í (a044848d-3918-4f3b-b689-5f3860c585a4)
Computing track assignment...
...done.
Success. Distance: 0.14
Requesting MusicBrainz release b0c8e581-7023-4e42-8e0c-4a7c7fa96532
primary MB release type: album
Sending event: albuminfo_received
Candidate: Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í (b0c8e581-7023-4e42-8e0c-4a7c7fa96532)
Computing track assignment...
...done.
Success. Distance: 0.13
Requesting MusicBrainz release 68742639-549f-4d1e-82bc-cce88690360d
primary MB release type: album
Sending event: albuminfo_received
Candidate: Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í (68742639-549f-4d1e-82bc-cce88690360d)
Computing track assignment...
...done.
Success. Distance: 0.13
Querying VGMdb for release 66622
Querying VGMdb for release 66623
get_albums Querying VGMdb for release Linked Horizon Shingeki no Kiseki
Sending event: albuminfo_received
Candidate: Linked Horizon - Shingeki no Kiseki / Linked Horizon [Limited Edition] (66622)
Computing track assignment...
...done.
Success. Distance: 0.36
Sending event: albuminfo_received
Candidate: Linked Horizon - Shingeki no Kiseki / Linked Horizon (66623)
Computing track assignment...
...done.
Success. Distance: 0.37
Evaluating 7 candidates.

C:\Users\ORE-SAMA\Downloads\Muzik\[TESTOO]\[2017] Shingeki no Kiseki by Linked Horizon_PCCA-04539 (14 items)
Sending event: before_choose_candidate
Correcting tags from:
    Linked Horizon - Shingeki no Kiseki
To:
    Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í
URL:
    https://musicbrainz.org/release/b0c8e581-7023-4e42-8e0c-4a7c7fa96532
(Similarity: 87.2%) (album, unmatched tracks, tracks) (Digital Media, 2017, JP, PONY CANYON)
 * µ£Çσ╛îπü«µêªµ₧£     -> µ£Çµ£ƒπü«µêªµ₧£ (title)
 * σ╜╝σÑ│πü»σå╖πüƒπüäµú║πü«Σ╕¡ -> σ╜╝σÑ│πü»σå╖πüƒπüäµú║πü«Σ╕¡πüº (title)
 * σ┐âΦçôπéÆµìºπüÆπéê∩╝ü   -> σ┐âΦçôπéÆµìºπüÆπéê!
Unmatched tracks (3):
 ! Track12 (#12) (1:25)
 ! Track13 (#13) (0:12)
 ! Θ¥ÆµÿÑπü»Φè▒τü½πü«πéêπüåπü½ (#14) (3:59)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? m
Finding tags for album "Linked Horizon - Shingeki no Kiseki".
Candidates:
1. Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í (87.2%) (album, unmatched tracks, tracks) (Digital Media, 2017, JP, PONY CANYON)
2. Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í (87.2%) (album, unmatched tracks, tracks) (CD, 2017, JP, PONY CANYON, ΘÇÜσ╕╕τ¢ñ)
3. Linked Horizon - ΘÇ▓µÆâπü«Φ╗îΦ╖í (85.9%) (tracks, album, missing tracks) (2xCD, 2017, JP, PONY CANYON)
4. Linked Horizon - Shingeki no Kiseki / Linked Horizon [Limited Edition] (63.9%) (tracks, source, album, ...) (VGMdb, 2xCD + Blu-ray, 2017, JP, Pony Canyon)
5. Linked Horizon - Shingeki no Kiseki / Linked Horizon (63.4%) (tracks, source, unmatched tracks, ...) (VGMdb, CD, 2017, JP, Pony Canyon)
6. Linked Horizon - Jiyuu e no Shingeki (36.7%) (unmatched tracks, tracks, album, ...) (Digital Media, 2013, US, PONY CANYON)
7. Linked Horizon - Jiyuu e no Shingeki (36.4%) (unmatched tracks, tracks, album, ...) (CD, 2013)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? 4
Correcting tags from:
    Linked Horizon - Shingeki no Kiseki
To:
    Linked Horizon - Shingeki no Kiseki / Linked Horizon [Limited Edition]
URL:
    https://vgmdb.net/album/66622?perpage=99999
(Similarity: 63.9%) (tracks, source, album, missing tracks) (VGMdb, 2xCD + Blu-ray, 2017, JP, Pony Canyon)
CD + Blu-ray 0
 * Σ║îπâ╢µ£êσ╛îπü«σÉ¢πü╕ (#1)    -> Nikagetsu-go no Kimi e (Σ║îπâ╢µ£êσ╛îπü«σÉ¢πü╕_An dich in zwei Monaten) (#0-0) (title)
 * τ┤àΦô«πü«σ╝ôτƒó (#2)      -> Guren no Yumiya (τ┤àΦô«πü«σ╝ôτƒó_Feuerroter Pfeil und Bogen) (#0-1) (title)
 * 14µûçσ¡ùπü«Σ╝¥Φ¿Ç (#3)    -> 14-moji no Dengon (14µûçσ¡ùπü«Σ╝¥Φ¿Ç_Ein Gebotschaft in vierzehn Zeichen) (#0-2) (title)
 * τ┤àΦô«πü«σ║ºµ¿Ö (#4)      -> Guren no Zahyou (τ┤àΦô«πü«σ║ºµ¿Ö_Feuerrotes Ziel) (#0-3) (title)
 * µ£Çσ╛îπü«µêªµ₧£ (#5)      -> Saigo no Senka (µ£Çµ£ƒπü«µêªµ₧£_Der letzte Erfolg) (#0-4) (title)
 * τÑ₧πü«σ╛íµÑ¡ (#6)       -> Kami no Miwaza (τÑ₧πü«σ╛íµÑ¡_Gottes Werk) (#0-5) (title)
 * Φç¬τö▒πü«τ┐╝ (#7)       -> Jiyuu no Tsubasa (Φç¬τö▒πü«τ┐╝_Die Fl├╝gel der Freiheit) (#0-6) (title)
 * σÅîτ┐╝πü«πâÆπé½πâ¬ (#8)     -> Souyoku no Hikari (σÅîτ┐╝πü«πâÆπé½πâ¬_Gefl├╝geltes Licht) (#0-7) (title)
 * Φç¬τö▒πü«Σ╗úσäƒ (#9)      -> Jiyuu no Daishou (Φç¬τö▒πü«Σ╗úσäƒ_Das Risiko der Freiheit) (#0-8) (title)
 * σ╜╝σÑ│πü»σå╖πüƒπüäµú║πü«Σ╕¡ (#10) -> Kanojo wa Tsumetai Hitsugi no Naka de (σ╜╝σÑ│πü»σå╖πüƒπüäµú║πü«Σ╕¡πüº_Sie liegt im kalten Sarg) (#0-9) (title)
 * σ┐âΦçôπéÆµìºπüÆπéê∩╝ü (#11)   -> Shinzou wo Sasageyo! (σ┐âΦçôπéÆµìºπüÆπéê!_Opfert eure Herzen!) (#0-10) (title)
 * Track12 (#12)   -> Guren no Tomoshibi wo Matoi Suiheisen no Kanata e to... (τ┤àΦô«πü«τü»πéÆτ║Åπüäµ░┤σ╣│τ╖Üπü«σ╜╝µû╣πü╕πü¿ΓÇª_[Secret Track]) (#0-11) (title)
 * Track13 (#13)   -> Dive into the Spin-off World!! (Dive into the Spin-off World!!_[Secret Track]) (#0-12) (title)
 * Θ¥ÆµÿÑπü»Φè▒τü½πü«πéêπüåπü½ (#14) -> Seishun wa Hanabi no you ni (Θ¥ÆµÿÑπü»Φè▒τü½πü«πéêπüåπü½_Die Jugend ist ein Feuerwerk) (#0-13) (title)
Missing tracks (1/15 - 6.7%):
 ! "Jiyuu no Daishou (Gekijouban Size)" (Φç¬τö▒πü«Σ╗úσäƒ [σèçσá┤τëêSize]_Das Risiko der Freiheit (Movie Size)) (#1-0)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? a
Sending event: import_task_choice
Sending event: import_task_apply
0 of 14 items replaced
Sending event: database_change
Sending event: database_change
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 937, in import_func
    import_files(lib, paths, query)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 914, in import_files
    session.run()
  File "c:\python27\lib\site-packages\beets\importer.py", line 327, in run
    pl.run_parallel(QUEUE_SIZE)
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "c:\python27\lib\site-packages\beets\importer.py", line 1415, in user_query
    apply_choice(session, task)
  File "c:\python27\lib\site-packages\beets\importer.py", line 1486, in apply_choice
    task.add(session.lib)
  File "c:\python27\lib\site-packages\beets\importer.py", line 751, in add
    self.album = lib.add_album(self.imported_items())
  File "c:\python27\lib\site-packages\beets\library.py", line 1324, in add_album
    item.add(self)
  File "c:\python27\lib\site-packages\beets\library.py", line 354, in add
    super(LibModel, self).add(lib)
  File "c:\python27\lib\site-packages\beets\dbcore\db.py", line 476, in add
    self.store()
  File "c:\python27\lib\site-packages\beets\library.py", line 346, in store
    super(LibModel, self).store(fields)
  File "c:\python27\lib\site-packages\beets\dbcore\db.py", line 405, in store
    tx.mutate(query, subvars)
  File "c:\python27\lib\site-packages\beets\dbcore\db.py", line 717, in mutate
    cursor = self.db._connection().execute(statement, subvals)
sqlite3.InterfaceError: Error binding parameter 25 - probably unsupported type.
```

### Setup

* OS: Win7x64
* Python version: 2.7.14
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): yes, VGMDB (but it didn't organize the tracks as a result)

My configuration (output of `beet config`) is:

```
### Global Options
directory: ~/Music
library: beets_musiclibrary.db

terminal_encoding: "utf-8" #'utf_8'?
# terminal_encoding: "cp65001"

## filename for the album art
art_filename: %asciify{cover_$album}
max_filename_length: 0 #unlimited
path_sep_replace: _
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

### General
threaded: yes
timeout: 5.0
verbose: 0

original_date: no
per_disc_numbering: yes

va_name: "Various Artists"
artist_credit: no
id3v23: yes

format_item: $artist - $album - $title
format_album: $albumartist - $album
time_format: '%Y-%m-%d %H:%M:%S'
format_raw_length: no

sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes

### Import Options
import:
    log: ~/beets-import.log
    write: yes
    copy: yes
    group_albums: no
    pretend: false
    search_ids: []
    duplicate_action: ask
    bell: no
    set_fields: {}
    autotag: yes
    timid: no #do not require confirmation on strong matches
    resume: ask
    incremental: no
    incremental_skip_later: no
    quiet_fallback: skip
    none_rec_action: ask
    default_action: apply
    singletons: no
    languages: [] #ISO 639-1 or ISO 639-2?
    detail: no
    flat: no

### Plugin Options
pluginpath: [
  ~\AppData\Roaming\beets\beetsplug,
]

plugins: [
  vgmdb,
  discogs,
  lyrics,
  embedart,
  fetchart,
  lastgenre,
  scrub,
  ftintitle,
  bucket,
  inline,
  the,
  badfiles,
  missing,
  info,
  duplicates
]

lyrics:
    auto: yes
    fallback: ''

lastgenre:
    fallback: ''
    source: artist

fetchart:
    auto: yes
    minwidth: 500
    maxwidth: 2000
    cautious: yes
    cover_names: cover cvr folder album
    sources: filesystem coverart amazon itunes albumart

embedart:
    auto: yes

scrub:
    auto: no

ftintitle:
    auto: yes

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

item_fields:
    multidisc: 1 if disctotal > 1 else 0

### Path options
bucket:
    bucket_alpha: ['0-9', 'A-D', 'E-H', 'I-L', 'M-P', 'Q-U', 'V-Z']

paths:
    ## A-D/Artist, The/[YEAR] Album Name, The/1-01. Track Name.mp3
    default: '%bucket{%upper{%left{%the{$albumartist},1}}}/%the{$albumartist}/[%if{$year,$year,0000}] $album %aunique{}/%if{$multidisc,$disc-}$track. $title'

    ## ZZ_NoAlbum/Artist, The - Track Name.mp3
    singleton: ZZ_NoAlbum/%%the{$artist}/$title


### UI Options
ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

### Auto Tagger
match:
    strong_rec_thresh: 0.04 #0.1, match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    required: []
    track_length_grace: 10
    track_length_max: 30
```

**Comment by sampsyo** [comment]
Please report problems with third-party plugins to the developers of those plugins.
