### ISSUE TITLE
Beets crashes when importing multiple albums

### ISSUE THREAD

**Issue by Matt07211** [beetbox/beets#2985]
### Beets crashes when importing multiple albums

When importing multiple albums , beets will crash with out "physically" copying the files but with the data entered into the database. Below is the most recent example, I normally don't do an import command more complex then the basic beet import, but this is the most recent example.

```sh
$ beet -vv import --set christmas=1  -s VA\ -\ Christmas\ Collection\ \[FLAC\]
user configuration: /home/matt07211/.config/beets/config.yaml
data directory: /home/matt07211/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding item field multidisc
inline: adding item field mediav
inline: adding item field mediav2
inline: adding item field ep
inline: adding item field single
inline: adding item field live
library database: /mnt/3TB-Drive-01/Audio/.musiclibrary.db
library directory: /mnt/3TB-Drive-01/Audio
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/A Winter's Tale - David Essex.flac
Item search terms: David Essex - A Winter's Tale
Sending event: import_task_created
...Repeated 126 times, trimmed for brevity...
Sending event: import_task_created
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.

Sending event: import_task_start
/mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/A Winter's Tale - David Essex.flac
Looking up: /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fideles (O Come All Ye Faithful) - Frank Sinatra.flac
Sending event: before_choose_candidate
Correcting track tags from:
Item search terms: Frank Sinatra - Adeste Fideles (O Come All Ye Faithful)
    David Essex - A Winter's Tale
Sending event: import_task_created
To:
    David Essex - A Winter’s Tale
URL:
    https://musicbrainz.org/recording/d4221d23-da37-4223-b483-fa6ee6bcc71f
(Similarity: 100.0%)
Sending event: import_task_choice
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_apply
0 of 1 items replaced
Sending event: database_change
Sending event: database_change
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.
Sending event: import_task_start
Looking up: /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fideles (O Come All Ye Faithful) - Il Divo.flac
Item search terms: Il Divo - Adeste Fideles (O Come All Ye Faithful)
Set field christmas=1 for /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/A Winter's Tale - David Essex.flac
Sending event: import_task_created
Sending event: database_change

/mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fideles (O Come All Ye Faithful) - Frank Sinatra.flac
Sending event: before_choose_candidate
Correcting track tags from:
    Frank Sinatra - Adeste Fideles (O Come All Ye Faithful)
To:
    Frank Sinatra - Adeste Fideles (O Come, All Ye Faithful)
URL:
    https://musicbrainz.org/recording/fc645754-b12b-4c37-a8d3-115541bf714a
(Similarity: 100.0%)
Sending event: import_task_choice
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.
Sending event: import_task_apply
Sending event: import_task_start
Looking up: /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fidelis - Connie Francis.flac
Item search terms: Connie Francis - Adeste Fidelis
0 of 1 items replaced
Sending event: import_task_created
Sending event: database_change
Sending event: database_change
Set field christmas=1 for /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fideles (O Come All Ye Faithful) - Frank Sinatra.flac
lastgenre: added last.fm item genre (artist): Pop, Rock, Glam Rock, Classic Rock, Oldies
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.
Sending event: import_task_start
Looking up: /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/After New Year's Eve - Heartbeats.flac
Item search terms: Heartbeats - After New Year's Eve
Sending event: database_change

/mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fideles (O Come All Ye Faithful) - Il Divo.flac
Sending event: before_choose_candidate
Correcting track tags from:
    Il Divo - Adeste Fideles (O Come All Ye Faithful)
To:
    Il Divo - Adeste fideles (O Come All Ye Faithful)
URL:
    https://musicbrainz.org/recording/0106030f-aca0-4b1e-83a2-a8749899630e
(Similarity: 100.0%)
Sending event: import_task_choice
Sending event: database_change
Sending event: import_task_created
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.
Sending event: database_change
Sending event: import_task_start
Looking up: /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/All I Want For Christmas - Samantha Mumba.flac
Item search terms: Samantha Mumba - All I Want For Christmas
Sending event: import_task_created
Sending event: import_task_apply
0 of 1 items replaced
Sending event: database_change
Sending event: database_change
lastgenre: added last.fm item genre (artist): Jazz, Swing, Oldies, Vocal Jazz, Easy Listening
Set field christmas=1 for /mnt/3TB-Drive-01/Audio/Download/Music/VA - Christmas Collection [FLAC]/Adeste Fideles (O Come All Ye Faithful) - Il Divo.flac
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.
Sending event: database_change
Sending event: database_change
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/lib/python2.7/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 943, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python2.7/site-packages/beets/ui/commands.py", line 913, in import_files
    session.run()
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/lib/python2.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/lib/python2.7/site-packages/beets/importer.py", line 1511, in plugin_stage
    func(session, task)
  File "/usr/lib/python2.7/site-packages/beets/plugins.py", line 134, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError
```
This happens on plain old .flac files or a compressed archive.

### Setup

* OS: Solus
* Python version: Python 2.7.15
* beets version: 1.4.7 (This problem was also happening on 1.4.6)
* Turning off plugins made problem go away (yes/no):  Have yet to try, will have to wait till morning to test.

My configuration (output of `beet config`) is:

```yaml
############################################################################
## Beets Configuration file.
## ~./config/beets/config.yaml
#############################################################################

### Global Options
library: /mnt/3TB-Drive-01/Audio/.musiclibrary.db
directory: /mnt/3TB-Drive-01/Audio/
plugins:
    # Autotagger Extensions
    - fromfilename
    # Metadata Plugins
    - edit
    - fetchart
    - embedart
    - ftintitle
    - lastgenre
    # Path Format Plugins
    - inline
    # Interoperability
    - badfiles
    - play
    # Miscellaneous Plugins
    - convert
    - duplicates
    - export
    - fuzzy
    - info
    - missing
    - random
    - web
    # Other/External Plugins
    - copyartifacts
    - check

per_disc_numbering: true

# General Configuration
ui:
    color: yes

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    log: /mnt/3TB-Drive-01/Audio/.beet.log
    bell: yes

# Done in order listed. Default is special and will always go at the end.
# e.g. If I had an album with the albumtype $soundtrack and $compilation
# Then the path that matchs first takes precedence.
paths:
    default: Music/$albumartist/($year) $album%aunique{,media mastering label catalognum albumdisambig}%if{$ep,%upper{ [$albumtype]}}%if{$single,%title{ [$albumtype]}}%if{$live,%title{ [$albumtype]}} %if{$mediav,[Vinyl]}%if{$mediav2,[Vinyl]}/%if{$multidisc,Disc $disc/}$track. $title
    albumtype:soundtrack: Music/Original Sound Tracks (OST)/$album%aunique{,media mastering label catalognum albumdisambig} ($year) %if{$mediav,[Vinyl]}%if{$mediav2,[Vinyl]}/%if{$multidisc,Disc $disc/}$track. %if{$multiartist,$artist -} $title
    singleton: Music/Non-Album/$artist/$title
    comp: Music/Compilations/$album%aunique{,media mastering label catalognum albumdisambig} ($year) %if{$mediav,[Vinyl]}%if{$mediav2,[Vinyl]}/%if{$multidisc,Disc $disc/}$track. $artist - $title
    christmas:1: Christmas Music Collection/$artist ($year) - $title
    albumtype:other: Other/$albumartist/$album%aunique{,media mastering label catalognum albumdisambig} %if{$ep,%upper{[$albumtype]}}%if{$single,%title{[$albumtype]}}%if{$live,%title{[$albumtype]}} %if{$mediav,[Vinyl]}%if{$mediav2,[Vinyl]}($year)/%if{$multidisc,Disc $disc/}$track. $title
    albumtype:audiobook: Audiobooks/$artist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track. $title


# Plugin Configurations
fetchart:
    store_source: yes

embedart:
    # I dont want album art auto-embedded
    auto: no

convert:
# auto: yes
    copy_album_art: yes
    album_art_maxwidth: 600
    dest: /mnt/3TB-Drive-01/Audio/Music [Mobile version]/
    embed: yes
    never_convert_lossy_files: yes
    format: opus
    formats:
        opus:
            command: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
            extension: opus.ogg
            # Above is to work around android media scanner, opus is included 
            # in the file extension for making it easier on me in the future
            # when android media scanner picks up opus extensions properly

copyartifacts:
    extensions: .cue .CUE .log .LOG .jpg .jpeg .png .accurip
    print_ignored: yes

lastgenre:
    count: 5

item_fields:
    multidisc: 1 if disctotal > 1 else 0
    mediav: 1 if media == '12" Vinyl' else 0
    mediav2: 1 if media == 'Vinyl' else 0
# multiartist: 1 if albumartist =='Various Artists' else 0
    ep: 1 if albumtype == 'ep' else 0
    single: 1 if albumtype == 'single' else 0
    live: 1 if albumtype == 'live' else 0

play:
    command: /usr/bin/deadbeef```

**Comment by sampsyo** [comment]
Hello!

> Turning off plugins made problem go away (yes/no): Have yet to try, will have to wait till morning to test.

Please try disabling the external plugins you're using (copyartifacts and check, it looks like). We've had similar reports of bugs in these plugins.

**Comment by Matt07211** [comment]
Seems like "check" is the culprit, guess that what I get for not doing enough testing late at night, I'll close this issue and see if a relevant issue has been posted to the check GitHub page.
