### ISSUE TITLE
Traceback: ImportError: cannot import name zip_longest

### ISSUE THREAD

**Issue by brianjcohen** [beetbox/beets#3148]
### Problem

Anytime I invoke 'beet' from the command line, with or with any arguments, I receive the following backtrace:

beet
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/__init__.py", line 25, in <module>
    from .hooks import AlbumInfo, TrackInfo, AlbumMatch, TrackMatch  # noqa
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/hooks.py", line 28, in <module>
    from jellyfish import levenshtein_distance
  File "/usr/local/lib/python2.7/dist-packages/jellyfish/__init__.py", line 5, in <module>
    from ._jellyfish import *   # noqa
  File "/usr/local/lib/python2.7/dist-packages/jellyfish/_jellyfish.py", line 3, in <module>
    from itertools import zip_longest
ImportError: cannot import name zip_longest

### Setup

* OS: Ubuntu Linux 14.04.5
* Python version: 2.7.6
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is: the same traceback

**Comment by jackwilsdon** [comment]
This should be fixed by #3112, although it hasn't been merged yet it seems.

**Comment by sampsyo** [comment]
Thanks for the heads up! I merged that (with a refinement).

**Comment by brianjcohen** [comment]
When would we expect this to be available via pip install --upgrade ?
