### ISSUE TITLE
BadFiles plugin crashes beets with latest git master

### ISSUE THREAD

**Issue by Holzhaus** [beetbox/beets#3158]
### Problem

If the `badfiles` plugin is activated, beets crashes when starting an import task.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import --write /data/music
user configuration: /home/jan/.config/beets/config.yaml
data directory: /home/jan/.config/beets
plugin paths:
Sending event: pluginload
artresizer: method is (2, (7, 0, 8))
lyrics: Disabling google source: no API key configured.
library database: /home/jan/beets.db
library directory: /data/music
Sending event: library_opened
Traceback (most recent call last):
  File "/home/jan/.local/bin/beet", line 11, in <module>
    load_entry_point('beets', 'console_scripts', 'beet')()
  File "/data/jan/Projects/beets/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/data/jan/Projects/beets/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/data/jan/Projects/beets/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/data/jan/Projects/beets/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/data/jan/Projects/beets/beets/importer.py", line 316, in run
    for stage_func in plugins.early_import_stages():
  File "/data/jan/Projects/beets/beets/plugins.py", line 426, in early_import_stages
    stages += plugin.get_early_import_stages()
  File "/data/jan/Projects/beets/beets/plugins.py", line 112, in get_early_import_stages
    return self._set_stage_log_level(self.early_import_stages)
AttributeError: 'BadFiles' object has no attribute 'early_import_stages'
```

### Setup

* OS: Arch Linux
* Python version: 3.7.2
* beets version: be118b92
* Turning off plugins made problem go away (yes/no): Yes (Disabling the `badfiles` plugin suffices)

My configuration (output of `beet config`) is: https://gist.github.com/Holzhaus/500b790c06fe2250ac9182bd8a6760da

**Comment by Holzhaus** [comment]
Fix proposed in PR #3159.
