### ISSUE TITLE
Temp .opus file "not in a recognized format" when converting

### ISSUE THREAD

**Issue by soadroxs** [beetbox/beets#3174]
### Problem

When importing a FLAC album into beets, with convert set to automatically convert into the opus format, I get this error.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import "Conan Osíris"
```

Led to this problem:

```
Traceback (most recent call last):
  File "/home/chris/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/chris/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/chris/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/home/chris/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/home/chris/.local/lib/python2.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/chris/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/chris/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/home/chris/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/home/chris/.local/lib/python2.7/site-packages/beets/importer.py", line 1511, in plugin_stage
    func(session, task)
  File "/home/chris/.local/lib/python2.7/site-packages/beets/plugins.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/beetsplug/convert.py", line 177, in auto_convert
    self.convert_on_import(config.lib, item)
  File "/home/chris/.local/lib/python2.7/site-packages/beetsplug/convert.py", line 486, in convert_on_import
    item.write()
  File "/home/chris/.local/lib/python2.7/site-packages/beets/library.py", line 651, in write
    raise ReadError(path, exc)
ReadError: error reading /tmp/tmpvxnkQL.opus: '/tmp/tmpvxnkQL.opus': not in a recognized format

error reading /tmp/tmpvxnkQL.opus: '/tmp/tmpvxnkQL.opus': not in a recognized format

```

Here's a link to the music files that trigger the bug (if relevant): 

### Setup

* OS: Xubuntu 18.04.1
* Python version: Python 2.7.15rc1
* beets version: Beets 1.4.8 (from source)
* Turning off plugins made problem go away (yes/no): Yes, but does not convert automatically as I wanted to

My configuration (output of `beet config`) is:

```yaml
directory: /media/chris/F2F6FCDBF6FCA0D1/Users/Chris/Music

original_date: yes

plugins: the ftintitle inline convert fetchart

paths:
    default: %the{$mainartist}/$year - $album/$disc.$track - $title
    
ui:
    color: no

import:
    write: yes
    move: yes

ftintitle:
    drop: yes

the: 
    a: no

convert:
    auto: yes 
    command: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
    extension: opus
    never_convert_lossy_files: yes

item_fields:
    mainartist: albumartist.split(";")[0].strip()

fetchart:
    cautious: true
    maxwidth: 800
    covernames: front
```

**Comment by soadroxs** [comment]
Fixed by installing ffmpeg from PPA and not from Snap.
