### ISSUE TITLE
Beatport plugin does not handle

### ISSUE THREAD

**Issue by tima** [beetbox/beets#318]
I have a number of Beatport tracks in my music collection that I was pleased to see a plugin added for accessing their metadata. I'm seeing a problem with it though. Doing a quiet import (I'm new to using beets) I got this error:

beet import -ql ~/beets/quiet-import.log /Volumes/TB3/iTunes/Music/

```
Traceback (most recent call last):
  File "/usr/local/share/python/beet", line 9, in <module>
    load_entry_point('beets==1.2.0', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 771, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 763, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/commands.py", line 828, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/commands.py", line 766, in import_files
    session.run()
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 337, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/site-packages/beets/util/pipeline.py", line 243, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/site-packages/beets/importer.py", line 646, in initial_lookup
    *autotag.tag_album(task.items)
  File "/usr/local/lib/python2.7/site-packages/beets/autotag/match.py", line 515, in tag_album
    search_album, va_likely)
  File "/usr/local/lib/python2.7/site-packages/beets/autotag/hooks.py", line 223, in album_candidates
    out.extend(plugins.candidates(items, artist, album, va_likely))
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 270, in candidates
    out.extend(plugin.candidates(items, artist, album, va_likely))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/beatport.py", line 188, in candidates
    return self._get_releases(query)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/beatport.py", line 240, in _get_releases
    for x in BeatportSearch(query).results]
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/beatport.py", line 86, in __init__
    release.get_tracks()
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/beatport.py", line 124, in get_tracks
    self.tracks = [BeatportTrack(x) for x in response['tracks']]
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beetsplug/beatport.py", line 142, in __init__
    self.length = timedelta(milliseconds=data['lengthMs'])
TypeError: unsupported type for timedelta milliseconds component: NoneType
```

Besides handling a none value more carefully here, it seems like beets really needs to contain failing plugin better. This stopped my import cold and doesn't give me the option to resume my import when I try again.

**Comment by brianroach** [comment]
Is there still a beatport plugin?

**Comment by sampsyo** [comment]
Sadly, no; they shut down their API. 😐

**Comment by brianroach** [comment]
@sampsyo I created a new issue about this yesterday, because it appears their API is back online for non-commercial use. See #1989
