### ISSUE TITLE
Running beets on my machine (macOS 10.11) fails with a syntax error.

### ISSUE THREAD

**Issue by miketoth** [beetbox/beets#3185]
### Problem

Running beets on my machine (macOS 10.11) fails with a syntax error.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
```

Led to this problem:

```
Traceback (most recent call last):
  File "/Users/name/Library/Python/2.7/bin/beet", line 7, in <module>
    from beets.ui import main
  File "/Users/name/Library/Python/2.7/lib/python/site-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/Users/name/Library/Python/2.7/lib/python/site-packages/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album, Proposal  # noqa
  File "/Users/name/Library/Python/2.7/lib/python/site-packages/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/usr/local/lib/python2.7/site-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:
                               ^
SyntaxError: invalid syntax
```

Here's a link to the music files that trigger the bug (if relevant):  n/a

### Setup

* OS: macOS 10.11.16
* Python version: 2.7.15
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
Traceback (most recent call last):
  File "/Users/name/Library/Python/2.7/bin/beet", line 7, in <module>
    from beets.ui import main
  File "/Users/name/Library/Python/2.7/lib/python/site-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/Users/name/Library/Python/2.7/lib/python/site-packages/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album, Proposal  # noqa
  File "/Users/name/Library/Python/2.7/lib/python/site-packages/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/usr/local/lib/python2.7/site-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:
                               ^
SyntaxError: invalid syntax
```

**Comment by sampsyo** [comment]
This was addressed in #3146 and subsequently #3169. Please either run the latest source or use Python 3.
