### ISSUE TITLE
Cannot log dict from BeetsLogger

### ISSUE THREAD

**Issue by temrix** [beetbox/beets#3188]
### Problem

When developing a plugin, trying to log a dict from an instance `plugin_obj._log` of `beets.plugins.BeetsPlugin` leads to an `AttributeError`. However, just printing the dict works fine.

What I did: I have a dict which I would like to log by `plugin_obj._log`.

For example, in this code, `self._log.info(my_dict)` leads to an `AttributeError`:

```python3
class MyPlugin(BeetsPlugin):
    def __init__(self):
        super(MyPlugin, self).__init__()

    def commands(self):
        cmd = ui.Subcommand('test')

        def func(lib, opts, args):
            my_dict = {'spam': 'eggs'}
            # print(my_dict)
            self._log.info(my_dict)

        cmd.func = func
        return [cmd]
```

Led to this problem:

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/temrix/pypy/lib-python/3/logging/__init__.py", line 986, in emit
    msg = self.format(record)
  File "/home/temrix/pypy/lib-python/3/logging/__init__.py", line 836, in format
    return fmt.format(record)
  File "/home/temrix/pypy/lib-python/3/logging/__init__.py", line 573, in format
    record.message = record.getMessage()
  File "/home/temrix/pypy/lib-python/3/logging/__init__.py", line 334, in getMessage
    msg = str(self.msg)
  File "/home/temrix/pypy/site-packages/beets/logging.py", line 86, in __str__
    return self.msg.format(*args, **kwargs)
AttributeError: 'dict' object has no attribute 'format'
Call stack:
  File "/home/temrix/pypy/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/home/temrix/pypy/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/home/temrix/pypy/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/temrix/beetsplug/myplugin.py", line 32, in func
    self._log.info(my_dict)
  File "/home/temrix/pypy/lib-python/3/logging/__init__.py", line 1285, in info
    self._log(INFO, msg, args, **kwargs)
  File "/home/temrix/pypy/site-packages/beets/logging.py", line 91, in _log
    return super(StrFormatLogger, self)._log(level, m, (), exc_info, extra)
Message: <beets.logging.StrFormatLogger._LogMessage object at 0x00007fb52be8e800>
Arguments: ()
```

### Setup

* OS: Debian
* Python version: 3.5.3
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
directory: ~/music
library: ~/Dokumente/musiclibrary.db

import:
    copy: no
    write: no

ui:
    color: yes

plugins: myplugin
```

**Comment by sampsyo** [comment]
Hi! Indeed; maybe we should convert all arguments there to strings. But the intended way to invoke the logging functions is with a template string—if you don't need anything surrounding the value you want to print, you can use the trivial template `'{0}'`. Like so:

```py
self._log.info(u'{0}', my_dict)
```

**Comment by temrix** [comment]
Aha, and I was trying to do this:

```python3
self._log.info({0}.format(my_dict))
```

Thank you for clarification, it now works.

I leave the ticket open in case you want to change the functionality as you said but it indeed is clearly outlined in the documentation.

**Comment by sampsyo** [comment]
Cool! I think I'll close this, because automatically string-converting the first argument might open up unpredictability that would have its own downsides. For example, I find this behavior in the default logging module pretty surprising:

```py
>>> import logging
>>> logging.warning({'foo': '%s'}, 'bar')
WARNING:root:{'foo': 'bar'}
```
