### ISSUE TITLE
Debian 9: Installed from package / pip, get traceback error running any beet command, ex. beet -p

### ISSUE THREAD

**Issue by abclution** [beetbox/beets#3213]
Not sure what is happening, tried to find something relevant in search but coming up dry.

beet -p
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.3.19', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/beets/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/usr/share/beets/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album  # noqa
  File "/usr/share/beets/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/usr/local/lib/python2.7/dist-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:
                               ^
SyntaxError: invalid syntax

and with the pip version

➜  AUDIO /usr/local/bin/beet -p
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 7, in <module>
    from beets.ui import main
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album, Proposal  # noqa
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/usr/local/lib/python2.7/dist-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:
                               ^
SyntaxError: invalid syntax

**Comment by sampsyo** [comment]
Please see #3154.
