### ISSUE TITLE
Synology NAS: cannot concatenate 'str' and 'int' objects using fetchart plugin with Fanart.tv

### ISSUE THREAD

**Issue by musiczetetic** [beetbox/beets#3303]
### Problem

Running the import command gives an error on only some albums:

TypeError: cannot concatenate 'str' and 'int' objects

Then import stops

This only started after I updated beets, I cannot remember the version I was on before, it was about 2 years old.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import -t /volume1/Audio/Organising/XXXXXnewFORdukereplace/
```

Led to this problem:

```
user configuration: /root/.config/beets/config.yaml
data directory: /root/.config/beets
plugin paths:
Sending event: pluginload
library database: /volume1/Documents/BeetsDB/DukeboxBeeten.blb
library directory: /volume1/Audio/BeetifiedMusic/BeetenDiscoggedReplacements
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face
Tagging Garfunkel and Oates - All Over Your Face
Searching for discovered album ID: 7504a4b7-cf20-38fa-aad6-69173ad89601
Requesting MusicBrainz release 7504a4b7-cf20-38fa-aad6-69173ad89601
primary MB release type: album
Sending event: albuminfo_received
Candidate: Garfunkel and Oates - All Over Your Face (7504a4b7-cf20-38fa-aad6-69173ad89601)
Computing track assignment...
...done.
Success. Distance: 0.00
Album ID match recommendation is Recommendation.strong
Search terms: Garfunkel and Oates - All Over Your Face
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'all over your face', 'tracks': u'10', 'artist': u'garfunkel and oates'}
Requesting MusicBrainz release 7504a4b7-cf20-38fa-aad6-69173ad89601
Sending event: import_task_created
primary MB release type: album
Sending event: albuminfo_received
Candidate: Garfunkel and Oates - All Over Your Face (7504a4b7-cf20-38fa-aad6-69173ad89601)
Duplicate.
Sending event: import_task_created
Sending event: import_task_created
discogs: Searching for master release 511640
Sending event: import_task_created
Sending event: import_task_created
discogs: Searching for master release 511640
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
discogs: Searching for master release 643473
Sending event: import_task_created
Sending event: import_task_created
discogs: Searching for master release 643473
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: albuminfo_received
Candidate: Garfunkel And Oates - All Over Your Face (3752073)
Computing track assignment...
...done.
Success. Distance: 0.43
Sending event: albuminfo_received
Candidate: Garfunkel And Oates - All Over Your Face (3465886)
Computing track assignment...
...done.
Success. Distance: 0.47
Sending event: albuminfo_received
Candidate: Girl Talk - All Day (2557241)
Computing track assignment...
...done.
Success. Distance: 0.82
Sending event: albuminfo_received
Candidate: Girl Talk - All Day (5300857)
Computing track assignment...
...done.
Success. Distance: 0.81
Sending event: albuminfo_received
Candidate: Various Artists - All Time Classics - Tearjerkers (8795219)
Sending event: import_task_created
Computing track assignment...
...done.
Success. Distance: 0.89
Evaluating 6 candidates.
Sending event: import_task_start

/volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face (10 items)
Looking up: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist
Sending event: before_choose_candidate
Tagging:
    Garfunkel and Oates - All Over Your Face
URL:
    https://musicbrainz.org/release/7504a4b7-cf20-38fa-aad6-69173ad89601
(Similarity: 100.0%) (CD, 2011, US)
Tagging Garfunkel and Oates - Slippery When Moist
Searching for discovered album ID: 190aaf75-54dd-4f05-a953-98357c34d835
Requesting MusicBrainz release 190aaf75-54dd-4f05-a953-98357c34d835
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? Sending event: import_task_created
primary MB release type: album
Sending event: albuminfo_received
Candidate: Garfunkel and Oates - Slippery When Moist (190aaf75-54dd-4f05-a953-98357c34d835)
Computing track assignment...
...done.
Success. Distance: 0.00
Album ID match recommendation is Recommendation.strong
Search terms: Garfunkel and Oates - Slippery When Moist
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'slippery when moist', 'tracks': u'13', 'artist': u'garfunkel and oates'}
Sending event: import_task_created
Requesting MusicBrainz release 9fcd65a9-90cd-4da9-a7ef-307e6a95eaf9
Sending event: import_task_created
primary MB release type: album
Sending event: albuminfo_received
Candidate: Garfunkel and Oates - Slippery When Moist (9fcd65a9-90cd-4da9-a7ef-307e6a95eaf9)
Computing track assignment...
Sending event: import_task_created
...done.
Success. Distance: 0.15
Sending event: import_task_created
Sending event: import_task_created
discogs: Searching for master release 511639
Sending event: import_task_created
Sending event: import_task_created
discogs: Searching for master release 511639
Sending event: import_task_created
Sending event: import_task_created
mSending event: albuminfo_received
Candidate: Garfunkel And Oates - Slippery When Moist (3752087)

Finding tags for album "Garfunkel and Oates - All Over Your Face".
Candidates:
1. Garfunkel and Oates - All Over Your Face (100.0%) (CD, 2011, US)
2. Garfunkel And Oates - All Over Your Face (56.8%) (tracks, id, source) (Discogs, CD, 2011, US, Not On Label)
3. Garfunkel And Oates - All Over Your Face (53.1%) (tracks, id, source, ...) (Discogs, File, 2011, Unknown, No One Buys Records)
4. Girl Talk - All Day (19.0%) (unmatched tracks, id, artist, ...) (Discogs, File, 2010, US, Illegal Art)
5. Girl Talk - All Day (17.7%) (tracks, id, artist, ...) (Discogs, File, 2010, US, Illegal Art)
6. Various Artists - All Time Classics - Tearjerkers (11.1%) (missing tracks, tracks, id, ...) (Discogs, 2xCD, 2002, UK, Warner Music UK Ltd.)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? Computing track assignment...
...done.
Success. Distance: 0.43
Sending event: albuminfo_received
Candidate: Garfunkel And Oates - Slippery When Moist (3465968)
Sending event: import_task_created
Computing track assignment...
...done.
Success. Distance: 0.47
Evaluating 4 candidates.
Sending event: import_task_start
Looking up: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2013 - Czarface
Tagging Czarface - Czarface
No album ID found.
Search terms: Czarface - Czarface
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'czarface', 'tracks': u'14', 'artist': u'czarface'}
Sending event: import_task_created
Requesting MusicBrainz release d37e821d-876e-48eb-8a9d-c63518453e5a
3
Correcting tags from:
    Garfunkel and Oates - All Over Your Face
To:
    Garfunkel And Oates - All Over Your Face
URL:
    https://www.discogs.com/Garfunkel-And-Oates-All-Over-Your-Face/release/3465886
(Similarity: 53.1%) (tracks, id, source, media, country) (Discogs, File, 2011, Unknown, No One Buys Records)
 * You, Me and Steve ->
   You, Me And Steve (id)
 * Weed Card ->
   Weed Card (id)
 * Pregnant Women Are Smug ->
   Pregnant Women Are Smug (id)
 * Gay Boyfriend ->
   Gay Boyfriend (id)
 * Fuck You ->
   Fuck You (id)
 * Sex With Ducks ->
   Sex With Ducks (id)
 * This Party Took a Turn for the Douche ->
   This Party Took A Turn For The Douche (id)
 * Running With Chicken ->
   Running With Chicken (id)
 * One Night Stand ->
   One Night Stand (id)
 * Places to Rest ->
   Places To Rest (id)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? Sending event: import_task_created
Sending event: import_task_created
primary MB release type: album
Sending event: albuminfo_received
Candidate: Czarface - CZARFACE (d37e821d-876e-48eb-8a9d-c63518453e5a)
Computing track assignment...
a...done.
Success. Distance: 0.10

Sending event: import_task_choice
Sending event: import_task_apply
Sending event: import_task_created
discogs: Searching for master release 525234
discogs: Searching for master release 525234
Replacing item 70936: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-01 Garfunkel and Oates - You, Me and Steve.mp3
Sending event: database_change
Sending event: import_task_created
Sending event: item_removed
Replacing item 70944: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-05 Garfunkel and Oates - Fuck You.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70935: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-09 Garfunkel and Oates - One Night Stand.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70942: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-08 Garfunkel and Oates - Running With Chicken.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70943: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-04 Garfunkel and Oates - Gay Boyfriend.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70940: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-07 Garfunkel and Oates - This Party Took a Turn for the Douche.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70938: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-06 Garfunkel and Oates - Sex With Ducks.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70937: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-03 Garfunkel and Oates - Pregnant Women Are Smug.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70941: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-10 Garfunkel and Oates - Places to Rest.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70939: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-02 Garfunkel and Oates - Weed Card.mp3
Sending event: database_change
discogs: Searching for master release 525234
Sending event: database_change
Sending event: item_removed
10 of 10 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_created
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1551426560.81, flexible attributes [] from album 5865 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face
Reimported item added 1551426561.08 from item 70936 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-01 Garfunkel and Oates - You, Me and Steve.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70936 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-01 Garfunkel and Oates - You, Me and Steve.mp3
Sending event: database_change
Reimported item added 1551426561.09 from item 70944 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-05 Garfunkel and Oates - Fuck You.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70944 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-05 Garfunkel and Oates - Fuck You.mp3
Sending event: database_change
Reimported item added 1551426561.07 from item 70935 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-09 Garfunkel and Oates - One Night Stand.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70935 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-09 Garfunkel and Oates - One Night Stand.mp3
Sending event: database_change
Reimported item added 1551426561.04 from item 70942 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-08 Garfunkel and Oates - Running With Chicken.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70942 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-08 Garfunkel and Oates - Running With Chicken.mp3
Sending event: database_change
Reimported item added 1551426561.02 from item 70943 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-04 Garfunkel and Oates - Gay Boyfriend.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70943 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-04 Garfunkel and Oates - Gay Boyfriend.mp3
Sending event: database_change
Reimported item added 1551426561.05 from item 70940 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-07 Garfunkel and Oates - This Party Took a Turn for the Douche.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70940 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-07 Garfunkel and Oates - This Party Took a Turn for the Douche.mp3
Sending event: database_change
Reimported item added 1551426561.1 from item 70938 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-06 Garfunkel and Oates - Sex With Ducks.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70938 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-06 Garfunkel and Oates - Sex With Ducks.mp3
Sending event: database_change
Reimported item added 1551426561.1 from item 70937 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-03 Garfunkel and Oates - Pregnant Women Are Smug.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70937 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-03 Garfunkel and Oates - Pregnant Women Are Smug.mp3
Sending event: database_change
Reimported item added 1551426561.06 from item 70941 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-10 Garfunkel and Oates - Places to Rest.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70941 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-10 Garfunkel and Oates - Places to Rest.mp3
Sending event: database_change
Reimported item added 1551426561.11 from item 70939 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-02 Garfunkel and Oates - Weed Card.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70939 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2011 - All Over Your Face/01-02 Garfunkel and Oates - Weed Card.mp3
Sending event: database_change

fetchart: trying source filesystem for album Garfunkel And Oates - All Over Your Face
/volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist (13 items)
fetchart: trying source fanarttv for album Garfunkel And Oates - All Over Your Face
Sending event: before_choose_candidate
Tagging:
    Garfunkel and Oates - Slippery When Moist
URL:
    https://musicbrainz.org/release/190aaf75-54dd-4f05-a953-98357c34d835
(Similarity: 100.0%) (CD, 2012, US)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? discogs: Searching for master release 525234
Sending event: import_task_created
discogs: Searching for master release 525234
Sending event: albuminfo_received
Candidate: Czarface - Czarface (4295837)
Computing track assignment...
...done.
Success. Distance: 0.16
Sending event: albuminfo_received
Candidate: Czarface - Czarface (4707533)
Computing track assignment...
...done.
Success. Distance: 0.16
Sending event: albuminfo_received
Candidate: Czarface - Czarface (5207900)
Computing track assignment...
...done.
Success. Distance: 0.16
Sending event: albuminfo_received
Candidate: Czarface - Czarface (4316701)
Computing track assignment...
...done.
Success. Distance: 0.14
Sending event: albuminfo_received
Candidate: Czarface - Czarface  (7435343)
Computing track assignment...
...done.
Success. Distance: 0.16
Evaluating 6 candidates.
m
Finding tags for album "Garfunkel and Oates - Slippery When Moist".
Candidates:
1. Garfunkel and Oates - Slippery When Moist (100.0%) (CD, 2012, US)
2. Garfunkel and Oates - Slippery When Moist (85.2%) (id, media) (Digital Media, 2012, US, No One Buys Records)
3. Garfunkel And Oates - Slippery When Moist (56.7%) (tracks, id, source) (Discogs, CD, 2012, US, Not On Label)
4. Garfunkel And Oates - Slippery When Moist (53.3%) (tracks, id, source, ...) (Discogs, File, 2012, Unknown, No One Buys Records)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? 3
Correcting tags from:
    Garfunkel and Oates - Slippery When Moist
To:
    Garfunkel And Oates - Slippery When Moist
URL:
    https://www.discogs.com/Garfunkel-And-Oates-Slippery-When-Moist/release/3752087
(Similarity: 56.7%) (tracks, id, source) (Discogs, CD, 2012, US, Not On Label)
 * Wow ->
   Wow (id)
 * Go Kart Racing ->
   Go Kart Racing (id)
 * I Don’t Know Who You Are ->
   I Don’t Know Who You Are (id)
 * Handjob, Blandjob, I Don’t Understand Job ->
   Handjob, Blandjob, I Don’t Understand Job (id)
 * Save the Rich ->
   Save The Rich (id)
 * Hey Girl in the Moonlight ->
   Hey Girl In The Moonlight (id)
 * The Ex‐Boyfriend Song ->
   The Ex-Boyfriend Song (id)
 * Silver Lining ->
   Silver Lining (id)
 * I Would Never (Have Sex with You) ->
   I Would Never (Have Sex With You) (id)
 * Google ->
   Google (id)
 * I Would Never (Dissect a Ewe) ->
   I Would Never (Dissect A Ewe) (id)
 * My Apartment’s Very Clean Without You ->
   My Apartment’s Very Clean Without You (id)
 * Go ->
   Go (id)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? a
Sending event: import_task_choice
Sending event: import_task_apply
Replacing item 70950: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-03 Garfunkel and Oates - I Don't Know Who You Are.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70945: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-13 Garfunkel and Oates - Go.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70951: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-10 Garfunkel and Oates - Google.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70956: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-04 Garfunkel and Oates - Handjob, Blandjob, I Don't Understand Job.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70946: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-06 Garfunkel and Oates - Hey Girl in the Moonlight.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70952: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-07 Garfunkel and Oates - The Ex-Boyfriend Song.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70955: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-11 Garfunkel and Oates - I Would Never (Dissect a Ewe).mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70949: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-01 Garfunkel and Oates - Wow.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70953: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-05 Garfunkel and Oates - Save the Rich.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70954: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-12 Garfunkel and Oates - My Apartment's Very Clean Without You.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70947: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-08 Garfunkel and Oates - Silver Lining.mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70948: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-09 Garfunkel and Oates - I Would Never (Have Sex with You).mp3
Sending event: database_change
Sending event: item_removed
Replacing item 70957: /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-02 Garfunkel and Oates - Go Kart Racing.mp3
Sending event: database_change
Sending event: database_change
Sending event: item_removed
13 of 13 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1551426692.51, flexible attributes [] from album 5866 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist
Reimported item added 1551426692.8 from item 70950 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-03 Garfunkel and Oates - I Don't Know Who You Are.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70950 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-03 Garfunkel and Oates - I Don't Know Who You Are.mp3
Sending event: database_change
Reimported item added 1551426692.77 from item 70945 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-13 Garfunkel and Oates - Go.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70945 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-13 Garfunkel and Oates - Go.mp3
Sending event: database_change
Reimported item added 1551426692.75 from item 70951 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-10 Garfunkel and Oates - Google.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70951 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-10 Garfunkel and Oates - Google.mp3
Sending event: database_change
Reimported item added 1551426692.76 from item 70956 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-04 Garfunkel and Oates - Handjob, Blandjob, I Don't Understand Job.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70956 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-04 Garfunkel and Oates - Handjob, Blandjob, I Don't Understand Job.mp3
Sending event: database_change
Reimported item added 1551426692.72 from item 70946 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-06 Garfunkel and Oates - Hey Girl in the Moonlight.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70946 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-06 Garfunkel and Oates - Hey Girl in the Moonlight.mp3
Sending event: database_change
Reimported item added 1551426692.73 from item 70952 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-07 Garfunkel and Oates - The Ex-Boyfriend Song.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70952 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-07 Garfunkel and Oates - The Ex-Boyfriend Song.mp3
Sending event: database_change
Reimported item added 1551426692.82 from item 70955 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-11 Garfunkel and Oates - I Would Never (Dissect a Ewe).mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70955 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-11 Garfunkel and Oates - I Would Never (Dissect a Ewe).mp3
Sending event: database_change
Reimported item added 1551426692.74 from item 70949 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-01 Garfunkel and Oates - Wow.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70949 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-01 Garfunkel and Oates - Wow.mp3
Sending event: database_change
Reimported item added 1551426692.76 from item 70953 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-05 Garfunkel and Oates - Save the Rich.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70953 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-05 Garfunkel and Oates - Save the Rich.mp3
Sending event: database_change
Reimported item added 1551426692.8 from item 70954 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-12 Garfunkel and Oates - My Apartment's Very Clean Without You.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70954 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-12 Garfunkel and Oates - My Apartment's Very Clean Without You.mp3
Sending event: database_change
Reimported item added 1551426692.81 from item 70947 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-08 Garfunkel and Oates - Silver Lining.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70947 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-08 Garfunkel and Oates - Silver Lining.mp3
Sending event: database_change
Reimported item added 1551426692.79 from item 70948 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-09 Garfunkel and Oates - I Would Never (Have Sex with You).mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70948 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-09 Garfunkel and Oates - I Would Never (Have Sex with You).mp3
Sending event: database_change
Reimported item added 1551426692.78 from item 70957 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-02 Garfunkel and Oates - Go Kart Racing.mp3
Reimported item flexible attributes [u'track_alt', u'data_source'] from item 70957 for /volume1/Audio/Organising/XXXXXnewFORdukereplace/2012 - Slippery When Moist/01-02 Garfunkel and Oates - Go Kart Racing.mp3
Sending event: database_change
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 10, in <module>
    sys.exit(main())
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/ui/commands.py", line 943, in import_func
    import_files(lib, paths, query)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/ui/commands.py", line 913, in import_files
    session.run()
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/importer.py", line 1511, in plugin_stage
    func(session, task)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beets/plugins.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beetsplug/fetchart.py", line 807, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beetsplug/fetchart.py", line 873, in art_for_album
    for candidate in source.get(album, self, paths):
  File "/volume1/@appstore/beets/env/lib/python2.7/site-packages/beetsplug/fetchart.py", line 416, in get
    self.API_ALBUMS + album.mb_releasegroupid,
TypeError: cannot concatenate 'str' and 'int' objects

```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Synology NAS DSM 6.1.3-15152
* Python version: 2.7
* beets version: 1.4.7-3
* Turning off plugins made problem go away (yes/no):  yes, turning off fetchart stopped the issue

My configuration (output of `beet config`) is:

```yaml

directory: /volume1/Audio/BeetifiedMusic/BeetenDiscoggedReplacements/
library: /volume1/Documents/BeetsDB/DukeboxBeeten.blb

plugins: web fetchart discogs embedart copyartifacts lastgenre

musicbrainz:
    source_weight: 1.0
    searchlimit: 1

discogs:
    source_weight: 0.8
    searchlimit: 5

match:
    required: year

lastgenre:
    count: 4
    separator: ' / '
    prefer_specific: yes

fetchart:
    sources: filesystem fanarttv coverart amazon albumart
    fanarttv_key: XXXXXXXXXXXXXXXXXXXX

copyartifacts:
    extensions: .txt .nfo .jpg .pdf

paths:
    default: $albumartist/$year $album%aunique{}/$track $title
    singleton: Non-Album Tracks/$artist/$title
    comp: Compilations/VA_$album%aunique{}/$track $title

web:
    host: 192.168.X.X
    cors: 192.168.X.*



```

**Comment by GuilhermeHideki** [comment]
We have two problems:
1. The concat error (Tried to fix in #3304)
2. Fanart.tv source expects the `mb_releasegroupid` is an id from MusicBrainz, but it's a Discogs id in this case

The 2nd might be fixable if we check the data_source in the items or at least has an uuid format, avoiding some requests

**Comment by sampsyo** [comment]
This is tricky! I left a comment in #3304 that was erroneously directed at @GuilhermeHideki, but @musiczetetic, could you please take a look? A sample from your library database that reproduces the problem could be super helpful here.

**Comment by musiczetetic** [comment]
Thanks for taking a look. Could you be more specific about "A sample from your library database", do you mean an album of files that causes the issue or something out of the database file?

**Comment by sampsyo** [comment]
The database file.
