### ISSUE TITLE
Error: MusicBrainz not reachable in release search with query

### ISSUE THREAD

**Issue by marty606** [beetbox/beets#3306]
### Problem

Running this command in verbose (`-vv`) mode:

```
$ beet -vv (import -ql -p Y:\Music\ImportToBeets)
```

Led to this problem:
```sh
(Beets PY 3.6) C:\Users\test\Documents\Scrapy\Projects\Namaste\Namaste>beet -vv import -ql -p Y:\Music\ImportToBeets
user configuration: C:\Users\test\AppData\Roaming\beets\config.yaml
data directory: C:\Users\test\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
lyrics: The Genius backend requires BeautifulSoup, which is not installed, so the source is disabled.
library database: Y:\Music\# - Beets\library.db
library directory: Y:\Music\4_Beets
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: Y:\Music\ImportToBeets\Dr. John\Babylon
Tagging Dr. John - Babylon
Searching for discovered album ID: f9d24eec-89de-4bd1-b3fc-ae1a878a6ee9
Requesting MusicBrainz release f9d24eec-89de-4bd1-b3fc-ae1a878a6ee9
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Album ID match failed.
Search terms: Dr. John - Babylon
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'babylon', 'artist': 'dr. john', 'tracks': '7'}
Sending event: import_task_created
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'babylon', 'artist': 'dr. john', 'tracks': '7'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\Babylon (7 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\Desitively Bonnaroo
Skipping.
Tagging Dr. John - Desitively Bonnaroo
Sending event: import_task_choice
Searching for discovered album ID: 7e5b1693-2c42-4edf-a053-8f74153103e4
Requesting MusicBrainz release 7e5b1693-2c42-4edf-a053-8f74153103e4
Album ID match failed.
Search terms: Dr. John - Desitively Bonnaroo
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'desitively bonnaroo', 'artist': 'dr. john', 'tracks': '12'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'desitively bonnaroo', 'artist': 'dr. john', 'tracks': '12'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\Desitively Bonnaroo (12 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\Dr. John's GumboSkipping.

Sending event: import_task_choice
Tagging Dr. John - Dr. John's Gumbo
Searching for discovered album ID: fcb3a2d5-cf9c-4671-b3e0-3924894382d1
Requesting MusicBrainz release fcb3a2d5-cf9c-4671-b3e0-3924894382d1
Album ID match failed.
Search terms: Dr. John - Dr. John's Gumbo
Album might be VA: False
Searching for MusicBrainz releases with: {'release': "dr. john's gumbo", 'artist': 'dr. john', 'tracks': '12'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': "dr. john's gumbo", 'artist': 'dr. john', 'tracks': '12'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\Dr. John's Gumbo (12 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\Gris-GrisSkipping.

Tagging Dr. John - Gris-Gris
Sending event: import_task_choice
Searching for discovered album ID: 8d2476b6-21d0-4ca2-9675-917eac40b3c6
Requesting MusicBrainz release 8d2476b6-21d0-4ca2-9675-917eac40b3c6
Album ID match failed.
Search terms: Dr. John - Gris-Gris
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'gris-gris', 'artist': 'dr. john', 'tracks': '7'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'gris-gris', 'artist': 'dr. john', 'tracks': '7'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\Gris-Gris (7 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\In the Right PlaceSkipping.

Sending event: import_task_choice
Tagging Dr. John - In the Right Place
Searching for discovered album ID: dc689536-49ad-32bd-97ba-975643b46e38
Requesting MusicBrainz release dc689536-49ad-32bd-97ba-975643b46e38
Album ID match failed.
Search terms: Dr. John - In the Right Place
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'in the right place', 'artist': 'dr. john', 'tracks': '11'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'in the right place', 'artist': 'dr. john', 'tracks': '11'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\In the Right Place (11 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\RemediesSkipping.

Sending event: import_task_choice
Tagging Dr. John - Remedies
Searching for discovered album ID: 2c1dc6dd-fd1a-4c62-8949-5de28261fc2c
Requesting MusicBrainz release 2c1dc6dd-fd1a-4c62-8949-5de28261fc2c
Album ID match failed.
Search terms: Dr. John - Remedies
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'remedies', 'artist': 'dr. john', 'tracks': '6'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'remedies', 'artist': 'dr. john', 'tracks': '6'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\Remedies (6 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\The Sun, Moon & HerbsSkipping.

Sending event: import_task_choice
Tagging Dr. John - The Sun, Moon & Herbs
Searching for discovered album ID: b1fdb698-19c0-3ef2-9252-3fd600c7b612
Requesting MusicBrainz release b1fdb698-19c0-3ef2-9252-3fd600c7b612
Album ID match failed.
Search terms: Dr. John - The Sun, Moon & Herbs
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'the sun, moon & herbs', 'artist': 'dr. john', 'tracks': '7'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'the sun, moon & herbs', 'artist': 'dr. john', 'tracks': '7'}
Evaluating 0 candidates.
Sending event: import_task_start

Y:\Music\ImportToBeets\Dr. John\The Sun, Moon & Herbs (7 items)
Looking up: Y:\Music\ImportToBeets\Dr. John\The Very Best of Dr. JohnSkipping.

Sending event: import_task_choice
Tagging Dr. John - The Very Best of Dr. John
Searching for discovered album ID: 3b4b0a56-9448-43f8-9894-06ae233b86fd
Requesting MusicBrainz release 3b4b0a56-9448-43f8-9894-06ae233b86fd
Album ID match failed.
Search terms: Dr. John - The Very Best of Dr. John
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'the very best of dr. john', 'artist': 'dr. john', 'tracks': '18'}
Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 540, in mb_parser_xml
    return mbxml.parse_message(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\mbxml.py", line 135, in parse_message
    tree = util.bytes_to_elementtree(message)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\util.py", line 43, in bytes_to_elementtree
    tree = ET.ElementTree(file=f)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 557, in __init__
    self.parse(file)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\beets\autotag\mb.py", line 434, in match_album
    limit=config['musicbrainz']['searchlimit'].get(int), **criteria)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 965, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 769, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 711, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400, in __call__
    return self.fun(*args, **kwargs)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 675, in _mb_request
    return parser_fun(resp)
  File "c:\users\test\anaconda3\envs\beets py 3.6\lib\site-packages\musicbrainzngs\musicbrainz.py", line 545, in mb_parser_xml
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: not well-formed (invalid token): line 1, column 0

Error: MusicBrainz not reachable in release search with query {'release': 'the very best of dr. john', 'artist': 'dr. john', 'tracks': '18'}
Evaluating 0 candidates.

Y:\Music\ImportToBeets\Dr. John\The Very Best of Dr. John (18 items)
Skipping.
Sending event: import_task_choice
Sending event: import
Sending event: cli_exit

(Beets PY 3.6) C:\Users\test\Documents\Scrapy\Projects\Namaste\Namaste>
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS:  windows
* Python version: 3.6.7
* beets version: 1.4.7
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: Y:\Music\4_Beets\
library: Y:\Music\# - Beets\library.db
import:
    move: yes
    write: yes
plugins: [lastgenre, ftintitle, embedart, fetchart, lyrics, smartplaylist, popularity, mbcollection]
lastgenre:
    count: 5
embedart:
    remove_art_file: yes
fetchart:
    fanarttv_key: 017935260170d93ded95********
    sources:
        - fanarttv
        - itunes
        - amazon
        - coverart
        - albumart
        - filesystem
        - '*'
musicbrainz:
    user: JPHayt****
    pass: DRv*****
    auto:  yes
    remove: yes
```

**Comment by sampsyo** [comment]
This error is indicating that MusicBrainz returned an invalid response. Any chance it was down when you were trying this?

**Comment by marty606** [comment]
> This error is indicating that MusicBrainz returned an invalid response. Any chance it was down when you were trying this?

well i have been trying for a week. I can certainly got to https://musicbrainz.org/ log in and it works just fine....

**Comment by sampsyo** [comment]
Weird! Can you provide some more context here? Does it happen every time? On some music but not other music? On some networks?

Needless to say, this doesn't happen every time for everyone. So we could really use your help narrowing down what might be different about your system.

**Comment by marty606** [comment]
It happens every time. I tried many times over the past week with different albums/artists. I tried again this morning. Same result.

**Comment by sampsyo** [comment]
Weird! Can you think of any way that we might be able to reproduce the problem?

**Comment by marty606** [comment]
I have no idea, it started happening out of the blue. I just tried uninstalling my antivirus but it made no difference.

**Comment by marty606** [comment]
Fixed! It was some kind of virus causing the issue. I ran spybot & malwarebites in safe mode & beets is now importing just fine. Thanks sampsyo for your help.
