### ISSUE TITLE
bpd plugin not working

### ISSUE THREAD

**Issue by krungthe** [beetbox/beets#3324]
A new installation of beets on Ubuntu 19.04, after enabling the bpd plugin in the settings file, the command "beet bpd" fails

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv bpd
```

Led to this problem:

```
user configuration: /home/inaki/.config/beets/config.yaml
data directory: /home/inaki/.config/beets
plugin paths: /home/inaki/beets/myplugins
Sending event: pluginload
library database: /home/inaki/data/musiclibrary.db
library directory: /media/inaki/Data/Music
Sending event: library_opened
Traceback (most recent call last):
  File "/home/inaki/.local/bin/beet", line 10, in <module>
    sys.exit(main())
  File "/home/inaki/.local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/inaki/.local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/inaki/.local/lib/python3.7/site-packages/beetsplug/bpd/__init__.py", line 1604, in func
    int(ctrl_port))
  File "/home/inaki/.local/lib/python3.7/site-packages/beetsplug/bpd/__init__.py", line 1578, in start_bpd
    server = Server(lib, host, port, password, ctrl_port, self._log)
  File "/home/inaki/.local/lib/python3.7/site-packages/beetsplug/bpd/__init__.py", line 1083, in __init__
    from beetsplug.bpd import gstplayer
  File "/home/inaki/.local/lib/python3.7/site-packages/beetsplug/bpd/gstplayer.py", line 32, in <module>
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

```

### Setup

* OS: Ubuntu 19.04
* Python version: 3.7.3
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: /media/inaki/Data/Music/
library: ~/data/musiclibrary.db

import:
    copy: yes
    write: yes
    log: beetslog.txt
art_filename: albumart

plugins: bpd play
pluginpath: ~/beets/myplugins

ui:
    color: yes

paths:
    default: $genre/$albumartist/$album/$track $title
    singleton: Singletons/$artist - $title
    comp: $genre/$album/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title
play:
    command:
    use_folders: no
    relative_to:
    raw: no
    warning_threshold: 100
    bom: no
bpd:
    host: ''
    port: 6600
    control_port: 6601
    password: REDACTED
    volume: 100

```

**Comment by sampsyo** [comment]
Have you installed GStreamer and the relevant Python modules, as described in the documentation? If so, how did you install them?

**Comment by krungthe** [comment]
Everything was already installed, but there was a conflict when run $:sudo apt-get install gstreamer1.0. All the packages and dependencies were already installed, but at the end it said that sudo apt-get install gstreamer1.0-python3-dbg-plugin-loader could not be updated because it conflicted with gstreamer1.0-python3-dbg-plugin-loader, whatever that means, so I tried apt-get install gstreamer1.0-python3-dbg-plugin-loader and it upgraded that package. Now the result I get from beet bpd is this:

$ beet bpd
bpd: Starting server...
bpd: Server ready and listening on :6600
Traceback (most recent call last):
  File "/home/inaki/.local/bin/beet", line 10, in <module>
    sys.exit(main())
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/inaki/.local/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 1604, in func
    int(ctrl_port))
  File "/home/inaki/.local/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 1580, in start_bpd
    server.run()
  File "/home/inaki/.local/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 1100, in run
    super(Server, self).run()
  File "/home/inaki/.local/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 242, in run
    bluelet.run(start())
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/util/bluelet.py", line 380, in run
    exit_te.reraise()
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/util/bluelet.py", line 204, in reraise
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/util/bluelet.py", line 266, in advance_thread
    next_event = coro.throw(*value)
  File "/home/inaki/.local/lib/python2.7/site-packages/beetsplug/bpd/__init__.py", line 241, in start
    MPDConnection.handler(self))
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/util/bluelet.py", line 268, in advance_thread
    next_event = coro.send(value)
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/util/bluelet.py", line 630, in server
    listener = Listener(host, port)
  File "/home/inaki/.local/lib/python2.7/site-packages/beets/util/bluelet.py", line 400, in __init__
    self.sock.bind((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by sampsyo** [comment]
This error means what it says: something else (perhaps MPD itself) is listening on the same port.
