### ISSUE TITLE
gmusic: Beet unable to start

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#3396]
# Problem

Beet is unable to start. Something is wrong with my Google Music plugin, but I'm not sure what it can be. It has always worked before.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv
user configuration: /home/glenn/.config/beets/config.yaml
data directory: /home/glenn/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1239, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1130, in _setup
    plugins = _load_plugins(config)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1116, in _load_plugins
    plugins.send("pluginload")
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 451, in send
    for handler in event_handlers()[event]:
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 434, in event_handlers
    for plugin in find_plugins():
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 288, in find_plugins
    _instances[cls] = cls()
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/gmusic.py", line 37, in __init__
    self.m.login()
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 170, in login
    self._perform_upauth(uploader_id, uploader_name))
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 207, in _perform_upauth
    raise OSError('a valid MAC could not be determined.'
OSError: a valid MAC could not be determined. Provide uploader_id (and be sure to provide the same one on future runs).
```

Here's a link to the music files that trigger the bug (if relevant): N/A

### Setup

* OS: Ubuntu 19.04
* Python version: 2.7.16
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): YES

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/980425CD0425AF66/MP3s.new
import:
#    move: yes
    write: yes
original_date: yes
asciify_paths: yes
id3v23: yes
plugins: edit embedart fetchart lastgenre scrub missing info replaygain gmusic
paths:
    default: $albumartist/$album%aunique{}/$track $title
replaygain:
    backend: gstreamer
embedart:
    ifempty: yes
    remove_art_file: yes
gmusic:
    email: 'gboysko@gmail.com'
    password: SOME_PASSWORD
```

**Comment by gboysko** [comment]
FWIW, there must be some kind of environmental problem, as this has worked with this version. And `SOME_PASSWORD` is not my actual App Password.

**Comment by gboysko** [comment]
FWIW, after a reboot, I don't see the problem anymore. This was reported years ago: https://github.com/simon-weber/gmusicapi/issues/408.

**Comment by sampsyo** [comment]
Hmm; that's mysterious. I don't think there's anything we can do from the beets side, unfortunately, unless I'm missing something?
