### ISSUE TITLE
import: FileNotFoundError

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#3404]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet import ./ToImport/
```

Led to this problem:

```
user configuration: /Users/jack/.config/beets/config.yaml
data directory: /Users/jack/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/jack/.config/beets/library.db
library directory: /Users/jack/Music
Sending event: library_opened
Sending event: import_begin
Traceback (most recent call last):
  File "/Users/jack/.venv/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/Users/jack/.venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/util/pipeline.py", line 262, in run
    msg = next(self.coro)
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/importer.py", line 1294, in read_tasks
    for t in task_factory.tasks():
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/importer.py", line 1109, in tasks
    for dirs, paths in self.paths():
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/importer.py", line 1161, in paths
    for dirs, paths in albums_in_dir(self.toppath):
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/importer.py", line 1613, in albums_in_dir
    logger=log):
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/util/__init__.py", line 222, in sorted_walk
    for res in sorted_walk(cur, ignore, ignore_hidden, logger):
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/util/__init__.py", line 207, in sorted_walk
    if (ignore_hidden and not hidden.is_hidden(cur)) or not ignore_hidden:
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/util/hidden.py", line 80, in is_hidden
    return _is_hidden_osx(path) or _is_hidden_dot(path)
  File "/Users/jack/.venv/lib/python3.7/site-packages/beets/util/hidden.py", line 31, in _is_hidden_osx
    file_stat = os.lstat(beets.util.syspath(path))
FileNotFoundError: [Errno 2] No such file or directory: b'/Volumes/Untitled/ToImport/Emili\xcc\x81ana Torrini'
```

The real name of the directory is "Emilíana Torrini", so it seems that beets is having issues with special characters such as`í` on macOS. This only seems to happen when it is on an _external_ drive - in this case one that is formatted as ExFAT, so I'm not sure if there is much we can do to handle this.

### Setup

* OS: macOS
* Python version: 3.7.3 
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: /Users/jack/Music
```

**Comment by sampsyo** [comment]
Aha; that's too bad! Thanks for pointing this out.

A mildly unsatisfying but effective approach would be to catch `OSError`s in the `lstat` call and just return `False`—i.e., conservatively assume the file isn't hidden if for some reason we can't access the file. This would have the side effect of making this function safe to call on files that _actually_ don't exist.

**Comment by jackwilsdon** [comment]
I'm not sure if the problem is with `os.lstat` itself - does this not indicate some form of issue with `beets.util.syspath(path)`? I'm not at my Mac right now but will be able to test this out later.

**Comment by sampsyo** [comment]
I don't think it does indicate a problem with `syspath`, for two reasons:

- `syspath` should be a no-op on non-Windows platforms. Our standard approach is to put it anywhere we pass a filename as an argument to an OS function call, but I suppose that's not technically necessary in this Mac-only context… 🙃
- I think the filename is correct, according to what you said the directory name is. It's the UTF-8 encoding of the correct string:
   ```py
   >>> b'/Volumes/Untitled/ToImport/Emili\xcc\x81ana Torrini'.decode()
   '/Volumes/Untitled/ToImport/Emilíana Torrini'
   ```

**Comment by jackwilsdon** [comment]
OK so this seems to actually be an issue with my drive and nothing to do with beets at all!

```Text
$ ls -l
d????????? ? ?    ?        ?            ? Emilíana Torrini
$ ls Emilíana\ Torrini 
ls: cannot access 'Emilíana Torrini': No such file or directory
```

**Comment by sampsyo** [comment]
Wow; that's pretty weird! Thanks for following up.

**Comment by zzolo** [comment]
This issue is more about how Macs handle different mounted (non-Mac) file systems and UTF8 characters, and I don't think specific to your drive.

I am not sure I can explain it very well.  This seems to mostly explain it:
https://eclecticlight.co/2017/04/06/apfs-is-currently-unusable-with-most-non-english-languages/

For instance, I can see the files and interact with them in Finder, but in Terminal, it won't recognize them, though it knows something is supposed to be there.

I've dug into this for a while, but can't seem to find a fix.  The hard part with `beets` is that we can't just fix the filename as that will break the database.
