### ISSUE TITLE
No such file or directory, wrong path

### ISSUE THREAD

**Issue by Extarys** [beetbox/beets#3445]
### Problem
I keep getting `No such file or directory` today. Some songs actually disappeared and were not moved.

The target location is `/media/Data3/beet-Test/B/Black Sun Empire` and the album folder is already present. The track I wish to move is from another artist but belongs in that album.

Running this command in verbose (`-vv`) mode:
```sh
beet -v import '/media/NasEntertainment/Musik/S/Subhuman/'
```

Led to this problem:

```
$ beet -vv import '/media/NasEntertainment/Musik/S/Subhuman/'
user configuration: /home/jer/.config/beets/config.yaml
data directory: /home/jer/.config/beets
plugin paths: 
Sending event: pluginload
inline: adding album field albumtype_EP
inline: adding album field albumtype_Single
inline: adding album field bitrate
zero: invalid field: releasegroupdisambig
zero: invalid field: releasegroupdisambig
library database: /media/DarkHawk/opt/beet/library.blb
library directory: /media/Data3/beet-Test
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
chroma: chroma: fingerprinted b'/media/NasEntertainment/Musik/S/Subhuman/Cruel & Unusual (2005)/Disk 2 - 11 Subhuman - Eggplant (BSE remix).flac'
chroma: matched recordings ['8dd41147-7697-4f2a-b5c9-4dfda022dfc5'] on releases ['711d25e7-6f6d-407a-b559-b7f047b755f8', '49ca4330-e387-4eea-baac-7e900bf2f0a7']
Looking up: /media/NasEntertainment/Musik/S/Subhuman/Cruel & Unusual (2005)
Tagging Black Sun Empire - Cruel & Unusual
Searching for discovered album ID: 49ca4330-e387-4eea-baac-7e900bf2f0a7
Requesting MusicBrainz release 49ca4330-e387-4eea-baac-7e900bf2f0a7
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (49ca4330-e387-4eea-baac-7e900bf2f0a7)
Computing track assignment...
...done.
Success. Distance: 0.65
Album ID match recommendation is Recommendation.low
Search terms: Black Sun Empire - Cruel & Unusual
Album might be VA: True
Searching for MusicBrainz releases with: {'release': 'cruel & unusual', 'artist': 'black sun empire', 'tracks': '1'}
Requesting MusicBrainz release 49ca4330-e387-4eea-baac-7e900bf2f0a7
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (49ca4330-e387-4eea-baac-7e900bf2f0a7)
Duplicate.
Requesting MusicBrainz release 711d25e7-6f6d-407a-b559-b7f047b755f8
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (711d25e7-6f6d-407a-b559-b7f047b755f8)
Computing track assignment...
...done.
Success. Distance: 0.76
Requesting MusicBrainz release 0bde632e-4bc9-4ddd-acf9-7454a5f9130e
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (0bde632e-4bc9-4ddd-acf9-7454a5f9130e)
Computing track assignment...
...done.
Success. Distance: 0.68
Requesting MusicBrainz release 211a132b-5e97-455a-bcfa-cd2cacf0ddaf
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (211a132b-5e97-455a-bcfa-cd2cacf0ddaf)
Computing track assignment...
...done.
Success. Distance: 0.77
Requesting MusicBrainz release 613b08f5-562b-4875-9269-c3f896cc629f
primary MB release type: album
Sending event: albuminfo_received
Candidate: Knee Jerk - Cruel and Unusual (613b08f5-562b-4875-9269-c3f896cc629f)
Computing track assignment...
...done.
Success. Distance: 0.79
Searching for MusicBrainz releases with: {'release': 'cruel & unusual', 'arid': '89ad4ac3-39f7-470e-963a-56509c546377', 'tracks': '1'}
Requesting MusicBrainz release 613b08f5-562b-4875-9269-c3f896cc629f
primary MB release type: album
Sending event: albuminfo_received
Candidate: Knee Jerk - Cruel and Unusual (613b08f5-562b-4875-9269-c3f896cc629f)
Duplicate.
Requesting MusicBrainz release d9b77355-2470-4fe0-b183-61dcf082d82f
primary MB release type: album
secondary MB release type(s): compilation
Sending event: albuminfo_received
Candidate: GBH - Cruel & Unusual (d9b77355-2470-4fe0-b183-61dcf082d82f)
Computing track assignment...
...done.
Success. Distance: 0.78
Requesting MusicBrainz release 49ca4330-e387-4eea-baac-7e900bf2f0a7
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (49ca4330-e387-4eea-baac-7e900bf2f0a7)
Duplicate.
Requesting MusicBrainz release 711d25e7-6f6d-407a-b559-b7f047b755f8
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (711d25e7-6f6d-407a-b559-b7f047b755f8)
Duplicate.
Requesting MusicBrainz release 0bde632e-4bc9-4ddd-acf9-7454a5f9130e
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (0bde632e-4bc9-4ddd-acf9-7454a5f9130e)
Duplicate.
Sending event: albuminfo_received
Candidate: Jemir Blanco - Cruel and Unusual (1143625)
Computing track assignment...
...done.
Success. Distance: 0.79
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (Continuous DJ Mix) (44363)
Computing track assignment...
...done.
Success. Distance: 0.53
Sending event: albuminfo_received
Candidate: Various Artists - Cruel & Unusual (44361)
Computing track assignment...
...done.
Success. Distance: 0.73
Sending event: albuminfo_received
Candidate: Various Artists - Cruel & Unusual Sampler (44366)
Computing track assignment...
...done.
Success. Distance: 0.68
Requesting MusicBrainz release 711d25e7-6f6d-407a-b559-b7f047b755f8
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Requesting MusicBrainz release 49ca4330-e387-4eea-baac-7e900bf2f0a7
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
chroma: acoustid album candidates: 2
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (711d25e7-6f6d-407a-b559-b7f047b755f8)
Duplicate.
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (49ca4330-e387-4eea-baac-7e900bf2f0a7)
Duplicate.
Evaluating 10 candidates.

/media/NasEntertainment/Musik/S/Subhuman/Cruel & Unusual (2005) (1 items)
Sending event: before_choose_candidate
Finding tags for album "Black Sun Empire - Cruel & Unusual".
Candidates:
1. Black Sun Empire - Cruel & Unusual (Continuous DJ Mix) (47.1%) (id, tracks, media, ...) (Beatport, Digital, 2005, Black Sun Empire, BSELP002MIXCD)
2. Black Sun Empire - Cruel & Unusual (35.3%) (missing tracks, country) (2xCD, 2005, NL, Black Sun Empire, BSECD002)
3. Black Sun Empire - Cruel & Unusual (32.3%) (missing tracks, id, mediums, ...) (4x12" Vinyl, 2005, NL, Black Sun Empire, BSE LP 002)
4. Various Artists - Cruel & Unusual Sampler (32.1%) (id, tracks, media, ...) (Beatport, Digital, 2005, Black Sun Empire, BSESAM002)
5. Various Artists - Cruel & Unusual (27.4%) (missing tracks, id, tracks, ...) (Beatport, Digital, 2005, Black Sun Empire, BSELP002)
6. Black Sun Empire - Cruel & Unusual (24.2%) (missing tracks, id, label, ...) (2xCD, 2006, US, Ohm Resistance, OHM_00002)
7. Black Sun Empire - Cruel & Unusual (22.5%) (missing tracks, id, tracks, ...) (Digital Media, 2005, XW, Black Sun Empire, BSELP002MP3)
8. GBH - Cruel & Unusual (22.5%) (missing tracks, id, artist, ...) (CD, 2004, US, Idol Records, IR 044)
9. Jemir Blanco - Cruel and Unusual (21.5%) (id, artist, missing tracks, ...) (Beatport, Digital, 2013, Spike, SPIKE003)
10. Knee Jerk - Cruel and Unusual (21.4%) (missing tracks, id, artist, ...) (2002, US)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? i
Enter release ID: 49ca4330-e387-4eea-baac-7e900bf2f0a7
Tagging Black Sun Empire - Cruel & Unusual
Searching for album ID: 49ca4330-e387-4eea-baac-7e900bf2f0a7
Requesting MusicBrainz release 49ca4330-e387-4eea-baac-7e900bf2f0a7
primary MB release type: album
secondary MB release type(s): dj-mix
Sending event: albuminfo_received
Candidate: Black Sun Empire - Cruel & Unusual (49ca4330-e387-4eea-baac-7e900bf2f0a7)
Computing track assignment...
...done.
Success. Distance: 0.65
beatport: Searching for release 49ca4330-e387-4eea-baac-7e900bf2f0a7
Evaluating 1 candidates.
Sending event: before_choose_candidate
Tagging:
    Black Sun Empire - Cruel & Unusual
URL:
    https://musicbrainz.org/release/49ca4330-e387-4eea-baac-7e900bf2f0a7
(Similarity: 35.3%) (missing tracks, country) (2xCD, 2005, NL, Black Sun Empire, BSECD002)
CD 2
 * Eggplant (BSE remix) (#11) -> Eggplant (BSE remix) (#22)
Missing tracks (34/35 - 97.1%):
 ! The Cooler                    (# 1) (6:47)
 ! Boris the Blade (Optiv remix) (# 2) (6:43)
 ! Bitemark                      (# 3) (7:30)
 ! Masquerade                    (# 4) (6:26)
 ! Hideous                       (# 5) (6:42)
 ! Everything                    (# 6) (6:41)
 ! Sideways                      (# 7) (6:09)
 ! Future Frame                  (# 8) (7:05)
 ! Breathe (BSE remix 01)        (# 9) (6:26)
 ! Breathe (BSE remix 02)        (#10) (6:40)
 ! Stranded V2.0                 (#11) (6:43)
 ! Stranded V2                   (#12) (2:00)
 ! Centepod                      (#13) (2:00)
 ! Circle of Nine                (#14) (1:32)
 ! Sahara                        (#15) (3:01)
 ! Brood X                       (#16) (1:38)
 ! Boris the Blade (Optiv remix) (#17) (2:33)
 ! Just the One                  (#18) (2:00)
 ! Got Lost                      (#19) (2:44)
 ! The Promist 2005              (#20) (2:28)
 ! Skullfucked                   (#21) (3:50)
 ! Night Raiders                 (#23) (1:27)
 ! The Cooler                    (#24) (2:55)
 ! Sideways                      (#25) (2:11)
 ! Fearless                      (#26) (2:33)
 ! Hideous                       (#27) (4:23)
 ! Everything                    (#28) (2:22)
 ! Masquerade                    (#29) (1:38)
 ! Bitemark                      (#30) (5:07)
 ! 1138                          (#31) (3:39)
 ! Future Frame                  (#32) (4:45)
 ! Breathe (BSE remix 02)        (#33) (6:13)
 ! Panorama                      (#34) (2:11)
 ! Beautiful Morning (BSE remix) (#35) (5:26)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? a
Sending event: import_task_choice
found duplicates: [160]
default action for duplicates: a
This album is already in the library!
could not get filesize: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac'
could not get filesize: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/09. Breathe (BSE remix 01).flac'
could not get filesize: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/10. Breathe (BSE remix 02).flac'
could not get filesize: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/33. Breathe (BSE remix 02).flac'
could not get filesize: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/15. Sahara.flac'
Old: 5 items, FLAC, 961kbps, 25:05, 0.0 B
New: 1 items, FLAC, 981kbps, 2:11, 15.4 MiB
[S]kip new, Keep both, Remove old, Merge all? m
Sending event: import_task_start
chroma: chroma: fingerprinted b'/media/NasEntertainment/Musik/S/Subhuman/Cruel & Unusual (2005)/Disk 2 - 11 Subhuman - Eggplant (BSE remix).flac'
chroma: matched recordings ['8dd41147-7697-4f2a-b5c9-4dfda022dfc5'] on releases ['711d25e7-6f6d-407a-b559-b7f047b755f8', '49ca4330-e387-4eea-baac-7e900bf2f0a7']
Traceback (most recent call last):
  File "/home/jer/.pyenv/versions/3.7.2/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 315, in run
    for msg in _allmsgs(out):
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 466, in pull
    out = coro.send(msg)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/importer.py", line 1344, in lookup_candidates
    plugins.send('import_task_start', session=session, task=task)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/plugins.py", line 489, in send
    result = handler(**arguments)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/plugins.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beetsplug/chroma.py", line 182, in fingerprint_task
    return fingerprint_task(self._log, task, session)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beetsplug/chroma.py", line 251, in fingerprint_task
    acoustid_match(log, item.path)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beetsplug/chroma.py", line 91, in acoustid_match
    duration, fp = acoustid.fingerprint_file(util.syspath(path))
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/acoustid.py", line 324, in fingerprint_file
    return _fingerprint_file_audioread(path, maxlength)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/acoustid.py", line 265, in _fingerprint_file_audioread
    with audioread.audio_open(path) as f:
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/audioread/__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/audioread/rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac'
```

The path `'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac'` is not valid. The destionation is /media/beet-Test.

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Mint 19.2
beets version 1.4.9
Python version 3.7.2
no plugins loaded

* Turning off plugins made problem go away (yes/no): No, but the song form source folder is **gone**
```
Replacing item 1514: /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac
Sending event: database_change
Sending event: item_removed
Replacing item 1505: /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/09. Breathe (BSE remix 01).flac
Sending event: database_change
Sending event: item_removed
Replacing item 1506: /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/10. Breathe (BSE remix 02).flac
Sending event: database_change
Sending event: item_removed
Replacing item 1526: /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/33. Breathe (BSE remix 02).flac
Sending event: database_change
Sending event: item_removed
Replacing item 1510: /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/15. Sahara.flac
Sending event: database_change
Sending event: database_change
Sending event: item_removed
5 of 6 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Reimported album: added 1574362192.8681886, flexible attributes [] from album 160 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)
Reimported item added 1574362192.8895912 from item 1514 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac
Reimported item flexible attributes ['track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength', 'track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength'] from item 1514 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac
Sending event: database_change
Reimported item added 1574362192.8796613 from item 1505 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/09. Breathe (BSE remix 01).flac
Reimported item flexible attributes ['track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength', 'track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength'] from item 1505 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/09. Breathe (BSE remix 01).flac
Sending event: database_change
Reimported item added 1574362192.8808138 from item 1506 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/10. Breathe (BSE remix 02).flac
Reimported item flexible attributes ['track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength', 'track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength'] from item 1506 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/10. Breathe (BSE remix 02).flac
Sending event: database_change
Reimported item added 1574362192.9029472 from item 1526 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/33. Breathe (BSE remix 02).flac
Reimported item flexible attributes ['track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength', 'track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength'] from item 1526 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/33. Breathe (BSE remix 02).flac
Sending event: database_change
Reimported item added 1574362192.885243 from item 1510 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/15. Sahara.flac
Reimported item flexible attributes ['track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength', 'track_alt', 'data_source', 'danceable', 'gender', 'genre_rosamerica', 'mood_acoustic', 'mood_aggressive', 'mood_electronic', 'mood_happy', 'mood_party', 'mood_relaxed', 'mood_sad', 'rhythm', 'tonal', 'voice_instrumental', 'average_loudness', 'chords_changes_rate', 'chords_key', 'chords_number_rate', 'chords_scale', 'key_strength'] from item 1510 for /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/15. Sahara.flac
Sending event: database_change
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
removing reference to missing album art file /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/cover.jpg
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: before_item_moved
Traceback (most recent call last):
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/__init__.py", line 481, in move
    os.rename(path, dest)
FileNotFoundError: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac' -> b'/media/Data3/beet-Test/%/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/site-packages/beets/util/__init__.py", line 485, in move
    shutil.copyfile(path, dest)
  File "/home/jer/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: b'/media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac'

Error: No such file or directory while moving /media/DarkHawk/beet-Test/B/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac to /media/Data3/beet-Test/%/Black Sun Empire/2005 - Cruel & Unusual (FLAC)/19. Got Lost.flac
```

`/media/DarkHawk/beet-Test` does not exist and never has.
My configuration (output of `beet config`) is:

```yaml
directory: /media/Data3/beet-Test
library: /media/DarkHawk/opt/beet/library.blb
per_disc_numbering: no
asciify_paths: yes
original_date: yes

import:
    write: yes
    move: yes
    copy: no
    languages: en fr
    bell: yes
    quiet_fallback: skip
    log: /media/DarkHawk/opt/beet/beet.log

match:
    strong_rec_thresh: 0.05
    preferred:
        countries: ['CA', 'US', 'GB|UK', 'FR', 'XW']
        media: ['CD', 'Digital Media|File', 'Blu-ray', 'SACD', 'Vinyl']

ui:
    color: yes

paths:
    default: %upper{%left{%the{$albumartist},1}}/$albumartist/%if{year,$year - }$album%aunique{} (%upper{$format})/$track. $title
    albumtype:soundtrack: Soundtracks/$album%ifdef{$year, - $year}/$track. %asciify{$title}
    singleton: Non-Album/%asciify{$artist}/%asciify{$title}
    comp: Compilations/$album%aunique{}/$track. %asciify{$title}

#item_fields:

album_fields:
    albumtype_EP: u'(' + albumtype + u')' if albumtype == 'EP' else ''
    albumtype_Single: u'(' + albumtype + u')' if albumtype == 'Single' else ''
    bitrate: |
        total = 0
        for item in items:
            total += item.bitrate
        return total / len(items)

#plugins: inline convert web lyrics lastgenre acousticbrainz scrub chroma acousticbrainz beatport zero ftintitle extrafiles fetchart fromfilename the

zero:
    fields: month day year comments r128_album_gain releasegroupdisambig rg_album_gain rg_album_peak r128_album_gain r128_track_gain releasegroupdisambig rg_track_gain rg_track_peak
    comments: [EAC, LAME, from.+collection, 'ripped by']
    genre: []
    update_database: true

fetchart:
    auto: yes
    maxwidth: 2048
    minwidth: 760
    enforce_ratio: 0.5%
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    

replaygain:
    auto: album

extrafiles:
    patterns:
        artworkdir:
          - '[sS]cans/'
          - '[aA]rtwork/'
        lyrics:
          - '*.lrc'
    paths:
        artworkdir: $albumpath/artwork
        lyrics: $albumpath/$filename

scrub:
    auto: yes

lyrics:
  auto: yes
  force: no
  fallback: ''
  google_engine_ID: 009217259823014548361:lndtuqkycfu
  google_API_key: Something

lastgenre:
    auto: yes
    source: artist
    min_weight: 10
    count: 5
    separator: '; '
    prefer_specific: no
    canonical: no

acousticbrainz:
    force: yes

chroma:
    auto: yes

acoustid:
    apikey: babyshark
```

**Comment by sampsyo** [comment]
Huh, that seems bad—are you saying that the file actually gets deleted? Is there anything I can do to try to reproduce the same problem? I'm having trouble following the steps here to understand exactly what caused the situation you're seeing.

Are the files you're importing already in your library (i.e., this is a re-import)?

Could this be https://github.com/beetbox/beets/issues/702?

**Comment by Extarys** [comment]
Hi, thanks for your reply.

No, the file I'm trying to import was not previously imported. That's what is strange about this.
Current, old library: `/media/NasEntertainment/Musik/`
Imports to: `/media/Data3/beet-Test`
On `/media/DarkHawk/` only the database file and the logs are saved.

I noticed that if I don't touch the terminal (coffee, toilet) and the background stuff are done (in -vv mode) but still requires my input (apply, skip etc), sometimes the program also throw an exception - I would need to test this further. I believe the database file of beet might be corrupted. I'm not sure, we had quite a few electric outages and I never completely shut my computer, it's always in hibernate/sleep mode when I'm not using it.

Is there a way to delete the current `/media/DarkHawk/opt/beet/library.blb` and regenerate it (reimporting maybe?) from the "test-Beet" folder without doing anything else and see if the error persist?

**Comment by sampsyo** [comment]
Hmm, that continues to be pretty mysterious.

One way to "re-create" the library database is to use `import -AWC` on your existing library (possibly with `move` turned off in your config), as mentioned in this FAQ entry:
https://github.com/beetbox/beets/issues/702
