### ISSUE TITLE
Support sorting by specific attributes

### ISSUE THREAD

**Issue by rain0r** [beetbox/beets#3461]
### Use case

I'm trying to use beets to sort by item rating:

```
$ beet ls -f '$path' rating-
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/beet", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.7/site-packages/beets/ui/commands.py", line 1072, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/usr/lib/python3.7/site-packages/beets/ui/commands.py", line 1067, in list_items
    for item in lib.items(query):
  File "/usr/lib/python3.7/site-packages/beets/dbcore/db.py", line 701, in __iter__
    objects = self.sort.sort(list(self._get_objects()))
  File "/usr/lib/python3.7/site-packages/beets/dbcore/query.py", line 885, in sort
    return sorted(objs, key=key, reverse=not self.ascending)
TypeError: '<' not supported between instances of 'float' and 'str'

```

### Solution

There is already a TODO in the code for this issue: https://github.com/beetbox/beets/blob/0c033bdaf10b78be04e6ebc8f998d9d3d5f70e3d/beets/dbcore/query.py#L875

I guess most - if not all - attribute fields already have a type specified (like the `acousticbrainz`-plugin here: https://github.com/beetbox/beets/blob/master/beetsplug/acousticbrainz.py#L116).

So we should somehow gather or query them when sorting the objects.

**Comment by sampsyo** [comment]
Huh; this should indeed work!

I have a couple of questions to help nail down what's happening:

- What does your configuration look like? Have you tried using the `types` plugin to define an integer type for your rating field?
- What happens if you restrict this to just one or two songs? I realize that might not be all that useful, but it could be a bad interaction with _specific tracks_ in your database and it would be good to narrow down which are causing the problem.

**Comment by rain0r** [comment]
The `types` plugin was not enabled. I can't define a type for `rating` since it apparently was already defined:

`beets.plugins.PluginConflictException: Plugin mpdstats defines flexible field rating which has already been defined with another type.`

This is also the case for all fields of the `acousticbrainz` plugin.

---

I think I found an affected item, it's [Little Simz feat. BADBADNOTGOOD - Our Conversations](https://musicbrainz.org/recording/f4b9f90f-1a38-4cd4-937c-5c0260f9a5d6). The rating for this track is `0.3125`.

When this track is in the result set, ordering by rating fails.

**Comment by sampsyo** [comment]
Got it! Any chance you could share your library database file for debugging? It should help reveal exactly where the unexpected types are coming from in that comparison.

Barring that, some SQLite output could be helpful, if you have comfortable drumming it up.

**Comment by rain0r** [comment]
The database is around 100MB, so I guess it might be easier if I just pass the information.

I'm comfortable working with SQLite, so ... what kind of output would be useful?

**Comment by sampsyo** [comment]
OK, cool! Just a `SELECT *` from an affected and unaffected row of the `items` table, and probably a `SELECT * FROM item_attributes WHERE entity_id=<item id>` to get the flexible attributes. I'm not sure that will actually tell us the types of the values, but worth a shot?

**Comment by rain0r** [comment]
Okay, here is the affected row:

```
id|path|album_id|title|artist|artist_sort|artist_credit|album|albumartist|albumartist_sort|albumartist_credit|genre|lyricist|composer|composer_sort|arranger|grouping|year|month|day|track|tracktotal|disc|disctotal|lyrics|comments|bpm|comp|mb_trackid|mb_albumid|mb_artistid|mb_albumartistid|mb_releasetrackid|albumtype|label|acoustid_fingerprint|acoustid_id|mb_releasegroupid|asin|catalognum|script|language|country|albumstatus|media|albumdisambig|releasegroupdisambig|disctitle|encoder|rg_track_gain|rg_track_peak|rg_album_gain|rg_album_peak|r128_track_gain|r128_album_gain|original_year|original_month|original_day|initial_key|length|bitrate|format|samplerate|bitdepth|channels|mtime|added|work|mb_workid|work_disambig|style|discogs_albumid|discogs_artistid|discogs_labelid
746|/mnt/archivefs/music/Singleton/Little Simz feat. BADBADNOTGOOD/Little Simz feat. BADBADNOTGOOD - Our Conversations.mp3||Our Conversations|Little Simz feat. BADBADNOTGOOD|Little Simz feat. BADBADNOTGOOD|Little Simz feat. BADBADNOTGOOD|Stillness in Wonderland (Deluxe Edition)|Little Simz|||||||||0|0|0|16|22|0|0|||85.0330505371|0|f4b9f90f-1a38-4cd4-937c-5c0260f9a5d6||3cdb40fe-a63e-4bb9-b40d-17cda5f50979|||||AQADtMqVREmUaPh14gofIUeyoTmebLjCB73BRD_mU0g2HWmONuFxUT8-4yjCNFqaQ9cRjzVCJX2QLO_xr3ia4An8ZMe94-qO40JoBeIfnDv8Bbai42xRLQoutYFMhOLhC9fRzMeXEtHBZ5Kg_Nj4EdePDxXzQcuJMzzeIx0p4zY-iSqO5hx6yccVGzvxY-qOLFIjJI2XpZjSxUIfxri0cURPwd1w-DxGM0iYlMjhHm2443zA69Bf-MbN4DnAPHBJ2EEpBzzyHtqPdPnh17hCnLBzxGkOlXyQPmiuIesbNMwDjdMQHT-O5g-K2_iLi1mK-8F99Hge2FtRagkwHclfhFaOh09Q8XiSOHAs4UkPL0PoJ0j-4HRA_jiVF6dyNNR0TM_SI_mOHD9eDQ-N8zjy41T24Aw_5DpxdPcx5Th3D3l68NA--HD3wvCWQ3eOGl-Onki55cCfgyVMHk_B4-Lh7nh__PiMfLjxRhusbbAqVSlO6DauvDEu6kjboOyCj0f4Dg6H7sgLzjnQPHHQb2jyIHwWhdDGoMkVC_k-ocGzLMgNscuRxtNoHE3c4zkPlnmOPxr8E1-m4XQaPD_O4x9qXXCjUkhjiUi240yOptGCWj_44DzcTMGPUA78DNMdPBd04iKPTxl1_EkQrdXx4wnR_EJFn2jmo0-Ga0e1ZfCV4wv-gbmOH9dxJssR_7jTQM8QZjoeZUnhZ8dND0wSs8JDnOGQPOGRjuGH42qPxl8Q_oF-xFMSRUIpgdIl3AnSHno0pNeM1ipuEtcJ1xZiJwszkCHh_Lgjo0-C9LkIP1EK-3hyXDw-p8NF4pnwqMcVkTiLJxecH1Uu4aIDXThhJyz-BReOKy_6IfWUC8-Om4e4JfMRR3uI8kPMQw9c0dCTQ_-Q5T38g_rSGaEeRXiS45p06EL4SGiON8dhecZzHP4SIc-0GUnR8Ch5NG6MO0ejMsc_VJxy5DnK5_gePDq05FuE8EWP5jF2WoKd6DiP05ieB-nkw5QO53CdEV8mFl0vg6FcfHmC7_jhyNAecCfOHFceoteF_2he6MEXc_gLc-FxSTuaUD36fGiUmUboHY30oGQkdNNhsYRDyQfbI_4GLUqmHbGJRyauD2Gpi0iWlHh2_MLxi0WvJVpg5ki4B6HioAkpok-Wg9eD6yWaHX18VJkEx_HQVxz6XIj2Bsp_NIwSpcHdIo9SWA-Hz8anlGjGw-kU9JGQ_Kj0UAhDXJfQOEUelZhy6EmOL7go4-GJe-rQ7WjsQ32OQ8uO_mjS7Yh0NEkYJeh3XELjZJk0JPuRk4vwB2V2ogmlZXhOEWV0pNOOZM_RfCXROzgpfFmCo2KzBWHOdJCZnNDxw5fiIdaOhiiXoM8KV0T6tKiSB1-UEVdCDVk-fIePHld6kHsQ65Dy4HvQPDj4o2eOMNaaoT-yJHpwlsQf4x_eCWXGFEy25Dgf5Fc6lFmU7qhEkcihxziJZzrCMCheXTi6TC-aR8WvFI3DoxKzIHl_pOtxqvBxH80T-ehzHOGabagoNsOP69D7Ir1wdNTRfEetHM3xH-eGsifykDuk84TrePB4aNegZsqJxg1xKrug-scfhB3esLgWgwt9_EFKFvo1_EfOHN-FNHuGRznKhWieZRauH-Xj4HrQaRkqqTrcRDuS48MPRsrxG2_iCU34oReunvhfPAuOa8eTG6dE9EdyZsj7oWkaXFfwLZfASj3S58eXIcyYE2Wu4tNwU8YvPMaZWENypGmyqMePT7lw6-iP0I0MPUFIHw0jxgHbDk1FhO86qG0spJWOH2cyXHuKMzryBkm6D82WxEKPKwrOvMiPpNQxL9HR5Kh5VCeD5peRXDnyvUTLHc30rHgmWviPHq4SIXmFMLNygsef41-Yo7nQfRqSUllu5Cd6JHySCyETH1eu4fhCoXmE6seXy-CWL8RjfBJsHmcXHBPfomEuJUi-OQviTBH-5dgPJp-YotgjB79w9IGXZTxKPnj2SEbM7ISeEeGJ5riC5LtQKxfCfHgyHZV5NHsy5EyQfDE8MluKa-nxHn6U4NGsYH4D78HzQu5anEc_HVcL82D44R-uB8d_PBMuSR-ShdKHUOKFH1Se4n-I7kUTa8eTJ8SDSzlC6zvuicLDQhecHI6XFYx1EZ9e9AlcJYV4EqHo4KSHJhK_IHw19Dm-ZVC047pQaoFoIdTS4w1t_EYtwRYt5NKRVGeKTWXxLUuFf_hhJynRF8mPUIqYo2sWXIqHf0NPEs0khvg-XH0alE_wHyc-HXeI6Tu-JfiDK2FSXDnRfKiOxKmE_DiPK8qF5sLJHP2OR3iT6QjPCKKeI5KcCOeFPoG3ZEe1T8KzeAKT8AgPPoeO_RFyHldChBY8n4H4TEdz4spc6DEeI0ySo2WM__iDZ8e1B_lzXBCnH49wM8WTRj-mcDlRPsSHH14_PD9GTWcRafcinLiYBbmy47Ez6HnhDLVKhGSO-8iVgylZ6AxOH9fSYUoe9FmOlztUMXgKvQ-uC8a14yrWqqjmHPyPOsly5EfLHM1-PLhyDaOWqrjCo9k79EuGN8Of4_GQPDkRUUdXqXCH_uCP3gjzQI6c44r6Iv_Q62ge5FlySLUcIc6UdUK1MUfzg9cV5OfRN9CyIt9xNalwJ-ISPCUaxgnxbSz-4ByPZN4SIl9O9BIFKpcsfDwa48uOs0doSUHj5NC7QvckpMt-3DmO20rBfEGjZkesbEfJHFoqKfiRF02lHXcOi15wUP7Qh3iH8BBj5jhvZI6Oq9vgSxFx-MoQLjL0RRfydoVDXjF-MHmWwmOG6XiURRGaLQ9qMQzeaEZzAEAAAAQqQoAySAIDCBDOCqAQAMRRAwAwAigAFAJAEQKIA8QYYogAgggECLDAKSuEgI44BwgxDCgMiBKQCASAOIwpYQBQiFFkDCBAMGMSQxQAgYASjGjEEEAKAoCMAUQAQAAQAjjpEBCAG-EAEMQIUYgCAAFgAJECMEIAEYgBBBQASiDgDFYOCAGQcQ4qYggRggmChBAECAIAE0gARgBRxiBBjCGYCSSRIkwEIYAyDmAGABEACSIMMkBBAoQAhCAECQCAKSAIQ8AIBDgBjACkhBEIGAGYMsAIwAwilBEiEBGEAaQRIIApBQRyHBpIlEACASMYgFwIoGQVHAAhAHJMCCUAAU4gACwyBlEmjFDUGIKEMAwJQgQDgBgAFBECAGGEUA4KowQjBgDgAEkEKAEMMMgQYIQg0CgAEEGCCMQEgEoZ4ggBgAEgOCGEgYKYYIYAAIhFChBFDQOCUwawAgIQ5ghBwBiFkVIMGEGUEIZAIKkEDAAgIRAIKTMMEEQIYJRABBBhIGFGAWCAhIJooQAgCBCiBABAEAIJAkQYQggSlAnABEAICAoA4ZYpQYRQgAADAGMYGIGEABIQAwADgggCGEBMEQGIEAQgIgwUTgIiAAPScMSAcEQgCYAhSggAAAAAEECJEwAARIRShgBCkHYIQIGQQwAxIgAARAkhkPUKGUAAFAQZYRQBAgAkkCLACMEQUAAg4JBRgiEjKAFCUGQAIAIoRAgRQhEAhCIWCEEUABgoIIASFgHikBGACgaMMAYYIQgCyiFijBQECacIAIoQSggRBgBBAFGGGKEUI0oBgQRABCBCHTCGACQIIYJpIBAAAAhAmQIGAAEAMAYYpQhQBAChqGDCKEEIYwAIAARQCBAikhLACAEokMAQQhhQggGhDAUAKQcMEAQAgBwBwBnABEECCAEUAYQAgIAQyQgAqLACUEKEkIIJAwAoAgBAFFAGEQM|b7de7cfd-f144-4775-838e-b0d243a06fb3|||||||||||||-8.11|1.08125925064087|||||0|0|0|A|363.52|320000|MP3|44100|0|2|1572531680.0|1554282789.77568|||||||
```

Item attributes:

```
sqlite> SELECT * FROM item_attributes WHERE entity_id=746;
id|entity_id|key|value
746|746|data_source|MusicBrainz
63286|746|last_played|1562272247
63287|746|skip_count|1
63288|746|rating|0.3125
163173|746|danceable|0.865370690823
163174|746|gender|female
163175|746|genre_rosamerica|rhy
163176|746|mood_acoustic|0.246594280005
163177|746|mood_aggressive|0.170967742801
163178|746|mood_electronic|0.747600197792
163179|746|mood_happy|0.14324451983
163180|746|mood_party|0.411458224058
163181|746|mood_relaxed|0.849749684334
163182|746|mood_sad|0.38193166256
163183|746|rhythm|VienneseWaltz
163184|746|tonal|0.022494783625
163185|746|voice_instrumental|instrumental
163186|746|average_loudness|0.875408232212
163187|746|chords_changes_rate|0.066291987896
163188|746|chords_key|A#
163189|746|chords_number_rate|0.00204368378036
163190|746|chords_scale|major
163191|746|key_strength|0.702238380909
```

Now for an item which can be sorted by `rating`:

```
sqlite> SELECT * FROM items WHERE id=24359;
id|path|album_id|title|artist|artist_sort|artist_credit|album|albumartist|albumartist_sort|albumartist_credit|genre|lyricist|composer|composer_sort|arranger|grouping|year|month|day|track|tracktotal|disc|disctotal|lyrics|comments|bpm|comp|mb_trackid|mb_albumid|mb_artistid|mb_albumartistid|mb_releasetrackid|albumtype|label|acoustid_fingerprint|acoustid_id|mb_releasegroupid|asin|catalognum|script|language|country|albumstatus|media|albumdisambig|releasegroupdisambig|disctitle|encoder|rg_track_gain|rg_track_peak|rg_album_gain|rg_album_peak|r128_track_gain|r128_album_gain|original_year|original_month|original_day|initial_key|length|bitrate|format|samplerate|bitdepth|channels|mtime|added|work|mb_workid|work_disambig|style|discogs_albumid|discogs_artistid|discogs_labelid
24359|/mnt/archivefs/music/Brian Jonestown Massacre, The/Thank God for Mental Illness/07-The Brian Jonestown Massacre - Free and Easy, Take 2.mp3|1646|Free and Easy, Take 2|The Brian Jonestown Massacre|Brian Jonestown Massacre, The|The Brian Jonestown Massacre|Thank God for Mental Illness|The Brian Jonestown Massacre|Brian Jonestown Massacre, The|The Brian Jonestown Massacre|Shoegaze, Indie Rock||||||0|0|0|7|13|1|1|||88.5166702271|0|c22324d2-fb64-436d-bc2f-510c5457fb80|8c49701e-b108-4f33-88a7-96d33c64dc3c|381e8434-109a-439c-8acc-5d328359f2e0|381e8434-109a-439c-8acc-5d328359f2e0|10ca0c40-1ade-3cbc-8267-09d50266fdf3|album|BOMP Records|AQADtEmSJNmWcQkcJTzyo-kp3MGzHD-qTSca5YjJDz80Lgx-5C-8p_iRC09QH9KT4yKa2ESXKbiPHtbx49Aq48YVhMf9w3rwGZaGfFC3HkcaH343XIqF57gYI-Qr9PrhXoiaZ-h3_MNuDleE_mjOVDjygEludIygZ8d_XHmSQHiG5uiz48qLP0d_-Hng4zwY78NN9GEuWOmhJwxONDtOefhmoTn643ygH9cPO2AZFg-ORgxeJT4Of9AY4qWFgrpRvbjwo_vhJYP8Eel3GSfRL0Ut-Ogjhcieg71x4jmY48Z9_HiO_DiJi8cNfxTxEHlHaNTxtviP8nBF-Dl-6A08tshHZCZ8mCcOXYJ1PLtwnHoQO4d_fGGCX2jYTsgOjRXCOMJ9PNE9fDl6Zmh2zBuPH2EXxRE8MoV4zI3C41NhRcqFm0f-4jz-4nCmSDm6kEd4eUiW_DiP-cHRxHlwCkf4LIf-CDMl5wj7wPuR7ziPh1nRdj2u4zyarxLa42QOLWqO8MOjUfiPMse1IT_-QEv4I--FT4mCHul44SGh84d59MmCkDdy_bBczvhZ3Dqu4WTwHu9gRZbRHye66JvAw19oaMwe4UHJpmj04-2gL4jFE82OngHnzDMKe8KfHFeUIJRIGbpT5D2uPAu2Ezlu6EKlznCiI9qOfcd3-Av66CFefJgiqphkPnjE6Agz5sKRPDr6KJHxv8I4jcSZB432HT0-_BHy8Pjjo1eC5rgF9lLATcebodKN5viLZxb44_jxS3gkBT_6RRB_nId_9Hlwpqi3ownB9ug4iN3hH0ep6jiPRz5KElr0gO2F_uhXXOhJpNY8_AnO6QjzCx9jfDMaaqipQy-jYk-Q7rGxH5d0oXEfXMd3pIfCY49UpEkktL0ChvD5IHexQ3zkQceTo9mD6OPx6WjA2CquoBdGHl024YlwUcEvJ0j4Ilfw6ngeXDqeHWmuFMkTHUcf5Wjy4WjUo3pq5Eh2NMsxUwou4_nA43iLHKpsoaBVnMHTQ5dSfIGP0oaeF-_x0mguBfXwH7eg78Jr5EF_uCIeHnkO1cyR78HFPOjzGH1ghxb4KPD3IFQD3cITwXuFWrmG5mmCQ6cEis_xHbnyEKWVIsx54ReY8RmaBzreBfqWH90peEwGH9fxHx6068EnWfiO_9jOFF92_NAuwtWFi7twPBvs5ihv7MJ9hPmS4xNx4rikUMclZN-FaucCvXiO5jH6KPiBC3qWL-jhmsUjCt2T40U7NkK5MMaPUmj4gO3xJ7CZDtfxYiqaM8M51NIT-DiZQ3yEW8W1HJhS7jiaH7XaQ8-FMI6MhzF8Bb_xC7ZiofNIXEcfPPNw6UG4RL6B9MFpPEoYfBJKI4y8B9p72DlCjUd-9C386NAY8ThT6A8-Henk4HvApRm8RMzG4SnxEJke6AmR4zyO-wnCQ8yG3Dp--MZ1_Gj-4NmF6zn4w2rx5ENeXBe07sV3WMdxIa1xnKfh46CmDUcOfUuJxn0QXfqB5-iNMNfxo39gQ8-h7MeHH89wMHuOZzuOFs0zXHsOonCNm_CDyHtwURLwFV4eCxV1fDERPhCV4y_yhSp--Cgb4duFH011PCcm9AZ_9MNM3AlxibgVhLbhP8Ev_Pjx5OiPo6ShX0XJWshDGTWP5kuN4_JRhocd1M7xREd06YN-_KgFUcafDp6mHL2F4xoD7fDKLYeP44oIJidx6riO89CPki385PhRWsGXHQ8vQaWOME-JHnc-XJdw4mpy4TNxPUiVU8MeyDn-oE84YsquICdCcmDC4to7yP2Gxg2D0srxRSg3Bf48uIe7h9B5WAyDlpGO8rBZaI9S_PjR7I8RWscv5JPAeNKJn9CJxhfO4I_Q_dByBadyNCvaHezCNPiOH81lopdw0kE-XA3Ko3lxKTe-D93EBLzxHxHdCskjuFMa9PjSoz8cMbgyeUFa53hw6Uh1of0QSWYg7kL-Y4o34zmqp7AqebjywfmQUyaSH6Z61ELZo3nwjah6Ip9TbJ9wEZ-PtJM6hJwOnTxypnjEH1WbCqfgG19gN0X6IbmyFL2Oa6hcNF3A_kFHkUiPijw-oSweH_ma4lzgR6iSCj9ySqEO3oa3KVGRPFqI93Be_LiuoPphHlne41KEHmmOTtKH_qBGiuiO93iPU0mSo6R0pFEeQ56MSEmPK0sDn8iPS4TyLYcjHpcCR5XwYz_6o0lF5EQnNLlu7Go8hBkP7YkQHqeHPjs-Jlk4fDsYMgjzMoXeI2i5HN11_EeoZ4d9aOVw5rifoA9S6XhrPAx66XhAK8GXI8yZCj00mYefo1Ue9NngaYpgPUe9sfihVQ_8jLiEx4GfiYMZzUN59MnR6B70gLtElFOObxFCojLCpBp0xsiPM9fR_Ogb_KieCmF-Qb-NMA9R3gifQ3wspNcefLi2osxIgc8SBm-E5iOmMVke5NaRVLnRvEaPfgMuYboiGwx_mDlmZvBx0XiY53CI8Lgk6FGW42IaNI8norj84VsL_eiPRg2qwdcEreSRCyUPH32D7yh5mAi5MEi-HXuM6-BzXEebpgCDnKCMEW-AEMEAAwUVTgoirCGWOQMFVIIQ4rRwCigqBAFGKEEMkJAIBCgjwBACkKBAGUQEIQoAQ4AiAADrjFNIa0CIcEQRcYoAhBDniATACEAJAoRIwRQVBlrCBABEASuUgoICIYGhAjISHBIMWEIoUMQZRwkAQClklIYAEAAoIQgBCggRggFhBKHAKCGAII4wIQgjDghAgBEKACSJBE4ogoBAiBEDCCBOAEIEEEQRyYABWBAJDFYECgKAIAggAVQkQgqDGACEAGAEQMYIIgQhABgErEAEAGKhYoKA5phwJAkiDBVACYoEAYgJRSwwwRhliACMMCEEkMAYJIAGABEhEHAACCMAYFA4hgQQhECiCBUAMGEIJIYBYYgpAIBkpGBUGcOQYcIgJgQgRgBChBCCMaGYA9YwgIQwwADCBAGIAsAQIwYIB5AQRQhAFASOECMMUQQAYIAi0ggADhEIIAAIdUgwQARQwhAFCQDKCUccAQQxwgQwBBIgiALCASaUUIJICpBSjBghKONAEAcUEkIYBoESwDGFkFJAFaIFQEA5YAESRBAFhFGOEyWcMJJEQZAVnQhhgHBMAKQUQAABZAB1RBgAkAIAGYMoUAQRIwRSBhgCMUOAMQgEEUZAYBBgRjAyGBLCEUAcE0IYAoQgxjghgAILKQEFMcIBJYkhQiBEkFHAA6AEENwpA5whRAAjmABESIKkMAIwwxARhCCCFEACAeOEAEIQZqxgggBiACDYESUIYAwIBY0DDBkFgJACEIQMEMAwAYQCRlDNADGAA0CRNUAAZZgQQBCEhCMIEImQYYYIZBhSBjiCEFKSMAGMYEohAYUBwAjJBCCAAQAEEAYAQyQDAAkMmBCmCUAAEkgRQKASiAICCIAGAQQsAQQR4AgSQBAkADIAIEIAAEIAYIEDThCFgBGkAIcAIUAZxgBA1AqnDIEIKUGAAA|e9cdc4f6-502d-4e71-be15-daf28c3c3b75|eb5b111a-2570-3d64-ac06-4d98a2e0cfa3|B000003JGL|BCD 4061|Latn|eng|US|Official|CD|||||4.03|0.271854341033936|3.98|0.343863606445312|||1996|10|25|A|148.292789115646|246384|MP3|44100|0|2|1572532465.0|1565601785.38292|||||0||
```
Item attributes:

```
sqlite> SELECT * FROM item_attributes WHERE entity_id=24359;
id|entity_id|key|value
283224|24359|track_alt|7
283225|24359|data_source|MusicBrainz
289557|24359|danceable|0.997491121292
289558|24359|gender|female
289559|24359|genre_rosamerica|roc
289560|24359|mood_acoustic|0.00431328406557
289561|24359|mood_aggressive|0.0684177577496
289562|24359|mood_electronic|0.131961241364
289563|24359|mood_happy|0.324560582638
289564|24359|mood_party|0.824433743954
289565|24359|mood_relaxed|0.0175035130233
289566|24359|mood_sad|0.19813759625
289567|24359|moods_mirex|Cluster3
289568|24359|rhythm|ChaChaCha
289569|24359|tonal|0.927591860294
289570|24359|timbre|bright
289571|24359|voice_instrumental|voice
289572|24359|average_loudness|0.913285017014
289573|24359|chords_changes_rate|0.0290482081473
289574|24359|chords_key|A
289575|24359|chords_number_rate|0.00216316431761
289576|24359|chords_scale|major
289577|24359|key_strength|0.739266455173
```

---

I deliberately imported a second item from this artist in my collection to be sure that this item (with id `746`) is faulty. Because listing `Little Simz` and sorting by rating works when only one item is in the result set.

```
$ beet ls Simz
Little Simz -  - Dead Body
Little Simz feat. BADBADNOTGOOD - Stillness in Wonderland (Deluxe Edition) - Our Conversations
$ beet ls Simz rating-
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/beet", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1267, in main
    _raw_main(args)
  File "/usr/lib/python3.7/site-packages/beets/ui/__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.7/site-packages/beets/ui/commands.py", line 1072, in list_func
    list_items(lib, decargs(args), opts.album)
  File "/usr/lib/python3.7/site-packages/beets/ui/commands.py", line 1067, in list_items
    for item in lib.items(query):
  File "/usr/lib/python3.7/site-packages/beets/dbcore/db.py", line 701, in __iter__
    objects = self.sort.sort(list(self._get_objects()))
  File "/usr/lib/python3.7/site-packages/beets/dbcore/query.py", line 885, in sort
    return sorted(objs, key=key, reverse=not self.ascending)
TypeError: '<' not supported between instances of 'float' and 'str'
```

---

> I'm not sure that will actually tell us the types of the values, but worth a shot?

Accessing the database via `django` and doing a `type()` on the value will return a string. Guess it does that because the sqlite-column is declared as `TEXT`?

**Comment by sampsyo** [comment]
Thanks! I notice that, in this example, the second item (the one that doesn't cause a problem) is missing the `rating` field altogether. Here's my diagnosis of what's going wrong. This line gets the value for `rating` from the object:
https://github.com/beetbox/beets/blob/a9b19e16784ac5ee743ac67aae6531423e13cbb7/beets/dbcore/query.py#L880

To avoid crashing when the value is missing, it gives a default value for the lookup. That default value is `''`, so everything is fine if the value is a string, but if the field is *typed* as an integer (as it is because you have the mpdstats plugin enabled), then the `sorted` that appears later on:
https://github.com/beetbox/beets/blob/a9b19e16784ac5ee743ac67aae6531423e13cbb7/beets/dbcore/query.py#L885

Will try to compare `''` against an actual float. The right things to do might include:

- Change the `get` to retrieve a sensible type-specific default value. (Our dbcore types do all have default "null" values, so this should be possible.)
- Switch from using a "key" function for the sort to using a "compare" function that specifically detects missing values and sorts them to be beginning or the end.

**Comment by rain0r** [comment]
Thanks for the hints. I got it working with a small scratch:

```
    def get(self, key, default=None):
        """Get the value for a given key or `default` if it does not
        exist.
        """
        if key in self:
            return self[key]
        else:
          from beets.dbcore.types import Float, Integer
          field_type = self._type(key)
          if isinstance(field_type, Float):
            return float(0)

          if isinstance(field_type, Integer):
            return int(0)

          return default
```

What do you think of it?

**Comment by sampsyo** [comment]
Cool! This is a good first step! We should avoid hard-coding the solution to work only for a baked-in set of types, though (float, int, and string). Fortunately, those `Type` objects have a field called `null` that provides a sensible default—0 for int and 0.0 for float, for example. So just getting `self._type(key).null` should probably do it, at least for most types we care about…

In the future, you can imagine a more complete solution would delegate the comparison to the `Type` class entirely. That is, there would be a `cmp` method on `Type` that decides how to order things.
