### ISSUE TITLE
lastimport always ends in a backtrace

### ISSUE THREAD

**Issue by DjSlash** [beetbox/beets#3466]
### Problem

I'm trying to get the play counts from last.fm with lastimport. I have upgraded pylast to their latest release (3.2.0). I've been playing with `retry_limit` and `per_page` (from 50 to 1000) to no avail. I've created an `api_key` on last.fm and used that (which made me adjusting lastimport a  bit to also include the `api_secret`). Sometimes the import runs a bit longer, but in most cases it crashes after a few pages. 

Not sure what to try next.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv lastimport
```

Led to this problem:

```
lastimport: Acquired 969/1000 play-counts (31 unknown)
lastimport: Querying page #2/48...
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/share/beets/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/share/beets/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/share/beets/beetsplug/lastimport.py", line 49, in func
    import_lastfm(lib, self._log)
  File "/usr/share/beets/beetsplug/lastimport.py", line 133, in import_lastfm
    tracks, page_total = fetch_tracks(user, page_current + 1, per_page)
  File "/usr/share/beets/beetsplug/lastimport.py", line 176, in fetch_tracks
    user_obj.get_top_tracks_by_page(limit=limit, page=page)
  File "/usr/share/beets/beetsplug/lastimport.py", line 109, in get_top_tracks_by_page
    "getTopTracks", "track", pylast.Track, params, cacheable)
  File "/usr/share/beets/beetsplug/lastimport.py", line 71, in _get_things
    self.ws_prefix + "." + method, cacheable, params)
  File "/usr/local/lib/python3.7/dist-packages/pylast/__init__.py", line 1118, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/usr/local/lib/python3.7/dist-packages/pylast/__init__.py", line 951, in execute
    response = self._download_response()
  File "/usr/local/lib/python3.7/dist-packages/pylast/__init__.py", line 940, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/local/lib/python3.7/dist-packages/pylast/__init__.py", line 970, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Operation failed - Most likely the backend service failed. Please try again.
```

### Setup

* OS: Debian testing (bullseye)
* Python version: 3.7.6
* beets version: 1.4.9
* pylast version: 3.2.0 (installed with pip)
* Turning off plugins made problem go away (yes/no): didn't try, this error is clearly not related to other plugins

My configuration (output of `beet config`) is:

```yaml
importfeeds:
    relative_to: !!binary |
        L2RhdGEvTXV6aWVr
    dir: /data/Muziek/.mpd
    formats: []
    m3u_name: imported.m3u
    absolute_path: no

musicbrainz:
    pass: REDACTED
    user: DjSlash
library: ~/.beets.db
directory: /data/Muziek/

plugins:
- convert
- duplicates
- fromfilename
- fuzzy
- importfeeds
- info
- inline
- lastgenre
- lastimport
- mbcollection
- mbsubmit
- mbsync
- mpdstats
- mpdupdate
- random
- scrub
- the
- zero                  
include: [mbpasswd.yaml]

replace:
    '[\\/]': ''
    ^\.: ''
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    \s+$: ''
format_album: $albumartist - $original_year - $album

sort_album: albumartist+ original_year+ album+
per_disc_numbering: yes

import:
    from_scratch: yes
    log: ~/beets.log

match:
    preferred:
        original_year: yes

paths:
    default: albums/%the{$albumartist}/%if{$original_year,$original_year - ,$year - }$album%if{$multidisc, (disc$disc$cdtitle)}%if{$notalbum, $cdtype}%aunique{original_year albumartist album}/$track - $artist - $title
    comp: albums/000 Various Artists/%if{$original_year,$original_year - ,$year - }$album%if{$multidisc, (disc$disc$cdtitle)}%if{$notalbum, $cdtype}%aunique{original_year albumartist album}/$track - $artist - $title
    singleton: singles/$initial/$artist - $title
item_fields:
    cdtitle: u' - %s' % (disctitle) if disctitle else u''
    multidisc: 1 if disctotal > 1 else 0
    initial: artist.lower().lstrip('[]*')[0]
album_fields:
    cdtype: u'[%s]' % (albumtype.lower()) if albumtype else u''
    notalbum: 0 if albumtype and albumtype.lower() == 'album' else 1
the:
    a: no
    the: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
lastgenre:
    canonical: yes
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
lastfm:
    user: DjSlash
    api_key: REDACTED
    api_secret: REDACTED
lastimport:
    retry_limit: 5
    per_page: 1000
mbcollection:
    collection: Beet
    auto: no
    remove: no
mpd:
    host: osmc
    port: 6600
    music_directory: /data/Muziek
    rating: yes         
    rating_mix: 0.75
    password: REDACTED
convert:
    never_convert_lossy_files: yes
    command: avconv -i $source -qscale:a 0 $dest
    extension: mp3

    paths:
        default: $artist - $title
    dest:
    pretend: no
    threads: 2
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    max_bitrate: 500
    auto: no
    tmpdir:
    quiet: no
    embed: yes
    no_convert: ''
    copy_album_art: no
    album_art_maxwidth: 0
replaygain:
    backend: audiotools
zero:
    fields: lyrics
    update_database: yes
    auto: yes
    keep_fields: []
mbsubmit:
    format: $track. $title - $artist ($length)
    threshold: medium
pathfields: {}
scrub:
    auto: yes
fuzzy:
    prefix: '~'
    threshold: 0.7
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
   tiebreak: {}
    strict: no
    tag: ''
```

**Comment by DjSlash** [comment]
Hmm, it magically resolved itself. I started it again, just for luck and when I looked this morning, it finished without error! :tada:

**Comment by sampsyo** [comment]
Huh! Glad it resolved itself… the server must have been down, I suppose. Maybe we should catch the exception and print a friendly error message?

**Comment by DjSlash** [comment]
That's why I was using pylast 3.2.0, there was pylast/pylast#297 merged, I hoped that at least I'd see more than just "_Most likely the backend service failed_".
