### ISSUE TITLE
Error in Type comparison of Flexible Fields declared by plugins

### ISSUE THREAD

**Issue by adamjakab** [beetbox/beets#3520]
### Problem

When activating two plugins which [declare the type for a flexible field](https://beets.readthedocs.io/en/stable/dev/plugins.html#flexible-field-types), beets exits with the following exception:

```bash
Traceback (most recent call last):
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/ui/__init__.py", line 1148, in _setup
    library.Item._types.update(plugins.types(library.Item))
  File "/Users/jackisback/opt/miniconda3/envs/beetsdevel/lib/python3.7/site-packages/beets/plugins.py", line 344, in types
    u'another type.'.format(plugin.name, field)
beets.plugins.PluginConflictException: Plugin acousticbrainz defines flexible field average_loudness which has already been defined with another type.
```

The above error can be reproduced by activating any two plugins (one example is`acousticbrainz`) which declare flexible fields like the code snippet below:

```python
item_types = {
        'average_loudness': types.Float(6)
}
```

The expected behaviour is that two plugins which declare the same field with the same type (for example: `types.Float()`) should be able to co-exist.

The actual behaviour is that beets exits with:

> beets.plugins.PluginConflictException: Plugin acousticbrainz defines flexible field average_loudness which has already been defined with another type.

The type comparison here seems to be wrong:

https://github.com/beetbox/beets/blob/b34d1f71a93b3663f70f46a4d5ed08702b14c5ca/beets/plugins.py#L342

because it compares the actual instances instead of their types.

**Comment by sampsyo** [comment]
Thanks! The solution here is to make dbcore types comparable, as I mentioned in this forum post:
https://discourse.beets.io/t/query-parsing-numeric-flex-attributes/1160/7?u=adrian

**Comment by adamjakab** [comment]
Quick note/explanation: the method in question is here:
https://github.com/beetbox/beets/blob/8ed76f1198c23b9205c6f566860a35569945d4bb/beets/plugins.py#L335
and it is being tested here:
https://github.com/beetbox/beets/blob/8ed76f1198c23b9205c6f566860a35569945d4bb/test/test_plugins.py#L128

However, it is being tested with `types.INTEGER´ refering to the the same class instance:
```python
    def test_match(self):
        class EventListenerPlugin(plugins.BeetsPlugin):
            item_types = {'duplicate': types.INTEGER}

        class AdventListenerPlugin(plugins.BeetsPlugin):
            item_types = {'duplicate': types.INTEGER}

        self.event_listener_plugin = EventListenerPlugin
        self.advent_listener_plugin = AdventListenerPlugin
        self.register_plugin(EventListenerPlugin)
        self.register_plugin(AdventListenerPlugin)
        self.assertNotEqual(None, plugins.types(Item))
```
so it passes. When duplicating the above test and using `types.Integer()` like this:
```python
    def test_match_instances(self):
        class EventListenerPlugin(plugins.BeetsPlugin):
            item_types = {'duplicate': types.Integer()}

        class AdventListenerPlugin(plugins.BeetsPlugin):
            item_types = {'duplicate': types.Integer()}

        self.event_listener_plugin = EventListenerPlugin
        self.advent_listener_plugin = AdventListenerPlugin
        self.register_plugin(EventListenerPlugin)
        self.register_plugin(AdventListenerPlugin)
        self.assertNotEqual(None, plugins.types(Item))
```
the test fails.
