### ISSUE TITLE
Problem with Lyrics

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3649]
When I launch beet lyrics, after some output it gives me:

________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 747, in func
    opts.force_refetch or self.config['force'],
  File "/usr/local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 840, in fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/usr/local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 840, in <listcomp>
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/usr/local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 873, in get_lyrics
    lyrics = backend.fetch(artist, title)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 403, in fetch
    return self.lyrics_from_song_api_path(song_api_path)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/lyrics.py", line 375, in lyrics_from_song_api_path
    lyrics = html.find("div", class_="lyrics").get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
________________________________________________________________________________________________________

What is it?

Thank you

**Comment by sampsyo** [comment]
Please see #3535.

**Comment by entuccio** [comment]
Sorry for my duplicate. I read the post, but how can I solve this? I didn't understand :-( sorry mate

**Comment by sampsyo** [comment]
The bug is fixed on master. There is an FAQ about running from source.
