### ISSUE TITLE
Crash at start in Debian unstable

### ISSUE THREAD

**Issue by s1shed** [beetbox/beets#3657]
Beets now crashes when trying to do anything. It was probably caused by an update to some system packages. Another user filed a [bug with Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964245). The user says he was able to resolve it by downgrading the python package but I note my python version is not the (allegedly) buggy one.

I've tried renaming the config directory to rule out problems with my configuration/plugins but this did not help.

I'm filing this bug not yet knowing where the problem lies.

### Problem

Running this command in verbose (`-vv`) mode:
```sh
beet -vv ls anything 
beet config
```

Led to this problem:

```
no user configuration found at /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/share/beets/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/share/beets/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/share/beets/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/share/beets/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/share/beets/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/share/beets/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/share/beets/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/share/beets/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/share/beets/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

### Setup

* OS:  Debian unstable
* Python version:  3.8.3 (Debian package: python3, version 3.8.2-3)
* beets version: 1.4.9 (both the debian package and one from a venv)
* Turning off plugins made problem go away (yes/no): no.

**Comment by s1shed** [comment]
I cannot reproduce the problem with the current master branch (cb668ccdab86855986dcff6b8da7b011d0d5b74c) but I can with v1.4.9.

**Comment by sampsyo** [comment]
Please see #3621.
