### ISSUE TITLE
ValueError: Name node can't be used with 'None' constant

### ISSUE THREAD

**Issue by Nick6** [beetbox/beets#3686]
Beets crashes with the following error message 

### Problem

Running this command in verbose (`-vv`) mode:

D:\Scripts>beet -vv
no user configuration found at C:\Users\Nick\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Nick\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
Traceback (most recent call last):
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\ui\__init__.py", line 1266, in main
    _raw_main(args)
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\ui\__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\ui\__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\ui\__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\ui\__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\util\functemplate.py", line 571, in template
    return Template(fmt)
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\util\functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\util\functemplate.py", line 614, in translate
    func = compile_func(
  File "C:\Users\Nick\AppData\Roaming\Python\Python38\site-packages\beets\util\functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
Led to this problem:

```
ValueError: Name node can't be used with 'None' constant
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Windows 10
* Python version: Python 3.8.5
* beets version: Latest
* Turning off plugins made problem go away (yes/no): No

**Comment by sampsyo** [comment]
Please see #3674.
