### ISSUE TITLE
Any command results in Traceback

### ISSUE THREAD

**Issue by WatermelonDriveway** [beetbox/beets#3696]
Can't seem to get beets to do anything after a system restore.  Any command leads to the same traceback error.  Plugins disabled, reinstalled python, pip, and beets.  Not sure what I could be doing wrong here.

```
╰─➤   ~ beet -vv
user configuration: /Volumes/home/jonny/.config/beets/config.yaml
data directory: /Volumes/home/jonny/.config/beets
plugin paths:
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
╰─➤   ~
```

### Setup

* OS: macOS 10.14.6
* Python version: 3.8
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is: the same traceback error, but my actual config is:

```
directory: /Volumes/data/flac
library: ~/.beets/musiclibrary.blb

original_date: yes


paths:
   default: $albumartist/($original_year) $album/$track - $title
   comp: Various Artists/($original_year) $album/$track - $title

import:
   timid: no
   write: yes
   per_disc_numbering: yes

match:
  strong_rec_thresh: 0.01



#plugins: mpdupdate zero discogs web copyartifacts 

#fetchart:
#   auto: yes
#   minwidth: 500
#   enforce_ratio: yes
#   sources: coverart itunes amazon albumart google fanart *
#   fanarttv_key: 7caa0baa5b3fa19619d8798870a42b3c

#zero:
#  fields: original_month original_day month day
#  update_database: true

#copyartifacts:
#    extensions: .log .LOG .cue .CUE .jpg .jpeg .png
```

```
╰─➤   ~ brew install python
==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.5.mojave.bottle.tar.gz
Already downloaded: /Volumes/home/jonny/Library/Caches/Homebrew/downloads/de7f5080226b1adf791bf431f04e17653c464823ed2bf587a577ce57f86ca735--python@3.8-3.8.5.mojave.bottle.tar.gz
==> Pouring python@3.8-3.8.5.mojave.bottle.tar.gz
==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-
==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-
==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.8/3.8.5: 4,331 files, 66.8MB
╰─➤   ~ sudo easy_install pip
Password:
Searching for pip
Best match: pip 20.2
Processing pip-20.2-py2.7.egg
pip 20.2 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /Library/Python/2.7/site-packages/pip-20.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
╰─➤   ~ pip3 install beets
Processing ./Library/Caches/pip/wheels/89/72/aa/6a3cdc4bf5c388806f3ac2faebf5a9bd765bfa55ba4ab4b480/beets-1.4.9-py3-none-any.whl
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/site-packages (from beets) (5.3.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/site-packages (from beets) (1.15.0)
Requirement already satisfied: mutagen>=1.33 in /usr/local/lib/python3.8/site-packages (from beets) (1.45.0)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/local/lib/python3.8/site-packages (from beets) (0.7.1)
Requirement already satisfied: jellyfish in /usr/local/lib/python3.8/site-packages (from beets) (0.8.2)
Requirement already satisfied: unidecode in /usr/local/lib/python3.8/site-packages (from beets) (1.1.1)
Requirement already satisfied: munkres>=1.0.0 in /usr/local/lib/python3.8/site-packages (from beets) (1.1.2)
Installing collected packages: beets
Successfully installed beets-1.4.9
╰─➤   ~ beet ls test
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
╰─➤   ~
```

Thanks.

**Comment by jackwilsdon** [comment]
Please see #3674.
