### ISSUE TITLE
MusicBrainz Error

### ISSUE THREAD

**Issue by DOFfactory** [beetbox/beets#3697]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet import *
```

Led to this problem:

```
Tagging:
    Earth, Wind & Fire - Faces
URL:
    https://musicbrainz.org/release/a81ac656-f6d2-4b7d-be7a-31ddcd29414c
(Similarity: 100.0%) (CD, 1989, US, Columbia, CGK 36795)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 598, in substitute
    res = self.compiled(values, functions)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 622, in wrapper_func
    args[VARIABLE_PREFIX + varname] = values[varname]
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 415, in __getitem__
    value = self._get(key)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 406, in _get
    return self._get_formatted(self.model, key)
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 81, in _get_formatted
    value = model._type(key).format(model.get(key))
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 443, in get
    return self[key]
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 354, in __getitem__
    return getters[key](self)
  File "/usr/lib/python3.8/site-packages/beetsplug/lidarrfields.py", line 25, in _tmpl_releasegroupartist
    rel = musicbrainzngs.get_release_group_by_id(item.mb_releasegroupid, ['artist-credits'])
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 890, in get_release_group_by_id
    return _do_mb_query("release-group", id, includes, params)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 358, in run
    self.coro.send(msg)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 1540, in manipulate_files
    task.manipulate_files(
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 738, in manipulate_files
    item.move(operation)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 811, in move
    dest = self.destination(basedir=basedir)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 873, in destination
    subpath = self.evaluate_template(subpath_tmpl, True)
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 601, in evaluate_template
    return template.substitute(self.formatted(for_path),
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 600, in substitute
    res = self.interpret(values, functions)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 592, in interpret
    return self.expr.evaluate(Environment(values, functions))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 282, in evaluate
    out.append(part.evaluate(env))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 184, in evaluate
    if self.ident in env.values:
  File "/usr/lib/python3.8/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 415, in __getitem__
    value = self._get(key)
  File "/usr/lib/python3.8/site-packages/beets/library.py", line 406, in _get
    return self._get_formatted(self.model, key)
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 81, in _get_formatted
    value = model._type(key).format(model.get(key))
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 443, in get
    return self[key]
  File "/usr/lib/python3.8/site-packages/beets/dbcore/db.py", line 354, in __getitem__
    return getters[key](self)
  File "/usr/lib/python3.8/site-packages/beetsplug/lidarrfields.py", line 25, in _tmpl_releasegroupartist
    rel = musicbrainzngs.get_release_group_by_id(item.mb_releasegroupid, ['artist-credits'])
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 890, in get_release_group_by_id
    return _do_mb_query("release-group", id, includes, params)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Linux 
* Python version: 3.8.2
* beets version: 1.4.9 (dockerized: linuxserver/beets)
* Turning off plugins made problem go away (yes/no): n/a

**Comment by sampsyo** [comment]
Hello! When you report a problem, it *really* helps us if you use the issue template. In particular, please include your configuration and try disabling plugins.

**Comment by DOFfactory** [comment]
Hi @sampsyo, thanks for the suggestion. I tried to follow the template as much as I was able to, however, it is indeed unknown to me, whether this is caused by a plugin or not. The thing is that I use beets _because_ of all the plugins. If I disable them, my config will not work properly, giving a false impression that the issue is not there. 

Given the error, I suspect the issue is with reaching MusicBrainz servers (`musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request`) with at least one of the python scripts (maybe `File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 497`). This does not look like an issue with a plugin, as I tried separately to run the `beet mbsync` command (the only plugin linked with MusicBrainz, see config below), and it did not end in error. I also tried to run the `beet import` on different folders, and the error is always the same.

Please also note that the file `beet.log` does not provide any further details on the error.

For further info, please find below my config: 

```
plugins: chroma copyartifacts edit embedart fetchart fromfilename fuzzy info inline lastgenre lidarrfields mbsync replaygain scrub web zero
directory: /music
library: /config/musiclibrary.blb
art_filename: folder # results in "folder.jpg"
max_filename_length: 0 # unlimited

# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no

# use the release-date of the original (first) realase of an album?
original_date: yes

# on multi-disk releases, assign track numbers for the whole album
# if "per disk", make sure tracknames do not collide ("paths" setting)
per_disc_numbering: yes

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg", ".cue"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]

# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8
bell: yes

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# Paths ----------------------------------------------------------------------

item_fields:
    first_artist: albumartist.split(', ',1)[0:1][0]
    disc_and_track: u'CD%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)
    disc_alt: u'CD%02i - ' % (disc) if disctotal > 1 else ''

album_fields:
    first_artist: albumartist.split(', ',1)[0:1][0]

# Paths and filenames for music files
# relative to music directory
# Done in order listed. Default is special and will always go at the end.

paths:
    # special cases
    label:ECM: 'ECM/[${catalognum}] - ${albumartist} - ${album}%if{%aunique{}, %aunique{}}/${disc_alt}${albumartist} - ${track} - ${artist} - ${title}'
    # generic, using beets-lidarr-fields [$releasegroupartist]
    default: '$releasegroupartist/${year} - ${album}%if{%aunique{}, %aunique{}}/${disc_alt}${albumartist} - ${track} - ${artist} - ${title}'
    singleton: '$releasegroupartist/Singles/${year} - ${album}/${disc_and_track} - ${title}'
    'series_name::.': 'Series/$series_name/$releasegroupartist/$year - $album%if{%aunique{}, %aunique{}}/${disc_alt}${albumartist} - ${track} - ${artist} - ${title}'
    compilation: 'VA/${album}%if{%aunique{}, %aunique{}}/${disc_and_track} - ${artist} - ${title}'
    albumtype:soundtrack: 'Soundtracks/${album} (${year})/$releasegroupartist - ${disc_and_track} - ${title}'
    albumtype:audiobook: Audiobooks/$artist/$album%aunique{}/%if{$multidisc,CD $disc/}$track - $title

copyartifacts:
    extensions: .txt .pdf .log .cue .png .jpg
    print_ignored: yes

# Convert ---------------------------------------------------------------------
# convert:
# auto: yes
#    copy_album_art: yes
#    album_art_maxwidth: 600
#    dest: /mnt/3TB-Drive-01/Audio/Music [Mobile version]/
#    embed: yes
#    never_convert_lossy_files: yes
#    format: opus
#    formats:
#        opus:
#            command: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
#            extension: opus.ogg
            # Above is to work around android media scanner, opus is included
            # in the file extension for making it easier on me in the future
            # when android media scanner picks up opus extensions properly

import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    copy: yes
    move: no
    delete: no

    # use auto-tagging where possible
    autotag: yes
    timid: no

    resume: ask
    incremental: no
    none_rec_action: ask

    quiet: no # enable with command line option
    quiet_fallback: skip
    default_action: apply

    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    cover_names:
        - front
        - cover
        - album
        - folder
        - art
    sources:
        - filesystem
        - coverart: releasegroup

replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: ['CD', 'Vinyl', 'Digital Media|File']
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

# null fields in files’ metadata tags

zero:
  update_database: true
  fields: comments images
  comments:
    - EAC
    - LAME
    - from.+collection

# MusicBrainz ID ------------------------------------------------------------
```

I would be extremely grateful for a fix as currently this error hinders me in using beets.

**Comment by sampsyo** [comment]
> it is indeed unknown to me, whether this is caused by a plugin or not. The thing is that I use beets _because_ of all the plugins. If I disable them, my config will not work properly, giving a false impression that the issue is not there.

Indeed! The idea with that question is the template is not to say that we don't handle bugs that have to do with plugins—but to find out which plugin might have the bug! If the bug goes away when you disable a given plugin, we know it's there.

In particular, looks like you're using `lidarrfields`. Could it be that?

**Comment by DOFfactory** [comment]
Thanks guys, the culprit is indeed with `lidarrfields`. As you can see from the config, I try to have a single artist folder structure, and instead of the usual hack I tried the `releasegroupartist` field. Obviously, it is not working properly. Closing.
