### ISSUE TITLE
Beets fails raison ValueError

### ISSUE THREAD

**Issue by jabossu** [beetbox/beets#3698]
Hello dear dev team ! :wave: 

Beets doesn't work anymore on my systrem : whenever I run it, no matter what arguments I give the command, a python error is raised and it fails (see output below). :disappointed: 
- The command always fails. 
- Just using the command with no argument fails in the same way. 
- The error is always the same.

### Problem

Running this command in verbose (`-vv`) mode:

```
$ beet -vv
user configuration: /home/jack/.config/beets/config.yaml
data directory: /home/jack/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

#### Led to this problem:

In my (profane) opinion, this might be because of an update in my system. :thinking: 
I had to update youtube-dl, and beets started failing immediately after that update. Being running Archlinux, I think my system is using a recent version of a dependency that beet cannot handle. (maybe ?)

:bookmark_tabs:  Here is the log of that update : 
```
[2020-07-28T14:49:23+0300] [PACMAN] Running 'pacman -Syu'
[2020-07-28T14:49:23+0300] [PACMAN] synchronizing package lists
[2020-07-28T14:49:25+0300] [PACMAN] starting full system upgrade
[2020-07-28T14:49:44+0300] [ALPM] transaction started
[2020-07-28T14:49:44+0300] [ALPM] upgraded dotnet-host (3.1.3.sdk103.2-1 -> 3.1.6.sdk106-1)
[2020-07-28T14:49:45+0300] [ALPM] upgraded dotnet-runtime (3.1.3.sdk103.2-1 -> 3.1.6.sdk106-1)
[2020-07-28T14:49:45+0300] [ALPM] upgraded intel-gmmlib (20.2.2-1 -> 20.2.3-1)
[2020-07-28T14:49:46+0300] [ALPM] upgraded python (3.8.3-1 -> 3.8.4-1)
[2020-07-28T14:49:46+0300] [ALPM] upgraded python-cffi (1.14.0-3 -> 1.14.1-1)
[2020-07-28T14:49:46+0300] [ALPM] upgraded python-ordered-set (3.1.1-2 -> 4.0.2-1)
[2020-07-28T14:49:46+0300] [ALPM] upgraded python-cryptography (2.9.2-1 -> 3.0-1)
[2020-07-28T14:49:46+0300] [ALPM] upgraded youtube-dl (2020.06.16.1-2 -> 2020.07.28-1)
[2020-07-28T14:49:47+0300] [ALPM] transaction completed
[2020-07-28T14:49:47+0300] [ALPM] running '30-systemd-update.hook'...
```
:information_source:  And here are the package info for my distro : 
````
$ pacman -Qi beets
Name            : beets
Version         : 1.4.9-3
Description     : Flexible music library manager and tagger
Architecture    : any
URL             : https://beets.io/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-jellyfish  python-munkres  python-musicbrainzngs  python-mutagen  python-setuptools
                  python-six  python-unidecode  python-yaml
Optional Deps   : bash-completion: Bash completion [installed]
                  bs1770gain: ReplayGain plugin
                  ffmpeg: Convert plugin [installed]
                  gst-plugins-bad: Chromaprint/Acoustid, BPD, ReplayGain plugins
                  gst-plugins-good: Chromaprint/Acoustid, BPD, ReplayGain plugins [installed]
                  gst-plugins-ugly: Chromaprint/Acoustid, BPD, ReplayGain plugins
                  gst-libav: Chromaprint/Acoustid, BPD, ReplayGain plugins
                  gst-python: Chromaprint/Acoustid, BPD, ReplayGain plugins
                  imagemagick: Thumbnails plugin [installed]
                  python-beautifulsoup4: Lyrics plugin
                  python-flask: Web plugin
                  python-gobject: ReplayGain plugin
                  python-mpd2: MPDStats plugin
                  python-pyacoustid: Chromaprint/Acoustid plugin [installed]
                  python-pylast: LastGenre plugin [installed]
                  python-requests: Chromaprint/Acoustid, BPD, FetchArt plugins [installed]
                  python-xdg: Thumbnails plugin [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3.47 MiB
Build Date      : Tue 24 Mar 2020 02:42:10 PM EET
Install Date    : Fri 17 Jul 2020 05:07:22 PM EEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

````
#### Here's a link to the music files that trigger the bug (if relevant):
No music in particular : beets fails to run, no matter what arguments I give it.

#### About my system :
* **OS**: Archlinux - up to date
* **Python** version: 3.8.5
* **beets** version: 1.4.9-3
* Turning off plugins made problem go away (yes/no): No

#### My configuration is:

```$ cat .config/beets/config.yaml
directory: ~/music
library: ~/.data/musiclibrary.db
import:
 move: yes
plugins: inline convert chroma fetchart embedart edit lastgenre
acoustid:
 apikey: <APIKEY>
convert:
 auto: yes
 format: ogg
```
:exclamation:  `beet config` not being able to run, I copy pasted my config file. I hope it's fine, if i'm missing informartion please tell me how to provide them :smile:

**Comment by wisp3rwind** [comment]
Please see https://github.com/beetbox/beets/issues/3674
