### ISSUE TITLE
Beet 1.4.9-3 unusable on Archlinux after update

### ISSUE THREAD

**Issue by PurpleAzurite** [beetbox/beets#3718]
### Problem

Updating beets to this version on Arch

Led to this problem:

```
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

Here's a link to the music files that trigger the bug (if relevant): N/A

### Setup

* OS: Archlinux
* Python version: 3.8
* beets version: 1.4.9-3
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```
  1 directory: /media/External-2/files.music
  2 library: /media/Archive-1/databases/database.beets/musiclibrary.db
  3
  4 plugins: fetchart lyrics
  5
  6 import:
  7         move: yes
  8
  9 fetchart:
 10         cautious: true
 11         cover_names: front back
 12         enforce_ratio: yes
 13
 14 lyrics:
 15         auto: no
```

**Comment by sampsyo** [comment]
Please see https://github.com/beetbox/beets/issues/3674.
