### ISSUE TITLE
Multiple error importing music (mainly with lyrics.py it seems)

### ISSUE THREAD

**Issue by Ashish0804** [beetbox/beets#3741]
### Problem
Getting the below mentioned error.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import ./English
```

Led to this problem:

```
Traceback (most recent call last):
  File "/home/ashish/miniconda3/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/importer.py", line 1511, in plugin_stage
    func(session, task)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beets/plugins.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beetsplug/lyrics.py", line 828, in imported
    False, self.config['force'])
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beetsplug/lyrics.py", line 841, in fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beetsplug/lyrics.py", line 841, in <listcomp>
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beetsplug/lyrics.py", line 874, in get_lyrics
    lyrics = backend.fetch(artist, title)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beetsplug/lyrics.py", line 403, in fetch
    return self.lyrics_from_song_api_path(song_api_path)
  File "/home/ashish/miniconda3/lib/python3.7/site-packages/beetsplug/lyrics.py", line 375, in lyrics_from_song_api_path
    lyrics = html.find("div", class_="lyrics").get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'

```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: popos
* Python version: 3.7.7
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    fallback: ''
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    genius_api_key: REDACTED
    force: no
    local: no
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
directory: ~/HDD/Music
library: /home/ashish/.config/beets/musiclibrary.db

plugins: embedart fetchart lyrics scrub

import:
    move: yes
    write: yes
per_disc_numbering: yes
threaded: yes
fetchart:
    midwidth: 400
    enforce_ratio: 10px
    sources: filesystem itunes amazon albumart coverart
    auto: yes
    minwidth: 0
    maxwidth: 0
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
scrub:
    auto: yes

```

**Comment by sampsyo** [comment]
Hello! Please see #3535.

**Comment by Ashish0804** [comment]
> Hello! Please see #3535.

When are we getting a new release? And there are other errors too in the log not related to lyrics.py

**Comment by jackwilsdon** [comment]
@Ashish0804 please see #3625 (it's pinned at the top of the issues list) for information regarding the next release
