### ISSUE TITLE
doesn't start on python3.8

### ISSUE THREAD

**Issue by minusf** [beetbox/beets#3742]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv help
```

Led to this problem:

```
% % beet -vv help
user configuration: /Users/user/.config/beets/config.yaml
data directory: /Users/user/.config/beets
plugin paths:
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

### Setup

* OS: macos 10.15.6
* Python version: 3.8.5
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

```yaml
directory: /music

format_item: $artist - $album - $title - $length - $track

format_album: $albumartist - $album - $year

paths:
  default: %lower{$albumartist/$original_year-$album/$track-$title}

#original_date: yes

match:
  preferred:
    media: ["CD", "Digital Media|File"]
    original_year: yes
  ignored_media: ["Data CD", "DVD", "DVD-Video"]

import:
  from_scratch: yes
  move: yes

replace:
  '\s*&\s*': '-and-'
  '[\\/]': ''
  '[\x00-\x1f]': '-'
  '[<>:,"\?\*\|!#\$]': ''
  '^\.\.': ''
  '\.\.': ''
  '\.$': ''
  '\.\s': '-'
  '\s\.': '-'
  '^\s+': ''
  '\s+$': ''
  '\s': '-'
  '^-': ''
  '-$': ''
  '-\.': '-'
  '[\[\]\(\)]': ''
  "'": ''
  '-_-': '-'
  '---': '-'

asciify_paths: yes

#plugins: edit fetchart ftintitle play scrub random mpdupdate

fetchart:
  sources:
    - filesystem

```

**Comment by sampsyo** [comment]
Please see #3674.
