### ISSUE TITLE
Unable to run new install of beets 

### ISSUE THREAD

**Issue by roberthaverly** [beetbox/beets#3744]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv
```

Led to this problem:

```
user configuration: /Users/[omitted]/.config/beets/config.yaml
data directory: /Users/[omitted]/.config/beets
plugin paths:
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: macOS 10.15.6
* Python version: 3.8
* beets version: Current
* Turning off plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/beets/identified/

import:
  move: no

ui:
  color: yes

musicbrainz:
  searchlimit: 15

paths:
  default: $albumartist - $year - $album ($label [$catalognum])/$albumartist - $track - $title
  comp: Various - $album - $year ($label [$catalognum])/$track - $artist - $title

```

**Comment by jackwilsdon** [comment]
Please see this pinned issue: #3674
