### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by entuccio** [beetbox/beets#3752]
Hello, 

suddenly when i launch beet it says:

-------------------------------------------

** error loading plugin lyrics:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/lyrics.py", line 28, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

** error loading plugin mpdstats:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/mpdstats.py", line 18, in <module>
    import mpd
ModuleNotFoundError: No module named 'mpd'

** error loading plugin fetchart:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/fetchart.py", line 25, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

** error loading plugin lastimport:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/lastimport.py", line 18, in <module>
    import pylast
ModuleNotFoundError: No module named 'pylast'

** error loading plugin lastimport:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/lastimport.py", line 18, in <module>
    import pylast
ModuleNotFoundError: No module named 'pylast'

** error loading plugin lastgenre:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/lastgenre/__init__.py", line 28, in <module>
    import pylast
ModuleNotFoundError: No module named 'pylast'

** error loading plugin ydl:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.ydl'

** error loading plugin discogs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.8/site-packages/beetsplug/discogs.py", line 26, in <module>
    from discogs_client import Release, Master, Client
ModuleNotFoundError: No module named 'discogs_client'

Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant

------------------------------------------- 

I tried:

brew install python (also reinstall)
brew install python3
python3  -m pip install beets
brew install beets
python3  -m pip install --upgrade --force-reinstall beets

Any idea??

**Comment by wisp3rwind** [comment]
The actual traceback is due to a known issue: https://github.com/beetbox/beets/issues/3674 Unfortunately, the fix is not released yet. The failures to load plugins are most likely not an issue with beets, but rather your python installation: Check that all the referenced packages are actually installed for Python 3.8. If you upgraded from a previous major Python release (3.7 or older) that may not be the case.

**Comment by entuccio** [comment]
OMG!

I tried to reinstall python . What else?

**Comment by wisp3rwind** [comment]
See https://beets.readthedocs.io/en/stable/faq.html#run-the-latest-source-version-of-beets on how to run the latest development version until a new version of beets is released.

Those other packages aren't required dependencies for beets, I guess you need to reinstall them manually (assuming they were installed using pip).

**Comment by entuccio** [comment]
Man! You're great!
Uninstalled beets and reinstalled following the documentation and the development version.

(need install every plugin manually, but that's ok)

Works perfectly. Thank you very much
