### ISSUE TITLE
Tests failing on Guix

### ISSUE THREAD

**Issue by tlc28** [beetbox/beets#3771]
### Problem

Hi Beets!

Running tests on Guix fails :

```sh
$ python -m unittest discover -p 'test_*'
$ # or
$ nosetests -v
```

Led to this problem:

```
======================================================================
FAIL: test_read_audio_properties (test.test_mediafile.AIFFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-beets-1.4.9.drv-0/beets-1.4.9/test/test_mediafile.py", line 440, in test_read_audio_properties
    self.assertEqual(getattr(mediafile, key), value)
AssertionError: 16 != 0

======================================================================
FAIL: test_read_audio_properties (test.test_mediafile.WavpackTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-beets-1.4.9.drv-0/beets-1.4.9/test/test_mediafile.py", line 440, in test_read_audio_properties
    self.assertEqual(getattr(mediafile, key), value)
AssertionError: 16 != 0

----------------------------------------------------------------------
Ran 1901 tests in 39.151s

FAILED (SKIP=33, failures=2)
```

### Setup

* OS: Guix
* Python version: 3.8.2
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): -

Regards

**Comment by sampsyo** [comment]
Hello! I believe we have fixed this on master… is there any chance you could give that a shot?

**Comment by tlc28** [comment]
Hi @sampsyo and thank you for responding so quickly.

I can try to run the tests on the code from the master branch, but I won't be able to package it as it not a "stable/tagged" version.
For the time being, I've disabled the 2 tests in the Guix package definition. I'll remove this patch when the next version of beets is out!

Regards
