### ISSUE TITLE
crash after installation

### ISSUE THREAD

**Issue by bmillemathias** [beetbox/beets#3787]
### Problem

I've just install beets in a venv to test it, so I ran 
```sh
$ beet
```

Led to this problem:

```
Traceback (most recent call last):
  File "/home/baptistemm/Code/venv/b33ts/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

### Setup

* OS:  fedora 33
* Python version:  3.9.0
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): n/A

My configuration (output of `beet config`) is:

well :)

```yaml
Traceback (most recent call last):
  File "/home/baptistemm/Code/venv/b33ts/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/home/baptistemm/Code/venv/b33ts/lib/python3.9/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant

```

**Comment by sampsyo** [comment]
See #3674.
