### ISSUE TITLE
ReplayGainPlugin throws false alarm sqlite3.OperationalError in test suite

### ISSUE THREAD

**Issue by ybnd** [beetbox/beets#3809]
### Problem
The tests in `test_replaygain.py` work with an in-memory SQLite database, which doesn't seem to play well with the parallelization introduced in https://github.com/beetbox/beets/pull/3478.

* [`item.store()`](https://github.com/beetbox/beets/blob/8645f56512fa8918fd05c4f53bd1b65ace87ab41/beetsplug/replaygain.py#L1311) raises

    ```
    Exception in thread Thread-90:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        self.run()
      File "/home/ybnd/code/beets/beets/beetsplug/replaygain.py", line 1198, in run
        six.reraise(exc[0], exc[1], exc[2])
      File "/home/ybnd/.local/share/venve/beets/lib/python3.8/site-packages/six.py", line 703, in reraise
        raise value
      File "/home/ybnd/code/beets/beets/beetsplug/replaygain.py", line 1510, in wfunc
        return func(*args, **kwargs)
      File "/home/ybnd/code/beets/beets/beetsplug/replaygain.py", line 1460, in _store_track
        store_track_gain(item, track_gains[0])
      File "/home/ybnd/code/beets/beets/beetsplug/replaygain.py", line 1324, in store_track_gain
        self._store(item)
      File "/home/ybnd/code/beets/beets/beetsplug/replaygain.py", line 1319, in _store
        item.store()
      File "/home/ybnd/code/beets/beets/beets/library.py", line 347, in store
        super(LibModel, self).store(fields)
      File "/home/ybnd/code/beets/beets/beets/dbcore/db.py", line 516, in store
        tx.mutate(query, subvars)
      File "/home/ybnd/code/beets/beets/beets/dbcore/db.py", line 838, in mutate
        cursor = self.db._connection().execute(statement, subvals)
    sqlite3.OperationalError: no such table: items
    ```

  on the first call, **but just succeeds on the second call**

* Occurs on every call to `item.store()`
* Doesn't depend on the ReplayGain backend you use

### Reproducing

1. Make sure `test_replaygain.py` actually runs some of the tests (most are skipped in the CI build)
2. Comment out [the `_store_retry_once` patch](https://github.com/beetbox/beets/blob/8645f56512fa8918fd05c4f53bd1b65ace87ab41/test/test_replaygain.py#L82)
3. Run the tests

### Setup

* OS: 5.8.18-1-MANJARO
* Python version: 3.8.6
* beets version: https://github.com/beetbox/beets/commit/8645f56512fa8918fd05c4f53bd1b65ace87ab41
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

```yaml
directory: ~/code/beets/library
library: ~/code/beets/library/library.db

threaded: yes
parallel_threads: 2
original_year: yes

paths:
    default: $albumartist/%if{$original_year,$original_year,$year} - $album%aunique{}/$track $title
    singleton: $artist/singles/%if{$original_year,$original_year,$year} - $title
    comp: compilations/%if{$original_year,$original_year,$year} - $albumartist - $album%aunique{}/$track $artist - $title

pluginpath:
    - ~/code/beets/beets-copyartifacts/build/lib/beetsplug
    - ~/code/beets/beets-link/beetsplug
    - ~/.local/lib/python3.8/site-packages/beetsplug

plugins: discogs convert missing embedart info types duplicates edit fromfilename copyartifacts link replaygain lyrics artistcountry

replaygain:
#    backend: command
    backend: ffmpeg
#    backend: bs1770gain
#    backend: gstreamer
#    backend: audiotools

convert:
    dest: library/converted

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>"\*\|\\]': '_'
    ':': '-'
    '\?': '_'
    '\.$': '.'
    '\s+$': ''
    '^\s+': ''
    '^-': '_'

aunique:
    keys: albumartist album
    disambiguators: albumdisambig country albumtype year label catalognum releasegroupdisambig
    bracket: '()'

```

**Comment by sampsyo** [comment]
Thanks for the detailed account!
