### ISSUE TITLE
(Ubuntu 20.04 LTS) Can't get the app to run

### ISSUE THREAD

**Issue by LoosGuccreen** [beetbox/beets#3813]
Hello !

### Problem

When I try to do anything with (a fresh install of) the app, I get a python crash.

I installed it using ubuntu repo (but it should be the latest version)

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv
user configuration: /home/clement/snap/beets/6/.config/beets/config.yaml
data directory: /home/clement/snap/beets/6/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/snap/beets/6/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

Led to this problem:

```
I installed the soft.

I tried to setup manually the config file (without beet config -e since it didn't work) but unfortunately it didn't solve anything.

For reference I have this when I try to do beet config -e even using sudo:

$ beet config -e
error: Could not edit configuration: [Errno 13] Permission denied
```

### Setup

* OS: Ubuntu 20.04.1 LTS
* Python version: Python 3.8.5
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): nope, but it did change something, I have the error "beet: error: no such option: --plugin", which is technically not a crash.

My configuration (output of `beet config`) is:

```yaml
directory: /home/clement/kDrive/Documents/Musique/Sorted
library: ~/.config/beets/library.db

import:
    move: yes
    write: no
```

**Comment by jackwilsdon** [comment]
Please see #3674.
