### ISSUE TITLE
all beets commands return an error on macOS with Python 3.9

### ISSUE THREAD

**Issue by sdebruyn** [beetbox/beets#3829]
### Problem

Running this command in verbose (`-vv`) mode led to the output below:

```sh
➜ beet --verbose --version
no user configuration found at /Users/sam/.config/beets/config.yaml
data directory: /Users/sam/.config/beets
plugin paths:
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

### Setup

* OS: macOS 10.15.7 (Darwin mbpsam 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64)
* Python version: 
```sh
➜ python3 --version
Python 3.9.1
```
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

**Comment by sdebruyn** [comment]
Dupe of #3674
