### ISSUE TITLE
Not sure if it is actually a bug or a problem of installation or missing libraries

### ISSUE THREAD

**Issue by HappyCampero76** [beetbox/beets#3879]
beet import /home/user/Music/
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (... paste here ...)
beet -vv
user configuration: /home/user/.config/beets/config.yaml
data directory: /homeuser/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/dist-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/dist-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant


Led to this problem:

```
(paste here)
```

Here's a link to the music files that trigger the bug (if relevant):


### Setup

* OS: BackBox 7
* Python version: 3.8 latest i could install from synaptic
* beets version: no idea since i installed it with pip3
* Turning off plugins made problem go away (yes/no): any command i try to execute will give me always the same error above even asking for the version of beet,the only command doesn't give me any error is #  beets config -e

<!--
You can turn off plugins temporarily by passing --plugins= on the command line:

$ beet --plugins= version
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

beet: error: no such option: --plugins


My configuration (output of `beet config`) is:
directory: /tmp/music/
library: /tmp/music/musiclibrary.db

import:
 move: yes
 apikey: <APIKEY>

convert:
 auto: yes
 format: mp3

chroma:
    auto: no

acoustid:
    apikey: AbCd1234
    
    Any suggestion is welcome since i cannot find any solution about the problem.

**Comment by wisp3rwind** [comment]
Known issue which is fixed on master, see https://github.com/beetbox/beets/issues/3674
