### ISSUE TITLE
Python 3.10: Fix the web plugin

### ISSUE THREAD

**Issue by wisp3rwind** [beetbox/beets#3898]
https://github.com/beetbox/beets/pull/3896 shows a number of CI failures in the web plugin's tests. For some reason, `None` ends up being passed to `os.stat()`, which crashes. That could also be an issue with a library we depend on rather beets itself. Example test output:

```
2021-03-23T08:39:04.5229707Z ______________________ WebPluginTest.test_delete_item_id _______________________
2021-03-23T08:39:04.5230285Z 
2021-03-23T08:39:04.5231008Z self = <test.test_web.WebPluginTest testMethod=test_delete_item_id>
2021-03-23T08:39:04.5231648Z 
2021-03-23T08:39:04.5232203Z     def test_delete_item_id(self):
2021-03-23T08:39:04.5232767Z     
2021-03-23T08:39:04.5233901Z         web.app.config['READONLY'] = False
2021-03-23T08:39:04.5234582Z     
2021-03-23T08:39:04.5235149Z         # Create a temporary item
2021-03-23T08:39:04.5236133Z         item_id = self.lib.add(Item(title=u'test_delete_item_id',
2021-03-23T08:39:04.5236930Z                                     test_delete_item_id=1))
2021-03-23T08:39:04.5237496Z     
2021-03-23T08:39:04.5238128Z         # Check we can find the temporary item we just created
2021-03-23T08:39:04.5239145Z >       response = self.client.get('/item/' + str(item_id))
2021-03-23T08:39:04.5239750Z 
2021-03-23T08:39:04.5240282Z test/test_web.py:322: 
2021-03-23T08:39:04.5240876Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-03-23T08:39:04.5241871Z .tox/py-test/lib/python3.10/site-packages/werkzeug/test.py:1006: in get
2021-03-23T08:39:04.5242730Z     return self.open(*args, **kw)
2021-03-23T08:39:04.5243758Z .tox/py-test/lib/python3.10/site-packages/flask/testing.py:222: in open
2021-03-23T08:39:04.5244604Z     return Client.open(
2021-03-23T08:39:04.5245631Z .tox/py-test/lib/python3.10/site-packages/werkzeug/test.py:970: in open
2021-03-23T08:39:04.5246817Z     response = self.run_wsgi_app(environ.copy(), buffered=buffered)
2021-03-23T08:39:04.5248106Z .tox/py-test/lib/python3.10/site-packages/werkzeug/test.py:861: in run_wsgi_app
2021-03-23T08:39:04.5249159Z     rv = run_wsgi_app(self.application, environ, buffered=buffered)
2021-03-23T08:39:04.5250369Z .tox/py-test/lib/python3.10/site-packages/werkzeug/test.py:1096: in run_wsgi_app
2021-03-23T08:39:04.5252353Z     app_rv = app(environ, start_response)
2021-03-23T08:39:04.5254590Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:2464: in __call__
2021-03-23T08:39:04.5256451Z     return self.wsgi_app(environ, start_response)
2021-03-23T08:39:04.5260627Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:2450: in wsgi_app
2021-03-23T08:39:04.5261278Z     response = self.handle_exception(e)
2021-03-23T08:39:04.5262126Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:1867: in handle_exception
2021-03-23T08:39:04.5262752Z     reraise(exc_type, exc_value, tb)
2021-03-23T08:39:04.5263542Z .tox/py-test/lib/python3.10/site-packages/flask/_compat.py:39: in reraise
2021-03-23T08:39:04.5264078Z     raise value
2021-03-23T08:39:04.5264777Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:2447: in wsgi_app
2021-03-23T08:39:04.5265399Z     response = self.full_dispatch_request()
2021-03-23T08:39:04.5266251Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:1952: in full_dispatch_request
2021-03-23T08:39:04.5266905Z     rv = self.handle_user_exception(e)
2021-03-23T08:39:04.5267756Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:1821: in handle_user_exception
2021-03-23T08:39:04.5268392Z     reraise(exc_type, exc_value, tb)
2021-03-23T08:39:04.5269174Z .tox/py-test/lib/python3.10/site-packages/flask/_compat.py:39: in reraise
2021-03-23T08:39:04.5269710Z     raise value
2021-03-23T08:39:04.5270452Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:1950: in full_dispatch_request
2021-03-23T08:39:04.5271099Z     rv = self.dispatch_request()
2021-03-23T08:39:04.5271894Z .tox/py-test/lib/python3.10/site-packages/flask/app.py:1936: in dispatch_request
2021-03-23T08:39:04.5272636Z     return self.view_functions[rule.endpoint](**req.view_args)
2021-03-23T08:39:04.5273219Z beetsplug/web/__init__.py:146: in responder
2021-03-23T08:39:04.5273799Z     return flask.jsonify(_rep(entities[0], expand=is_expand()))
2021-03-23T08:39:04.5274334Z beetsplug/web/__init__.py:55: in _rep
2021-03-23T08:39:04.5275476Z     out['size'] = os.path.getsize(util.syspath(obj.path))
2021-03-23T08:39:04.5275977Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-03-23T08:39:04.5276216Z 
2021-03-23T08:39:04.5276515Z filename = None
2021-03-23T08:39:04.5276748Z 
2021-03-23T08:39:04.5277072Z     def getsize(filename):
2021-03-23T08:39:04.5277566Z         """Return the size of a file, reported by os.stat()."""
2021-03-23T08:39:04.5278058Z >       return os.stat(filename).st_size
2021-03-23T08:39:04.5278712Z E       TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
2021-03-23T08:39:04.5279167Z 
2021-03-23T08:39:04.5279958Z /opt/hostedtoolcache/Python/3.10.0-alpha.6/x64/lib/python3.10/genericpath.py:50: TypeError
```

**Comment by sampsyo** [comment]
Weird; good catch! I'm glad this code is tested.

It looks like `obj.path` is None, where `obj` should be an `Item` object. I don't immediately see how that can be the case; I thought `Item`s always had a `path` as long as they were in the database. Perhaps this is an artifact of the tests, for instance, that might construct incomplete `Item`s for the tests? In which case the fix might be to the test scaffolding rather than to the plugin itself.

**Comment by wisp3rwind** [comment]
What's really weird, though, is that this doesn't fail on Python `< 3.10`. Locally, I get
```
Python 3.9.2 (default, Feb 20 2021, 18:40:11)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.getsize(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
i.e. the same exception. So the issue can't be that `getsize()` used to accept `None` silently.

>  I thought Items always had a path as long as they were in the database.

I'm pretty sure that the `Item` in question has no path, since it is directly created using the `Item(...)` constructor and doesn't use any of the functions for creating test figures from `test._common` or `test.helper`. What might be going on here is that for some reason, `Item.path` used to be the empty string `""` and is now `None`. The empty string would not lead to a TypeError, but rather a `FileNotFoundError`, which the web plugin catches in the `OsError` handler.

```
Python 3.9.2 (default, Feb 20 2021, 18:40:11)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.getsize("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by sampsyo** [comment]
Huh, that certainly is a mystery. It doesn't get to the bottom of where the difference between the versions is coming from, but using one of those "stock" Item constructor functions might be the eventual solution.
