### ISSUE TITLE
Python 3.9/MacOS 10.15.7 install/configuration issue with Beets?

### ISSUE THREAD

**Issue by DarrenPIngram** [beetbox/beets#3926]
Installing per the user guide and the configuration is erroring out using Python 3.9. I cannot be sure where the problem lies. Python 3.9 is in the $PATH and all updates seemingly applied.

di@MacPro multimedia % beet config -p                          
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.9/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
di@MacPro multimedia % 

Python 3 seems (!) to be working, or at least it hasn't complained, with other applications, but I accept I am not the world's most experienced Python user.

di@MacPro multimedia % echo $PATH                                    
/Users/di/Library/Python/3.9:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
di@MacPro multimedia % python --version
Python 2.7.17
di@MacPro multimedia % python3 --version
Python 3.9.4
di@MacPro multimedia % 

Would appreciate some guidance as to whether I am using Beets wrong, or there's something that needs to be fixed (how?) at my end. Or, indeed, if there's an issue with Beets itself that's out of my control.

**Comment by wisp3rwind** [comment]
This is a known issue, see https://github.com/beetbox/beets/issues/3674; unfortunately we still haven't pushed a release with the fix. See the link for more information.

**Comment by DarrenPIngram** [comment]
OK, thank you for the pointer and update.
