### ISSUE TITLE
Lyrics plugin error "object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [beetbox/beets#3970]
### Problem

`beet lyrics` was left running for a while, worked fine until it stopped at some unidentified song that triggered:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beets/ui/__init__.py", line 1291, in main
    _raw_main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beets/ui/__init__.py", line 1278, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beetsplug/lyrics.py", line 792, in func
    opts.force_refetch or self.config['force'],
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beetsplug/lyrics.py", line 889, in fetch_item_lyrics
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beetsplug/lyrics.py", line 889, in <listcomp>
    lyrics = [self.get_lyrics(artist, title) for title in titles]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beetsplug/lyrics.py", line 922, in get_lyrics
    lyrics = backend.fetch(artist, title)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beetsplug/lyrics.py", line 347, in fetch
    self.fetch_url(hit["result"]["url"]))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/beetsplug/lyrics.py", line 376, in _scrape_lyrics_from_html
    html = BeautifulSoup(html, "html.parser")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bs4/__init__.py", line 310, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
```

### Setup

* OS: macOS High Sierra
* Python version: 3.7
* beets version: 1.5.0

Relevant issue: https://github.com/beetbox/beets/issues/479

**Comment by 2V3EvG4LMJFdRe** [comment]
No one else has this? Should I run some version so that it doesn't happen?

```
lyrics:
    auto: yes
    force: yes
    sources: genius musixmatch lyricwiki lyrics
    google_API_key: redacted
    fallback: ''
    import.write: yes
```

**Comment by wisp3rwind** [comment]
No, this seems to be an actual bug, the fix from #480 apparently either got lost or didn't apply to all lyrics sources in the first place. I'll have a try at fixing this.

This probably didn't show up before because it only manifests when the lyrics provider's server is unreachable. If your connection is down entirely, that would show up much quicker.

**Comment by 2V3EvG4LMJFdRe** [comment]
Thanks a lot, hopefully you can get it. I could have posted the verbose log, but I'm going through my music year by year and the error shows up a solid hour into the process or so. Sometimes it doesn't show up at all.

**Comment by 2V3EvG4LMJFdRe** [comment]
Similar. I'm getting this a lot:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==1.6.1', 'console_scripts', 'beet')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/ui/__init__.py", line 1304, in main
    _raw_main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/ui/__init__.py", line 1291, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/ui/commands.py", line 1034, in import_func
    import_files(lib, paths, query)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/ui/commands.py", line 974, in import_files
    session.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/util/pipeline.py", line 311, in run
    out = self.coro.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/util/pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/importer.py", line 1395, in lookup_candidates
    task.lookup_candidates()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/importer.py", line 661, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/autotag/match.py", line 461, in tag_album
    for matched_candidate in hooks.album_candidates(items,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/autotag/hooks.py", line 632, in album_candidates
    yield from plugins.candidates(items, artist, album, va_likely, extra_tags)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/plugins.py", line 384, in candidates
    yield from plugin.candidates(items, artist, album, va_likely,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/plugins.py", line 733, in candidates
    albums = [self.album_for_id(album_id=r['id']) for r in results]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beets/plugins.py", line 733, in <listcomp>
    albums = [self.album_for_id(album_id=r['id']) for r in results]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beetsplug/spotify.py", line 260, in album_for_id
    track = self._get_track(track_data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/beetsplug/spotify.py", line 300, in _get_track
    album = track_data['album']['name']
TypeError: 'NoneType' object is not subscriptable
```
