### ISSUE TITLE
beets python3.9 error

### ISSUE THREAD

**Issue by DOFfactory** [beetbox/beets#3975]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet --version
```

Led to this problem:

```
Traceback (most recent call last):
  File "/opt/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/opt/lib/python3.9/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/opt/lib/python3.9/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/opt/lib/python3.9/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/opt/lib/python3.9/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/opt/lib/python3.9/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/opt/lib/python3.9/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/opt/lib/python3.9/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/opt/lib/python3.9/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/opt/lib/python3.9/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Linux
* Python version: Python 3.9.4
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): no

**Comment by wisp3rwind** [comment]
See https://github.com/beetbox/beets/issues/3674
