### ISSUE TITLE
Does not work in Fedora 35 with Python 3.10 (pip install)

### ISSUE THREAD

**Issue by crankedguy** [beetbox/beets#4193]
Hello,

actually beets cannot even be started on Fedora 35 with python 3.10 when installed via pip. You immediately get a key error. There seems something wrong in the mb integration.

```
pip install --user --upgrade beets
Collecting beets
  Using cached beets-1.6.0.tar.gz (1.7 MB)
Requirement already satisfied: unidecode in ./.local/lib/python3.10/site-packages (from beets) (1.3.2)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/lib/python3.10/site-packages (from beets) (0.5)
Requirement already satisfied: pyyaml in ./.local/lib/python3.10/site-packages (from beets) (6.0)
Requirement already satisfied: mediafile>=0.2.0 in ./.local/lib/python3.10/site-packages (from beets) (0.9.0)
Requirement already satisfied: confuse>=1.0.0 in ./.local/lib/python3.10/site-packages (from beets) (1.7.0)
Requirement already satisfied: munkres>=1.0.0 in ./.local/lib/python3.10/site-packages (from beets) (1.1.4)
Requirement already satisfied: jellyfish in ./.local/lib/python3.10/site-packages (from beets) (0.8.9)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.10/site-packages (from mediafile>=0.2.0->beets) (1.16.0)
Requirement already satisfied: mutagen>=1.45 in /usr/lib/python3.10/site-packages (from mediafile>=0.2.0->beets) (1.45.1)
Building wheels for collected packages: beets
  Building wheel for beets (setup.py) ... done
  Created wheel for beets: filename=beets-1.6.0-py3-none-any.whl size=499716 sha256=384f9e00164eaa4f72ee8fc45423ce94b031d043bc9f323ab80cf6583c2bf257
  Stored in directory: /home/<user>/.cache/pip/wheels/93/89/2d/645f35f3a8028288591e30728c8d3cbffce250b0f40a9c84de
Successfully built beets
Installing collected packages: beets
Successfully installed beets-1.6.0

beet
Traceback (most recent call last):
  File "/home/<user>/.local/bin/beet", line 5, in <module>
    from beets.ui import main
  File "/home/<user>/.local/lib/python3.10/site-packages/beets/ui/__init__.py", line 39, in <module>
    from beets.autotag import mb
  File "/home/<user>/.local/lib/python3.10/site-packages/beets/autotag/__init__.py", line 23, in <module>
    from .hooks import (  # noqa
  File "/home/<user>/.local/lib/python3.10/site-packages/beets/autotag/hooks.py", line 25, in <module>
    from beets.autotag import mb
  File "/home/<user>/.local/lib/python3.10/site-packages/beets/autotag/mb.py", line 74, in <module>
    if "work-level-rels" in musicbrainzngs.VALID_BROWSE_INCLUDES['recording']:
KeyError: 'recording'

```

**Comment by crankedguy** [comment]
Ah I found out what it was, actually Fedora provides an extremely old version of musicbrainzngs as a package, which was installed as a dependency and actually this one was pulled in from the system as can be seen above...
```
libmusicbrainz5.x86_64                                                                                   5.1.0-18.fc35                                                                       @fedora
python3-musicbrainzngs.noarch                                                                            0.5-24.fc35                                                                         @fedora
```

After installing 0.7.1 with --user from pip this works, no errors anymore. Sorry
