### ISSUE TITLE
WinError 17 for Album Art

### ISSUE THREAD

**Issue by TheOttoman2012** [beetbox/beets#4544]
Traceback (most recent call last):
  File "C:\Python372\lib\site-packages\beets\util\__init__.py", line 496, in move
    os.replace(path, dest)
OSError: [WinError 17] The system cannot move the file to a different disk drive: '\\\\?\\C:\\Users\\xxxxxxx\\AppData\\Local\\Temp\\tmpi9lylkhj.jpg' -> '\\\\?\\D:\\Music\\Sorted\\Artist\\Album\\cover.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python372\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python372\Scripts\beet.exe\__main__.py", line 7, in <module>
  File "C:\Python372\lib\site-packages\beets\ui\__init__.py", line 1285, in main
    _raw_main(args)
  File "C:\Python372\lib\site-packages\beets\ui\__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python372\lib\site-packages\beets\ui\commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "C:\Python372\lib\site-packages\beets\ui\commands.py", line 943, in import_files
    session.run()
  File "C:\Python372\lib\site-packages\beets\importer.py", line 342, in run
    pl.run_sequential()
  File "C:\Python372\lib\site-packages\beets\util\pipeline.py", line 390, in run_sequential
    list(self.pull())
  File "C:\Python372\lib\site-packages\beets\util\pipeline.py", line 467, in pull
    out = coro.send(msg)
  File "C:\Python372\lib\site-packages\beets\util\pipeline.py", line 170, in coro
    task = func(*(args + (task,)))
  File "C:\Python372\lib\site-packages\beets\importer.py", line 1569, in manipulate_files
    session=session,
  File "C:\Python372\lib\site-packages\beets\importer.py", line 766, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "C:\Python372\lib\site-packages\beets\plugins.py", line 488, in send
    result = handler(**arguments)
  File "C:\Python372\lib\site-packages\beets\plugins.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "C:\Python372\lib\site-packages\beetsplug\fetchart.py", line 1063, in assign_art
    self._set_art(task.album, candidate, not self.src_removed)
  File "C:\Python372\lib\site-packages\beetsplug\fetchart.py", line 1048, in _set_art
    album.set_art(candidate.path, delete)
  File "C:\Python372\lib\site-packages\beets\library.py", line 1317, in set_art
    util.move(path, artdest)
  File "C:\Python372\lib\site-packages\beets\util\__init__.py", line 499, in move
    prefix=py3_path(b'.' + os.path.basename(dest)),
TypeError: can't concat str to bytes

**Comment by TheOttoman2012** [comment]
Just to rule it out, I upgraded to Python 311 and got essentially the same error

**Comment by sampsyo** [comment]
This should be fixed on master; please see #4252.
