### ISSUE TITLE
Unable to run snap version of beets under Fedora 37

### ISSUE THREAD

**Issue by brianread108** [beetbox/beets#4597]
### Problem

Running this command:
```
/var/lib/snapd/snap/bin/beet help
```

Led to this problem:

```
Traceback (most recent call last):
  File "/snap/beets/6/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/snap/beets/6/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/snap/beets/6/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```
Python is 3.11.

mmm - wondering why the files are in python3.8?

There are another set of beet files under python3.11.

I'll remove them all and start again...

**Comment by brianread108** [comment]
ok, fixed it by uninstalling snap and rpm and then re-installing rpm. I must have tried to install beet using snap at some point before!!

**Comment by wisp3rwind** [comment]
That bug was fixed quite some time ago, see https://github.com/beetbox/beets/pull/3621
