### ISSUE TITLE
Echo Nest Unknown Error

### ISSUE THREAD

**Issue by yoasif** [beetbox/beets#481]
When importing http://musicbrainz.org/release/fc9c511a-a3a6-4069-abcd-0ea65449c969 using the latest source and the echonest plugin enabled, I get a "pyechonest.util.EchoNestIOError: Echo Nest Unknown Error" reproducibly. 

```
:~$ beet -v import -A '/quadra/music/Downloaded Albums/Banco de Gaia/album/Banco de Gaia - 2013-04-08 - Apollo'
data directory: /home/asif/.config/beets
library database: /home/asif/.musiclibrary.blb
library directory: /quadra/music/Downloaded Albums
/quadra/music/Downloaded Albums/Banco de Gaia/album/Banco de Gaia - 2013-04-08 - Apollo
0 of 9 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
echonest: (u'Echo Nest API Error 5: The Identifier specified does not exist',)
echonest: lookup by MBID failed
echonest: got song through search: Banco de Gaia - Lamentations [182.06621]
echonest: metadata: bpm = 70.82
echonest: metadata: energy = 0.25012
echonest: metadata: liveness = 0.134912
echonest: metadata: speechiness = 0.034224
echonest: metadata: acousticness = 0.712262
echonest: metadata: valence = 0.013836
echonest: metadata: danceability = 0.22675
echonest: metadata: echonest_id = SODCFPR13E36C52D6B
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
echonest: (u'Echo Nest API Error 5: The Identifier specified does not exist',)
echonest: lookup by MBID failed
echonest: got song through search: Banco de Gaia - Wimble Toot [479.05288]
echonest: metadata: bpm = 99.999
echonest: metadata: energy = 0.761175
echonest: metadata: liveness = 0.126003
echonest: metadata: speechiness = 0.032143
echonest: metadata: acousticness = 0.040603
echonest: metadata: valence = 0.426442
echonest: metadata: danceability = 0.604544
echonest: metadata: echonest_id = SODDWFD13E36C54663
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
echonest: (u'Echo Nest API Error 5: The Identifier specified does not exist',)
echonest: lookup by MBID failed
echonest: got song through search: Banco de Gaia - Eternal Sunshine [445.71955]
echonest: metadata: bpm = 127.997
echonest: metadata: energy = 0.696588
echonest: metadata: liveness = 0.317226
echonest: metadata: speechiness = 0.054773
echonest: metadata: acousticness = 0.006521
echonest: metadata: valence = 0.73494
echonest: metadata: danceability = 0.792567
echonest: metadata: echonest_id = SOEMAXR13E36C56934
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
echonest: (u'Echo Nest API Error 5: The Identifier specified does not exist',)
echonest: lookup by MBID failed
echonest: got song through search: Banco de Gaia - For Such a Time [512.95955]
echonest: metadata: bpm = 157.953
echonest: metadata: energy = 0.535834
echonest: metadata: liveness = 0.367458
echonest: metadata: speechiness = 0.050277
echonest: metadata: acousticness = 0.218338
echonest: metadata: valence = 0.220222
echonest: metadata: danceability = 0.383271
echonest: metadata: echonest_id = SOXBVVQ13E36C58840
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
echonest: (u'Echo Nest API Error 5: The Identifier specified does not exist',)
echonest: lookup by MBID failed
echonest: got song through search: Banco de Gaia - Apollon [400.86621]
echonest: metadata: bpm = 98.0
echonest: metadata: energy = 0.855483
echonest: metadata: liveness = 0.046618
echonest: metadata: speechiness = 0.093345
echonest: metadata: acousticness = 0.010288
echonest: metadata: valence = 0.84206
echonest: metadata: danceability = 0.729957
echonest: metadata: echonest_id = SONRSRI13E36C5A572
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
echonest: (u'Echo Nest API Error 5: The Identifier specified does not exist',)
echonest: lookup by MBID failed
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.2', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 810, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 802, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 845, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 783, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 341, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 243, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 815, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 380, in imported
    song = self.fetch_song(item)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 341, in fetch_song
    song = method(item)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 185, in search
    return self._flatten_song(self._pick_song(songs, item))
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/echonest.py", line 130, in _pick_song
    dist = abs(item.length - song.audio_summary['duration'])
  File "/usr/local/lib/python2.7/dist-packages/pyechonest/song.py", line 111, in get_audio_summary
    response = self.get_attribute('profile', bucket='audio_summary')
  File "/usr/local/lib/python2.7/dist-packages/pyechonest/proxies.py", line 179, in get_attribute
    return super(SongProxy, self).get_attribute(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyechonest/proxies.py", line 23, in get_attribute
    result = util.callm("%s/%s" % (self._object_type, method_name), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyechonest/util.py", line 246, in callm
    raise EchoNestIOError(error=e.reason)
pyechonest.util.EchoNestIOError: Echo Nest Unknown Error
```

I am happy to provide further details as needed.

**Comment by darthanubis** [comment]
echonest: IO error: Echo Nest Unknown Error

Using a personal api did not resolve for me.

**Comment by Freso** [comment]
@darthanubis That's not a very informative statement. Please read https://beets.readthedocs.org/en/latest/faq.html#report-a-bug-in-beets
