### ISSUE TITLE
No matching release error

### ISSUE THREAD

**Issue by qxrv** [beetbox/beets#4891]
Beets does not seem to fetch any release from Musicbrainz. This is my first time using it and I was testing it out with an album that I know is already well-tagged. I can't seem to troubleshoot the "MusicBrainz not reachable in release search with query" and was wondering what the problem is. The same error is also shown when trying to manually enter MBID (I) or enter search (E). Can confirm that the same problem repeats itself for any album I try to import.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import Downloads/1990\ -\ Heaven\ or\ Las\ Vegas\ \[CD\]
```

Led to this problem:

```
user configuration: /Users/hivernale/.config/beets/config.yaml
data directory: /Users/hivernale/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/hivernale/Music/beets_lib/musiclibrary.db
library directory: /Users/hivernale/Music/Mu
Sending event: library_opened
Sending event: import_begin
state file could not be read: [Errno 2] No such file or directory: '/Users/hivernale/.config/beets/state.pickle'
Sending event: import_task_created
Sending event: import_task_start
Looking up: /Users/hivernale/Downloads/1990 - Heaven or Las Vegas [CD]
Tagging Cocteau Twins - Heaven or Las Vegas
No album ID found.
Search terms: Cocteau Twins - Heaven or Las Vegas
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'heaven or las vegas', 'artist': 'cocteau twins', 'tracks': '10'}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 497, in _safe_read
    f = opener.open(req)
        ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/beets/autotag/mb.py", line 511, in match_album
    res = musicbrainzngs.search_releases(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 978, in search_releases
    return _do_mb_search('release', query, fields, limit, offset, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 782, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 690, in _mb_request
    resp = _safe_read(opener, req, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/musicbrainzngs/musicbrainz.py", line 525, in _safe_read
    raise NetworkError(cause=exc)
musicbrainzngs.musicbrainz.NetworkError: caused by: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

Error: MusicBrainz not reachable in release search with query {'release': 'heaven or las vegas', 'artist': 'cocteau twins', 'tracks': '10'}
Evaluating 0 candidates.

/Users/hivernale/Downloads/1990 - Heaven or Las Vegas [CD] (10 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
No matching release found for 10 tracks.
For help, see: https://beets.readthedocs.org/en/latest/faq.html#nomatch
```

### Setup

* OS: macOS 13.5.1
* Python version: 3.11.3
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no plugins installed

My configuration (output of `beet config`) is:

```yaml
directory: ~/Music/Mu/
library: ~/Music/beets_lib/musiclibrary.db
```

**Comment by qxrv** [comment]
Nevermind, managed to fix this by installing the latest version of Python from the official website.
