### ISSUE TITLE
beets crashes with an UTF-8 encoding error

### ISSUE THREAD

**Issue by mgoltzsche** [beetbox/beets#5017]
### Problem

During import, when I manually specify an artist name that contains mutated vowels, beets crashes with an UTF-8 encoding error.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import some/directory/with/music
user configuration: /data/beets/config.yaml
data directory: /data/beets
plugin paths: 
lastgenre: Loading canonicalization tree /usr/local/lib/python3.12/site-packages/beetsplug/lastgenre/genres-tree.yaml
Sending event: pluginload
library database: /data/musiclibrary.db
library directory: /data/music
Sending event: library_opened
Sending event: import_begin
Import of the directory:
/data/ytimport
was interrupted. Resume (Y/n)?
...
# selection (default 1), Skip, Use as-is, Enter search, enter Id, aBort? e
Artist: Ben Böhmer
Track: Begin Again
```

Led to this problem:

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beets/ui/__init__.py", line 1285, in main
    _raw_main(args)
  File "/usr/local/lib/python3.12/site-packages/beets/ui/__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.12/site-packages/beets/ui/commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python3.12/site-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/usr/local/lib/python3.12/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python3.12/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.12/site-packages/beets/util/pipeline.py", line 311, in run
    out = self.coro.send(msg)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beets/util/pipeline.py", line 170, in coro
    task = func(*(args + (task,)))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beets/importer.py", line 1400, in user_query
    task.choose_match(session)
  File "/usr/local/lib/python3.12/site-packages/beets/importer.py", line 949, in choose_match
    choice = session.choose_item(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beets/ui/commands.py", line 785, in choose_item
    post_choice = choice.callback(self, task)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beets/ui/commands.py", line 660, in manual_search
    return autotag.tag_item(task.item, artist, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beets/autotag/match.py", line 518, in tag_item
    for track_info in hooks.item_candidates(item, search_artist, search_title):
  File "/usr/local/lib/python3.12/site-packages/beets/plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "/usr/local/lib/python3.12/site-packages/beets/autotag/hooks.py", line 643, in item_candidates
    yield from mb.match_track(artist, title)
  File "/usr/local/lib/python3.12/site-packages/beets/autotag/mb.py", line 537, in match_track
    res = musicbrainzngs.search_recordings(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/musicbrainz.py", line 971, in search_recordings
    return _do_mb_search('recording', query, fields, limit, offset, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/musicbrainz.py", line 782, in _do_mb_search
    return _do_mb_query(entity, '', [], params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/musicbrainz.py", line 728, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/musicbrainz.py", line 417, in __call__
    return self.fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/musicbrainz.py", line 640, in _mb_request
    value = value.encode('utf8')
            ^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 13: surrogates not allowed
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: alpine:3.18.4 (docker container)
* Python version: 3.12.0
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
directory: /data/music
library: /data/musiclibrary.db

plugins:
- ytimport
- lastgenre
- info
- describe
- smartplaylist
- random
- web

import:
    write: yes
    copy: yes
    incremental: yes
    quiet: no
ytimport:
    directory: /data/ytimport

    import: yes
    likes: no
    max_likes: 3
    set: like=1
    min_length: 60
    max_length: 7200
    split_tracks: yes
    group_albums: no
    auth_headers:
    max_length_nochapter: 600
smartplaylist:
    relative_to: /data/playlists
    playlist_dir: /data/playlists
    forward_slash: no
    playlists: [{name: all.m3u, query: ''}, {name: all-by-album-genre.m3u, query: albumartist+ year+ album+ track+ genre+ artist+ title+}]
    auto: yes
    prefix: REDACTED
    urlencode: no
lastgenre:
    auto: yes
    canonical: yes
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    source: album
    force: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
describe:
    auto: no
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes
```

**Comment by JOJ0** [comment]
I think that is fixed in latest git version. Try installing from the git repo directly. https://beets.readthedocs.io/en/latest/contributing.html#getting-the-source

**Comment by mgoltzsche** [comment]
Great! Though, it turns out I cannot reproduce the bug also using the old beets version. I think entering a vovel as artist name was not the problem after all but the `\udcc3` character appearing within the name of a track that was imported in the background maybe - not sure which files I imported at the time.

**Comment by mgoltzsche** [comment]
Using the beets version from the master branch, I just imported 200 tracks that I downloaded and imported recently into a new empty beets library which should cover the problematic ones: all went fine now, there was no error.
(Though, I ran the import non-interactively using `quiet_fallback: asis` this time but I assume the bug would have manifested as an error by now if it still existed. Therefore I am closing the issue.)
