### ISSUE TITLE
Web Plugin: ModuleNotFoundError: No module named 'beetsplug.web'

### ISSUE THREAD

**Issue by lamyergeier** [beetbox/beets#5030]
# Install

```
sudo dnf install -y beet

$ pip install flask
Requirement already satisfied: flask in /home/lamy/.local/lib/python3.11/site-packages (3.0.0)
Requirement already satisfied: Werkzeug>=3.0.0 in /home/lamy/.local/lib/python3.11/site-packages (from flask) (3.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /home/lamy/.local/lib/python3.11/site-packages (from flask) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /home/lamy/.local/lib/python3.11/site-packages (from flask) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /home/lamy/.local/lib/python3.11/site-packages (from flask) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /home/lamy/.local/lib/python3.11/site-packages (from flask) (1.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/lamy/.local/lib/python3.11/site-packages (from Jinja2>=3.1.2->flask) (2.1.3)
$ pip install flask-cors
Requirement already satisfied: flask-cors in /home/lamy/.local/lib/python3.11/site-packages (4.0.0)
Requirement already satisfied: Flask>=0.9 in /home/lamy/.local/lib/python3.11/site-packages (from flask-cors) (3.0.0)
Requirement already satisfied: Werkzeug>=3.0.0 in /home/lamy/.local/lib/python3.11/site-packages (from Flask>=0.9->flask-cors) (3.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /home/lamy/.local/lib/python3.11/site-packages (from Flask>=0.9->flask-cors) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /home/lamy/.local/lib/python3.11/site-packages (from Flask>=0.9->flask-cors) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /home/lamy/.local/lib/python3.11/site-packages (from Flask>=0.9->flask-cors) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /home/lamy/.local/lib/python3.11/site-packages (from Flask>=0.9->flask-cors) (1.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/lamy/.local/lib/python3.11/site-packages (from Jinja2>=3.1.2->Flask>=0.9->flask-cors) (2.1.3)
```

### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv web
user configuration: /home/lamy/.config/beets/config.yaml
data directory: /home/lamy/.config/beets
plugin paths: 
** error loading plugin inline:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'beetsplug.inline'

** error loading plugin convert:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'beetsplug.convert'

** error loading plugin web:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'beetsplug.web'

Sending event: pluginload
library database: /home/lamy/.config/beets/library.db
library directory: /home/lamy/Music
Sending event: library_opened
error: unknown command 'web'
```

### Setup

* OS:  Fedora
* Python version: 3.12 
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): yes

```
$ beet --plugins= version
beets version 1.6.0
Python version 3.12.0
no plugins loaded
```

My configuration (output of `beet config`) is:

```yaml
plugins: inline convert web
```

**Comment by jackwilsdon** [comment]
This seems similar to some of the other search path issues we've seen in the past (#4028, #3730 to name a few).

Does `/usr/lib/python3.12/site-packages/beetsplug` exist? If so, does `__init__.py` exist in there?

It might be useful to see your module search path too: `python -c 'import sys; print(sys.path)'`

**Comment by lamyergeier** [comment]
@jackwilsdon I have 2 versions of python (and pip) installed (using dnf and homebrew):

```
$ type pip
pip is a function
pip () 
{ 
    if [[ "${1}" == "install" ]]; then
        command pip install --user "${@:2}";
    else
        command pip "$@";
    fi
}
pip is /home/linuxbrew/.linuxbrew/bin/pip
pip is /usr/bin/pip
$ pip --version
pip 23.3.1 from /mnt/Data/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/pip (python 3.11)
$ /usr/bin/pip --version
pip 23.2.1 from /usr/lib/python3.12/site-packages/pip (python 3.12)
$ type python
python is /usr/bin/python
$ type python3
python3 is /home/linuxbrew/.linuxbrew/bin/python3
python3 is /usr/bin/python3
$ python3 --version
Python 3.11.6
$ /usr/bin/python3 --version
Python 3.12.0
```

I think this is the source of the problem.
