### ISSUE TITLE
A plugin I use is causing a weird issue

### ISSUE THREAD

**Issue by CallMeMarcellino** [beetbox/beets#5180]
### Problem

Running this command:

```sh
$ beet import BLACKPINK
```

Led to this problem:

```
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\beets\util\__init__.py", line 496, in move
    os.replace(path, dest)
OSError: [WinError 17] The system cannot move the file to a different disk drive: '\\\\?\\C:\\Users\\lino\\AppData\\Local\\Temp\\tmpveqrudt4.jpg' -> '\\\\?\\S:\\Music\\Albums\\With One Artist\\BLACKPINK × Selena Gomez\\Ice Cream (2020)\\cover.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\beet.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\beets\ui\__init__.py", line 1285, in main
    _raw_main(args)
  File "C:\Python312\Lib\site-packages\beets\ui\__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python312\Lib\site-packages\beets\ui\commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "C:\Python312\Lib\site-packages\beets\ui\commands.py", line 943, in import_files
    session.run()
  File "C:\Python312\Lib\site-packages\beets\importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Python312\Lib\site-packages\beets\util\pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Python312\Lib\site-packages\beets\util\pipeline.py", line 358, in run
    self.coro.send(msg)
  File "C:\Python312\Lib\site-packages\beets\util\pipeline.py", line 170, in coro
    task = func(*(args + (task,)))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\beets\importer.py", line 1566, in manipulate_files
    task.manipulate_files(
  File "C:\Python312\Lib\site-packages\beets\importer.py", line 766, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "C:\Python312\Lib\site-packages\beets\plugins.py", line 488, in send
    result = handler(**arguments)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\beets\plugins.py", line 145, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\beetsplug\fetchart.py", line 1063, in assign_art
    self._set_art(task.album, candidate, not self.src_removed)
  File "C:\Python312\Lib\site-packages\beetsplug\fetchart.py", line 1048, in _set_art
    album.set_art(candidate.path, delete)
  File "C:\Python312\Lib\site-packages\beets\library.py", line 1317, in set_art
    util.move(path, artdest)
  File "C:\Python312\Lib\site-packages\beets\util\__init__.py", line 499, in move
    prefix=py3_path(b'.' + os.path.basename(dest)),
                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can't concat str to bytes
```

### Setup

* OS: Windows
* Python version: 3.12.2
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): yes

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - musixmatch
    - genius
    - tekstowo
directory: S:\Music
library: C:\Users\lino\Beets\musiclibrary.db

paths:
    singleton: Singles\$artist\$track - $title (${year})
    albumtype:soundtrack: Soundtracks\$albumartist\$album (${year})\$track - $title
    comp: Albums\With Multiple Artists\$album (${year})\$track - $title
    default: Albums\With One Artist\$albumartist\$album (${year})\$track - $title

import:
    move: yes
    write: yes
art_filename: cover
language: en
pluginpath: C:\Users\lino\Beets\plugins

plugins: chroma embedart fetchart replaygain scrub mbsync lastgenre fromfilename albumtypes lyrics web
embedart:
    remove_art_file: yes
    maxwidth: 0
    auto: yes
    compare_threshold: 0
    ifempty: no
    quality: 0
replaygain:
    backend: ffmpeg
    overwrite: no
    auto: yes
    threads: 32
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
include: ['C:\Users\lino\Beets\config.yaml']
scrub:
    auto: yes
albumtypes:
    types:
    - [ep, EP]
    - [single, Single]
    - [soundtrack, OST]
    - [live, Live]
    - [compilation, Anthology]
    - [remix, Remix]
    ignore_va: [compilation]
    bracket: '[]'
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: yes
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
chroma:
    auto: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes
```

**Comment by CallMeMarcellino** [comment]
Please note that the music file was on the S disk, which is where my library is, however my main beets config is on my main disk.
