### ISSUE TITLE
Beet build failure

### ISSUE THREAD

**Issue by ArtemSmaznov** [beetbox/beets#5202]
### Problem

Not sure if this is the right place to report this but I am trying to build the latest git version of beets from aur `beets-git` but the build is failing.

```sh
$ paru -S beets-git
```

Led to this problem:

```
...
Sending event: import_task_files
Sending event: album_imported
.Sending event: database_change
Sending event: database_change
.Sending event: database_change
Sending event: database_change
..Traceback (most recent call last):
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1146, in _make_table
    rows = tx.query("PRAGMA table_info(%s)" % table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 955, in query
    cursor = self.db._connection().execute(statement, subvals)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1051, in _connection
    conn = self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/library.py", line 1589, in _create_connection
    conn = super()._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1065, in _create_connection
    conn = sqlite3.connect(
           ^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/ui/__init__.py", line 1759, in _open_library
    lib = library.Library(
          ^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/library.py", line 1580, in __init__
    super().__init__(path, timeout=timeout)
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1032, in __init__
    self._make_table(model_cls._table, model_cls._fields)
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1145, in _make_table
    with self.transaction() as tx:
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 947, in __exit__
    self.db._connection().commit()
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1051, in _connection
    conn = self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/library.py", line 1589, in _create_connection
    conn = super()._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/beets/dbcore/db.py", line 1065, in _create_connection
    conn = sqlite3.connect(
           ^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

.library database: /tmp/tmpwpgbfbpg/nonexist/0.6466913731773644
library directory: /tmp/tmpwpgbfbpg/libdir
...........S.....S.......Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
.Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
.
======================================================================
FAIL: test_match_album (test.test_mb.MBLibraryTest.test_match_album)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/test/test_mb.py", line 837, in test_match_album
    sp.assert_called_with(artist="hello", release="there", limit=5)
  File "/usr/lib/python3.11/unittest/mock.py", line 939, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: search_releases(artist='hello', release='there', limit=5)
  Actual: search_releases(limit=15, release='there', artist='hello')
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Searching for MusicBrainz releases with: {'release': 'there', 'artist': 'hello'}
beets: DEBUG: Requesting MusicBrainz release d2a6f856-b553-40a0-ac54-a321e8e2da99
beets: DEBUG: Sending event: mb_track_extract
beets: DEBUG: Sending event: mb_album_extract
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_match_track (test.test_mb.MBLibraryTest.test_match_track)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/artem/.cache/paru/clone/beets-git/src/beets/test/test_mb.py", line 784, in test_match_track
    p.assert_called_with(artist="hello", recording="there", limit=5)
  File "/usr/lib/python3.11/unittest/mock.py", line 939, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: search_recordings(artist='hello', recording='there', limit=5)
  Actual: search_recordings(limit=15, artist='hello', recording='there')
-------------------- >> begin captured logging << --------------------
beets: DEBUG: Sending event: mb_track_extract
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1754 tests in 43.797s

FAILED (SKIP=39, failures=2)
==> ERROR: A failure occurred in check().
    Aborting...
error: failed to build 'beets-git-1.6.0.r1302.gdae525741-1':
error: packages failed to build: beets-git-1.6.0.r1302.gdae525741-1
```
I am not familiar with the build process but it looks like there are 3 issues here:

1. something to do with the db.py
2. test_match_album test fail
3. test_match_track test fail

### Setup

* OS: Arch Linux 6.8.7-zen1-1-zen
* Python version: Python 3.11.8
* beets version: beets version 1.6.1
* Turning off plugins made problem go away (yes/no): n/a

**Comment by wisp3rwind** [comment]
Please report this to the AUR first, at a brief glance there's at least one thing that the `PKGBUILD` should change: We've been using `pytest` for quite some time(see https://github.com/beetbox/beets/pull/3661) in place of `nose`. That may or may not the problem.
