### ISSUE TITLE
Unresolved Modules with version 2.1.0

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#5511]
### Unresolved modules with version 2.1.0

Running this command in verbose (`-vv`) mode:

```sh
 beet -vv
user configuration: /home/glenn/.config/beets/config.yaml
data directory: /home/glenn/.config/beets
plugin paths: 
** error loading plugin embedart:
Traceback (most recent call last):
  File "/home/glenn/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glenn/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beetsplug/embedart.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

** error loading plugin fetchart:
Traceback (most recent call last):
  File "/home/glenn/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glenn/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beetsplug/fetchart.py", line 23, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

** error loading plugin lastgenre:
Traceback (most recent call last):
  File "/home/glenn/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glenn/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beetsplug/lastgenre/__init__.py", line 29, in <module>
    import pylast
ModuleNotFoundError: No module named 'pylast'

error: replaygain initialization failed: Failed to load GStreamer: python-gi not found

```

Led to this problem:

```
$ pipx uninstall beets
$ pipx install beets
```
### Setup

* OS: Ubuntu 24.10
* Python version:  3.12.7
* beets version: 2.1.0
* Turning off plugins made problem go away (yes/no): no

**Comment by snejus** [comment]
It seems like you have plugins `embedart`, `fetchart`, `lastgenre` and `replaygain` enabled, however their dependencies are missing. Have you installed `beets` with extras for each of those plugins? For example see [fetchart docs](https://beets.readthedocs.io/en/latest/plugins/fetchart.html). 

In your case the command is probably `pipx install beets[embedart,fetchart,pylast,replaygain]`

**Comment by gboysko** [comment]
Thanks, @snejus. I had not installed those plugins. I was following the FAQ's instructions on installation, but didn't notice that. I uninstalled, then installed again using this command:

```sh
$ pipx install beets beets[embedart,fetchart,pylast,replaygain] --force
Installing to existing venv 'beets'
  installed package beets 2.1.0, installed using Python 3.12.7
  These apps are now globally available
    - beet
done! ✨ 🌟 ✨
Installing to existing venv 'beets'
Fatal error from pip prevented installation. Full pip output in file:
    /home/glenn/.local/state/pipx/log/cmd_2024-11-22_15.01.37_pip_errors.log

pip seemed to fail to build package:
    PyGObject

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../meson.build:1:0: ERROR: Compiler cc cannot compile programs.
    error: metadata-generation-failed

⚠️  Not removing existing venv /home/glenn/.local/share/pipx/venvs/beets
    because it was not created in this session
Error installing beets from spec 'beets[embedart,fetchart,pylast,replaygain]'.
```

Not sure how to resolve `PyGObject`.

**Comment by snejus** [comment]
See [replaygain](https://beets.readthedocs.io/en/latest/plugins/replaygain.html) docs.

It seems like GStreamer is missing from your system. Have you been using replaygain previously or did you only enable it now? If your current configuration was in place before the update, I expected system dependencies to be present already!

**Comment by gboysko** [comment]
I had used replaygain previously. I'm not sure how it was lost. I will try to resolve all of the various dependencies. Even after installing `python3-gi`, I'm still unable to install due to an unresolved dependency of `PyGObject`. I'll keep digging...

**Comment by snejus** [comment]
What sort of system are you using? It seems like system dependencies are missing, for example on Ubuntu you'd want to install

```fish
sudo apt update
sudo apt install ffmpeg gobject-introspection libgirepository1.0-dev
```

**Comment by gboysko** [comment]
I'm using Ubuntu 24. Is this information already in your docs?

**Comment by gboysko** [comment]
Sorry no luck, even after installing dependencies.

```sh
$ sudo apt update
[OUTPUT omitted--all success]

$ sudo apt install ffmpeg gobject-introspection libgirepository1.0-dev
ffmpeg is already the newest version (7:7.0.2-3ubuntu1).
ffmpeg set to manually installed.
gobject-introspection is already the newest version (1.80.1-4).
gobject-introspection set to manually installed.
libgirepository1.0-dev is already the newest version (1.80.1-4).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 27

$ pipx install beets[embedart,fetchart,lastgenre,scrub,replaygain] --force
Fatal error from pip prevented installation. Full pip output in file:
    /home/glenn/.local/state/pipx/log/cmd_2024-11-26_15.41.03_pip_errors.log

pip seemed to fail to build package:
    PyGObject

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../meson.build:1:0: ERROR: Compiler cc cannot compile programs.
    error: metadata-generation-failed

Error installing beets from spec 'beets[embedart,fetchart,lastgenre,replaygain,scrub]'.
```
Not sure what else I can do. I was able to use the prior version of `beets`, fwiw.

**Comment by gboysko** [comment]
I'm including the error log file.

[cmd_2024-11-26_15.41.03_pip_errors.log](https://github.com/user-attachments/files/17925592/cmd_2024-11-26_15.41.03_pip_errors.log)

The file indicates failures to compile?

**Comment by snejus** [comment]
Is replaygain working fine with the old version? Could you run `pipx runpip beets list` and show me the list of packages installed in this environment?

**Comment by snejus** [comment]
See this: https://www.perplexity.ai/search/system-dependencies-for-pygobj-Uijl8uXyTROBu1U06vREFQ#1

**Comment by gboysko** [comment]
@snejus Yes, replaygain was indeed working fine with the old version. I cannot run `pipx runpip beets list` since it fails to install the newer version. I remain blocked on installation due to my inability to install PyGObject.

I followed the instructions in the Perplexity.ai page to install both the dependencies for PyGObject as well as additional dependencies. When I try to install PyGObject as per the page, namely:

```
$ pip install PyGObject
```

I get an `error: externally-managed-environment` error. I never had this much problem installing beets before. 

I also tried:

```
$ pipx install PyGObject
```

but with the same outcome.

**Comment by snejus** [comment]
Apologies that you're having so many issues installing this. I realize that our documentation is not at all up to date regarding the system dependencies that `replaygain` plugin needs.

Could you try installing these dependencies and try again please?

```
sudo apt install python3-gi gir1.2-gstreamer-1.0 gstreamer1.0-plugins-good
```

**Comment by gboysko** [comment]
It appears that the dependencies installed correctly, but the problem has
always been PyGObject. After the above command succeeded, I ran:

```
pipx install beets[embedart,fetchart,lastgenre,scrub,replaygain] --force
```

And got this error message:

```
Fatal error from pip prevented installation. Full pip output in file:
    /home/glenn/.local/state/pipx/log/cmd_2025-01-21_17.22.20_pip_errors.log

pip seemed to fail to build package:
    PyGObject

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../meson.build:1:0: ERROR: Compiler cc cannot compile programs.
    error: metadata-generation-failed
```

What is the proper way to install the C compiler for Ubuntu 24?

**Comment by gboysko** [comment]
Final Update: I have successfully installed beets after uninstalling `gcc` from HomeBrew and using `sudo apt install gcc`. By doing this, I was able to install beets using `pipx`. 

I hope that this can help someone else.

**Comment by snejus** [comment]
Ah I missed out on the fact that you are using MacOS! Happy that you managed to figure this out. Homebrew / system incompatibilities are the worst: I remember that every issue I had with this took me ages to figure out.

Happy that you're finally sorted though, well done!

**Comment by gboysko** [comment]
FWIW, I was not using MacOS, but Ubuntu. Thanks!

**Comment by enigmatixator** [comment]
I encountered a similar error when installing `beets` via `pipx` on ubuntu 24.04 with `replaygain` plugin enabled:
```
pipx install beets[chroma,fetchart,embedart,lyrics,replaygain,scrub,web]
```
in my case, running the following command prior to `beets` installation seemed to resolve the issue:
```
sudo apt install libgirepository-2.0-dev
```

**Comment by c0wg0d** [comment]
I'm on Windows and I still cannot install the replaygain plugin because of the PyGObject issue.  I've tried installing the C++ desktop tools in Visual Studio, I've tried the MSYS2 system, nothing works.

**Comment by snejus** [comment]
Which `beets` version are you using?

**Comment by c0wg0d** [comment]
beets version 2.5.1
Python version 3.12.10
plugins: embedart, fetchart, ftintitle, lastgenre, musicbrainz, scrub, the
