### ISSUE TITLE
name 'unicode' is not defined

### ISSUE THREAD

**Issue by anderflash** [beetbox/beets#820]
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.6', 'console_scripts', 'beet')()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2147, in load
    ['**name**'])
  File "/usr/lib/python3.4/site-packages/beets/**init**.py", line 18, in <module>
    import beets.library
  File "/usr/lib/python3.4/site-packages/beets/library.py", line 25, in <module>
    from beets.mediafile import MediaFile, MutagenError
  File "/usr/lib/python3.4/site-packages/beets/mediafile.py", line 331, in <module>
    class StorageStyle(object):
  File "/usr/lib/python3.4/site-packages/beets/mediafile.py", line 361, in StorageStyle
    def **init**(self, key, as_type=unicode, suffix=None, float_places=2):
NameError: name 'unicode' is not defined

**Comment by kyleterry** [comment]
@anderflash you probably have pip2 or pip2.7 on your system. Try using that to install beets.

**Comment by brutus** [comment]
Stumbled upon this too. No biggie, but until you got Py3 support ready maybe drop a note about `pip2` and all that into the guide.

**Comment by simonbcn** [comment]
I have installed git version of beets on Arch Linux with `sudo python2 setup.py install` and then I try to import an album but:
```
$ beet im -CL Al entierro de una hoja seca                           
Traceback (most recent call last):
  File "/usr/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.18', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/beets-1.3.18-py2.7.egg/beets/__init__.py", line 20, in <module>
    import beets.library
  File "/usr/lib/python2.7/site-packages/beets-1.3.18-py2.7.egg/beets/library.py", line 25, in <module>
    from unidecode import unidecode
ImportError: No module named unidecode
```

However `unicode` is installed with python2.7:
```
$ sudo -H pip2 install -U unidecode
Requirement already up-to-date: unidecode in /usr/lib/python2.7/site-packages

$ ls /usr/lib/python2.7/site-packages/unidecode 
util.py  util.pyc
```

**Comment by jmbeach** [comment]
@sampsyo I agree with @brutus. Using `pip2 install beets` fixed my problem. I would think that it is worth mentioning in the docs.

**Comment by jrobeson** [comment]
sometimes it is pip, sometimes it is pip2, so both would need to be mentioned

**Comment by jrobeson** [comment]
@jmbeach : note, commenting on a really old bug report might not get noticed (in this project and many others). You should probably open a new issue (or PR) with a suggested change to the README

**Comment by jmbeach** [comment]
@jrobeson Gotcha. Thanks.
