### ISSUE TITLE
ImportFeeds:  fix/disable/catch symlink usage on windows

### ISSUE THREAD

**Issue by Schweinepriester** [beetbox/beets#840]
... because it doesnt work?

but it seems possible: http://en.wikipedia.org/wiki/NTFS_symbolic_link
http://lifehacker.com/5496652/how-to-use-symlinks-in-windows

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.6', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 967, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 958, in _raw_m
ain
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python27\lib\site-packages\beets\ui\commands.py", line 816, in import
_func
    import_files(lib, paths, query)
  File "C:\Python27\lib\site-packages\beets\ui\commands.py", line 788, in import
_files
    session.run()
  File "C:\Python27\lib\site-packages\beets\importer.py", line 262, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Python27\lib\site-packages\beets\util\pipeline.py", line 345, in run
    self.coro.send(msg)
  File "C:\Python27\lib\site-packages\beets\util\pipeline.py", line 158, in coro

    task = func(*(args + (task,)))
  File "C:\Python27\lib\site-packages\beets\importer.py", line 1076, in manipula
te_files
    task.finalize(session)
  File "C:\Python27\lib\site-packages\beets\importer.py", line 395, in finalize
    self._emit_imported(session.lib)
  File "C:\Python27\lib\site-packages\beets\importer.py", line 427, in _emit_imp
orted
    plugins.send('album_imported', lib=lib, album=self.album)
  File "C:\Python27\lib\site-packages\beets\plugins.py", line 379, in send
    handler(**args)
  File "C:\Python27\lib\site-packages\beetsplug\importfeeds.py", line 138, in al
bum_imported
    _record_items(lib, album.album, album.items())
  File "C:\Python27\lib\site-packages\beetsplug\importfeeds.py", line 127, in _r
ecord_items
    os.symlink(syspath(path), syspath(dest))
AttributeError: 'module' object has no attribute 'symlink'
```

**Comment by sammydynamo-dev** [comment]
Hi! I'm a student in the CodePath AI301 open-source program and I'd like to take this one as a contribution.

From digging into the code: when `importfeeds` is configured with `formats: link`, a symlink-creation failure (e.g. on Windows, where creating a symlink needs elevated privilege) raises out of the `link()` helper in `beets.util` and aborts the **entire** `beet import` run — even though the music files were already imported. (The original 2014 traceback is obsolete, but the abort-on-symlink-failure path still exists.)

Plan, matching your earlier note ("we should catch and skip this"):
- Wrap the `link()` call in the importfeeds `link` branch (`beetsplug/importfeeds.py`) in a `try/except beets.util.FilesystemError`, log a per-item warning that includes the path via `self._log.warning(...)`, and continue the import instead of aborting.
- Add a regression test that mocks `link()` to raise `FilesystemError` and asserts a warning is logged and no exception escapes.
- Add a `changelog.rst` "Bug fixes" entry citing `:bug:`840``.

I'll keep it strictly to that scope. One question: do you prefer catching `beets.util.FilesystemError` (what `link()` raises) over a broader `OSError`, and is warning-level logging the right call here? Happy to match your preference. Thanks!
